import json, re, csv, shutil, subprocess, os
from pathlib import Path

ROOT = Path('/mnt/data/ped_work/klinik_v395_work')
REPORT = ROOT/'reports/pediatrics_glossary_expansion'
REPORT.mkdir(parents=True, exist_ok=True)

payload = json.load(open(REPORT/'pediatrics-text-fields-v404.json', encoding='utf-8'))
texts = payload['texts']
source_inventory = payload['sourceInventory']
glossary_payload = json.load(open(REPORT/'pediatrics-active-glossary-terms-v404.json', encoding='utf-8'))

def norm(s):
    s = str(s or '').strip()
    s = s.replace('İ','i').replace('I','ı').lower().replace('ı','i')
    for a,b in [('ğ','g'),('ü','u'),('ş','s'),('ö','o'),('ç','c')]: s = s.replace(a,b)
    s = re.sub(r'[^\w+/.-]+',' ',s,flags=re.UNICODE)
    return re.sub(r'\s+',' ',s).strip()

def slug(s):
    x = norm(s)
    x = re.sub(r'[^a-z0-9]+','-',x).strip('-')
    return x[:90] or 'term'

active_norms = set()
for g in glossary_payload:
    if g.get('term'): active_norms.add(norm(g['term']))
    for a in g.get('aliases') or []:
        if a: active_norms.add(norm(a))

items = []
for t in texts:
    nt = norm(t.get('text',''))
    if nt:
        items.append({**t, 'normText': nt})

def count_occ(term, aliases=None):
    keys = [norm(term)] + [norm(a) for a in (aliases or [])]
    keys = [k for k in keys if k]
    c = 0
    for it in items:
        tx = it['normText']
        if any(k and k in tx for k in keys): c += 1
    return c

def examples(term, aliases=None, maxn=2):
    keys = [norm(term)] + [norm(a) for a in (aliases or [])]
    keys = [k for k in keys if k]
    out=[]
    seen=set()
    for it in items:
        tx = it['normText']
        if any(k and k in tx for k in keys):
            key=(it['path'], it['text'][:120])
            if key in seen: continue
            seen.add(key)
            out.append({'sourceFilePath': it['path'], 'text': it['text'][:440]})
            if len(out)>=maxn: break
    return out


def e(term, sub, short, detail, pearl, diff, nested=None, aliases=None, priority='P1', leak='low', ambiguity='low', phrase=True):
    aliases = aliases or []
    # keep canonical in aliases for matching variants, later deduped
    return dict(term=term, aliases=aliases, subcategory=sub, short=short, detail=detail, pearl=pearl, diff=diff, nested=nested or [], priority=priority, answerLeakRisk=leak, ambiguityRisk=ambiguity, phraseOnly=phrase)

C=[]
# Neonatology / newborn care
C += [
 e('Yenidoğan sepsisi','Neonatoloji / Enfeksiyon','Yenidoğanda hipotermi/ateş, beslenme bozulması, letarji ve perfüzyon bozukluğu ile seyredebilir ağır enfeksiyon tablosudur.','Yenidoğan bağışıklık yanıtı olgun olmadığı için enfeksiyon her zaman yüksek ateşle gelmeyebilir; hipotermi, emmeme, soluk-gri görünüm ve apne sepsis ipucu olabilir. Tedavi mantığı kültürleri aldıktan sonra ampirik antibiyotiği geciktirmemektir.','Yenidoğanda kötü beslenme + hipotermi/letarji sepsis kabul edilip kültür + ampirik antibiyotik zinciriyle yönetilir.','Basit viral ÜSYE’de genel durum genellikle korunur; yenidoğan sepsisinde perfüzyon, bilinç ve beslenme hızla bozulabilir.',['Kan kültürü','Ampirik antibiyotik','Hipotermi'], priority='P0'),
 e('Erken başlangıçlı yenidoğan sepsisi','Neonatoloji / Enfeksiyon','İlk 72 saatte ortaya çıkan ve çoğunlukla maternal-genital yol kaynaklı yenidoğan sepsisidir.','Grup B streptokok ve E. coli klasik etkenlerdir. Prematürite, uzamış membran rüptürü, maternal ateş ve koryoamniyonit risk artırır; klinik silik olabileceği için karar vital bulgu ve beslenme/perfüzyon üzerinden verilir.','İlk 72 saat sepsisinde maternal riskler ve GBS/E. coli düşünülür.','Geç başlangıçlı sepsis daha çok hastane/kateter veya çevresel temaslarla ilişkilidir.',['Grup B streptokok','Koryoamniyonit','Ampirik antibiyotik'], aliases=['erken neonatal sepsis']),
 e('Geç başlangıçlı yenidoğan sepsisi','Neonatoloji / Enfeksiyon','Yaşamın 72. saatinden sonra gelişen yenidoğan sepsisidir.','Prematüre yoğun bakım hastalarında kateter, ventilasyon, cilt bariyeri bozukluğu ve hastane florası etken olabilir. Klinik karar yine ateşten çok genel durum, beslenme, solunum ve perfüzyon değişikliğiyle verilir.','Prematüre + kateter/yoğun bakım + yeni kötüleşme geç neonatal sepsis düşündürür.','Erken sepsis maternal geçişle; geç sepsis çevresel/hastane ilişkili etkenlerle daha çok bağlantılıdır.',['Yenidoğan sepsisi','Kateter ilişkili enfeksiyon','Prematürite'], aliases=['geç neonatal sepsis']),
 e('Yenidoğan hiperbilirubinemisi','Neonatoloji / Sarılık','Yenidoğanda serum bilirubin düzeyinin artmasıyla cilt ve skleralarda sararma gelişmesidir.','İndirekt bilirubin artışı fizyolojik olabilse de ilk 24 saatte sarılık, hızlı yükseliş, prematürite veya hemoliz risklidir. Pediatri sorusunda kritik ayrım fizyolojik sarılık ile fototerapi/kan değişimi gerektirebilecek patolojik sarılık arasındadır.','İlk 24 saatte sarılık patolojik kabul edilir; hemoliz ve ciddi hiperbilirubinemi araştırılır.','Direkt bilirubin artışı kolestazı düşündürür; indirekt artışta hemoliz, fizyolojik sarılık ve anne sütü ilişkisi öne çıkar.',['İndirekt hiperbilirubinemi','Fototerapi','Kernikterus'], aliases=['neonatal hiperbilirubinemi'], priority='P0'),
 e('İlk 24 saatte sarılık','Neonatoloji / Sarılık alarmı','Yaşamın ilk günü ortaya çıkan sarılıktır ve genellikle patolojik kabul edilir.','Bu zamanlama fizyolojik sarılıktan çok hemoliz, kan grubu uygunsuzluğu, enfeksiyon veya eritrosit enzim/membran kusurlarını düşündürür. Bu yüzden bilirubin düzeyi ve yükselme hızı acil değerlendirilir.','İlk 24 saatte sarılık = fizyolojik deme; hemoliz ve ağır hiperbilirubinemi riski düşün.','Fizyolojik sarılık genellikle 24 saatten sonra belirir; ilk gün sarılığı alarmdır.',['ABO hemolitik hastalık','Rh izoimmünizasyonu','Direkt Coombs testi'], aliases=['ilk gün sarılığı'], priority='P0'),
 e('İndirekt hiperbilirubinemi','Neonatoloji / Bilirubin metabolizması','Konjuge olmamış bilirubin düzeyinin yükselmesidir.','Lipid çözünürlüğü nedeniyle ağır düzeylerde kan-beyin bariyerini geçip kernikterus riski yaratabilir. Yenidoğanda hemoliz, fizyolojik olgunlaşmamış konjugasyon ve anne sütü sarılığı bu grupta düşünülür.','İndirekt bilirubin yükselmesi kernikterus riski nedeniyle fototerapi eşikleriyle izlenir.','Direkt hiperbilirubinemi kolestaz ve hepatobiliyer hastalık uyarısıdır; indirekt form hemoliz/konjugasyon yetersizliğiyle ilişkilidir.',['Kernikterus','Fototerapi','ABO hemolitik hastalık']),
 e('Direkt hiperbilirubinemi','Neonatoloji / Kolestaz','Konjuge bilirubin artışıdır ve yenidoğanda kolestaz alarmı kabul edilir.','Direkt bilirubin artışı fizyolojik sarılık gibi izlenmez; biliyer atrezi, neonatal hepatit, enfeksiyon ve metabolik hastalıklar araştırılır. Akolik dışkı ve koyu idrar biliyer obstrüksiyon lehinedir.','Uzamış sarılık + akolik dışkı/koyu idrar direkt bilirubin ve biliyer atrezi açısından alarmdır.','Anne sütü sarılığı indirekt bilirubin artışıyla gider; direkt bilirubin kolestatik hastalık düşündürür.',['Biliyer atrezi','Akolik dışkı','Kasai portoenterostomi'], priority='P0'),
 e('Fototerapi','Neonatoloji / Sarılık tedavisi','İndirekt bilirubini suda çözünebilen izomerlere dönüştürerek atılımını artıran ışık tedavisidir.','Fototerapi bilirubin düzeyi, yaş saati ve risk faktörlerine göre başlanır. Asıl amaç bilirubinin nörotoksik düzeye çıkmasını önlemektir; direkt hiperbilirubinemide temel tedavi değildir.','Yenidoğan sarılığında karar bilirubin değeri kadar postnatal saat ve risk faktörüne bağlıdır.','Kan değişimi daha ağır veya fototerapiye rağmen tehlikeli düzeylerde gündeme gelir.',['İndirekt hiperbilirubinemi','Kernikterus','Kan değişimi']),
 e('Kernikterus','Neonatoloji / Bilirubin ensefalopatisi','Ağır indirekt hiperbilirubineminin bazal gangliyonlar başta olmak üzere beyinde nörotoksik hasar yapmasıdır.','Bilirubin albümine bağlı kapasiteyi aşınca beyne geçebilir; letarji, hipotoni/hipertoni, tiz ağlama ve nörolojik sekel riski ortaya çıkar. Bu nedenle erken tanı, fototerapi ve gerekirse kan değişimi hayatîdir.','Ağır indirekt bilirubin + nörolojik bulgu kernikterus açısından acildir.','Direkt bilirubin beyne geçme açısından aynı klasik kernikterus riskini taşımaz; indirekt form nörotoksiktir.',['İndirekt hiperbilirubinemi','Fototerapi','Kan değişimi'], priority='P0'),
 e('Kan değişimi','Neonatoloji / Sarılık tedavisi','Ağır yenidoğan hiperbilirubinemisinde bilirubin ve antikor yüklü kanın uzaklaştırılması için yapılan exchange transfüzyondur.','Fototerapiye rağmen tehlikeli düzeyde bilirubin, akut bilirubin ensefalopatisi bulgusu veya ağır hemolizde düşünülür. TUS mantığında bu, rutin sarılık tedavisi değil nörotoksisiteyi önleyen ileri basamaktır.','Bilirubin ensefalopatisi bulgusu varsa fototerapi beklemek yerine kan değişimi düşünülür.','Fototerapi çoğu indirekt sarılıkta ilk basamaktır; kan değişimi ağır/dirençli olgular içindir.',['Fototerapi','Kernikterus','ABO hemolitik hastalık'], aliases=['exchange transfüzyon','exchange transfusion']),
 e('ABO hemolitik hastalık','Neonatoloji / Hemoliz','Anne O, bebeğin A veya B olduğu durumlarda maternal anti-A/B antikorlarına bağlı yenidoğan hemolizidir.','Rh hastalığına göre daha sık ancak genellikle daha hafif olabilir; erken sarılık ve pozitif/negatif olabilen Coombs paterniyle sorulabilir. Hemoliz indirekt bilirubini artırarak fototerapi gereksinimini doğurur.','Anne O + bebek A/B + erken sarılık ABO hemolitik hastalığı düşündürür.','Rh izoimmünizasyonu daha ağır anemi/hidrops riskiyle seyredebilir.',['İlk 24 saatte sarılık','Direkt Coombs testi','İndirekt hiperbilirubinemi']),
 e('Rh izoimmünizasyonu','Neonatoloji / Hemolitik hastalık','Rh negatif annenin Rh pozitif fetüse karşı anti-D antikoru geliştirmesiyle oluşan hemolitik hastalıktır.','Maternal IgG plasentayı geçerek fetal eritrosit yıkımı yapar; ağır olguda fetal anemi ve hidrops gelişebilir. Rh immün globulin profilaksisi korunmada temel noktadır.','Rh uygunsuzluğunda sorun maternal anti-D IgG’nin fetal eritrositleri yıkmasıdır.','ABO hastalığı daha sık ve genellikle daha hafif; Rh hastalığı ağır fetal anemi yapabilir.',['Hidrops fetalis','Direkt Coombs testi','Rh immün globulin']),
 e('Anne sütü sarılığı','Neonatoloji / Uzamış indirekt sarılık','İyi beslenen sağlıklı bebekte ikinci haftadan sonra uzayan indirekt hiperbilirubinemidir.','Bebek iyi görünümlü, kilo alımı yeterli ve direkt bilirubin normal ise benign seyirli olabilir. Ancak uzamış sarılıkta önce kolestaz, hipotiroidi ve enfeksiyon gibi patolojik nedenler dışlanmalıdır.','İyi bebek + 2. hafta sonrası indirekt sarılık anne sütü sarılığını düşündürür; direkt bilirubini kontrol et.','Biliyer atrezide akolik dışkı/koyu idrar ve direkt bilirubin artışı beklenir.',['İndirekt hiperbilirubinemi','Direkt hiperbilirubinemi','Biliyer atrezi']),
 e('Biliyer atrezi','Neonatoloji / Kolestatik hastalık','Ekstrahepatik safra yollarının obliterasyonu ile giden yenidoğan kolestaz nedenidir.','Uzamış sarılık, akolik dışkı, koyu idrar ve direkt bilirubin artışı tipiktir. Erken Kasai portoenterostomisi prognoz için kritik olduğundan “bekle-gör” yaklaşımı uygun değildir.','Uzamış sarılık + akolik dışkı = direkt bilirubin bak ve biliyer atreziyi geciktirme.','Anne sütü sarılığı iyi bebekte indirekt bilirubin artışı yapar; biliyer atrezi kolestatik paterndir.',['Direkt hiperbilirubinemi','Akolik dışkı','Kasai portoenterostomi'], priority='P0'),
 e('Akolik dışkı','Neonatoloji / Kolestaz bulgusu','Safranın barsağa ulaşamaması nedeniyle dışkının açık/kil renginde olmasıdır.','Yenidoğanda akolik dışkı biliyer atrezi gibi kolestatik hastalıklar için güçlü alarmdır. Bu bulgu indirekt sarılıktan farklı olarak hepatobiliyer akımın bozulduğunu düşündürür.','Akolik dışkı yenidoğan sarılığında biliyer atrezi alarmıdır.','Normal sarı dışkı anne sütü sarılığıyla uyumlu olabilir; akolik dışkı obstrüktif/kolestatik süreci düşündürür.',['Biliyer atrezi','Direkt hiperbilirubinemi','Kasai portoenterostomi']),
 e('Kasai portoenterostomi','Neonatoloji / Cerrahi tedavi','Biliyer atrezide safra drenajını sağlamak için yapılan portoenterostomi ameliyatıdır.','Erken dönemde uygulanması karaciğer hasarını azaltabilir ve transplantasyon ihtiyacını geciktirebilir. Pediatri sorusunda biliyer atrezi tanısının gecikmemesinin nedeni bu zaman duyarlı cerrahidir.','Biliyer atrezide tanı gecikirse Kasai başarısı azalır.','Fototerapi indirekt sarılığın tedavisidir; biliyer atrezi cerrahi kolestaz sorunudur.',['Biliyer atrezi','Akolik dışkı','Direkt hiperbilirubinemi']),
 e('Respiratuvar distres sendromu','Neonatoloji / Solunum','Prematüre yenidoğanda surfaktan eksikliğine bağlı alveol kollapsı ve solunum sıkıntısı tablosudur.','Tip II pnömosit olgunlaşması yetersiz olduğunda yüzey gerilimi artar, atelektazi gelişir ve gaz değişimi bozulur. Doğumdan kısa süre sonra takipne, inleme, retraksiyon ve grafide retikülogranüler görünüm beklenir.','Prematüre + erken solunum sıkıntısı + surfaktan eksikliği = neonatal RDS.','TTN daha çok term/erken term bebekte geçici sıvı emilim gecikmesiyle olur; RDS surfaktan eksikliğidir.',['Surfaktan','Tip II pnömosit','Retikülogranüler görünüm'], aliases=['neonatal RDS','yenidoğan RDS'], priority='P0'),
 e('Retikülogranüler görünüm','Neonatoloji / Akciğer grafisi','Neonatal RDS’de yaygın ince granüler opasiteler ve düşük akciğer hacmi paternidir.','Alveoler kollaps ve diffüz atelektazi grafide bu görünümü oluşturur. Prematüre bebekte erken solunum sıkıntısıyla birlikte surfaktan eksikliğini destekler.','Prematüre RDS’de grafide retikülogranüler görünüm ve hava bronkogramları beklenir.','TTN’de hiperinflasyon ve fissürlerde sıvı daha tipiktir; RDS’de düşük hacim ve granüler görünüm ön plandadır.',['Respiratuvar distres sendromu','Surfaktan','Hava bronkogramı']),
 e('Hava bronkogramı','Neonatoloji / Akciğer grafisi','Alveoller opaklaştığında hava dolu bronşların grafide belirginleşmesidir.','RDS gibi alveoler hastalıklarda çevre alveol kollabe/opak olduğu için bronş içindeki hava kontrast oluşturur. Klinik bağlama göre pnömoni veya atelektaziyle de ilişkilendirilebilir.','RDS’de retikülogranüler görünümle birlikte hava bronkogramı tanıyı destekler.','Tek başına spesifik değildir; klinik ve diğer grafi bulgularıyla yorumlanır.',['Respiratuvar distres sendromu','Retikülogranüler görünüm','Atelektazi']),
 e('Nekrotizan enterokolit','Neonatoloji / Gastrointestinal acil','Özellikle prematürelerde bağırsak duvarında inflamasyon, iskemik hasar ve nekrozla giden acil tablodur.','Beslenme intoleransı, batın distansiyonu, kanlı dışkı ve sistemik kötüleşme ile gelir. Direkt grafide pnömatozis intestinalis veya portal ven gazı varsa enteral beslenme kesilir, geniş spektrum antibiyotik ve cerrahi izlem gerekir.','Prematüre + batın distansiyonu + kanlı dışkı + pnömatozis intestinalis = NEK.','Basit gastroenteritte bağırsak duvarında gaz ve sistemik nekroz paterni beklenmez.',['Pnömatozis intestinalis','Portal ven gazı','Prematürite'], aliases=['NEK','NEC'], priority='P0'),
 e('Pnömatozis intestinalis','Neonatoloji / Görüntüleme','Bağırsak duvarı içinde gaz görülmesidir ve nekrotizan enterokolit için klasik radyolojik bulgudur.','Mukozal hasar ve bakteriyel gaz üretimi bağırsak duvarında gaz birikimine yol açar. Prematüre bebekte bu bulgu klinik kötüleşmeyle birleştiğinde NEK yönetimini hızlandırır.','Prematüre bebekte pnömatozis intestinalis NEK için yüksek verimli ipucudur.','Normal intestinal gaz lümen içindedir; pnömatozis duvar içi gazdır.',['Nekrotizan enterokolit','Portal ven gazı','Batın distansiyonu'], priority='P0'),
 e('Portal ven gazı','Neonatoloji / Görüntüleme','Bağırsak duvarından portal venöz sisteme geçen gazın görüntülemede görülmesidir.','Nekrotizan enterokolit gibi ağır bağırsak duvarı hasarlarında gelişebilir. Klinik tabloda sistemik toksisiteyle birlikteyse hastalığın ağırlaştığını düşündürür.','NEK’te portal ven gazı ağır bağırsak duvarı hasarını destekler.','Lümen içi gazdan farklı olarak portal ven dağılımında periferik karaciğer gazı şeklinde izlenir.',['Nekrotizan enterokolit','Pnömatozis intestinalis','Bağırsak nekrozu']),
 e('Bilöz kusma','Neonatoloji / Cerrahi alarm','Safra içeren yeşil kusmadır ve yenidoğanda intestinal obstrüksiyon/volvulus açısından acil kabul edilir.','Yenidoğanda bilöz kusma malrotasyon-volvulus gibi barsak kanlanmasını bozabilecek acilleri düşündürür. Stabilizasyon sonrası üst GIS kontrast çalışması ve cerrahi değerlendirme geciktirilmez.','Yenidoğanda bilöz kusma cerrahi acildir; pilor stenozu tipik olarak safrasızdır.','Safrasız projektil kusma pilor stenozuna gider; yeşil bilöz kusma distal obstrüksiyon alarmıdır.',['Malrotasyon-volvulus','Üst GIS pasaj grafisi','Pilor stenozu'], priority='P0'),
 e('Malrotasyon-volvulus','Neonatoloji / Cerrahi acil','Barsak rotasyon anomalisi zemininde orta bağırsak dönmesi ve vasküler kompromis gelişmesidir.','Yenidoğanda bilöz kusma, batın hassasiyeti ve dolaşım bozukluğu varsa bağırsak iskemisi riski nedeniyle acil cerrahi değerlendirme gerekir. Tanı gecikirse nekroz ve şok gelişebilir.','Bilöz kusma + hasta yenidoğan = malrotasyon-volvulus düşün, cerrahiyi geciktirme.','Pilor stenozu safrasız kusar; volvulusta kusma bilöz olabilir ve iskemi riski taşır.',['Bilöz kusma','Üst GIS pasaj grafisi','Bağırsak iskemisi'], aliases=['midgut volvulus'], priority='P0'),
 e('Üst GIS pasaj grafisi','Neonatoloji / Görüntüleme','Yenidoğanda malrotasyon-volvulus şüphesinde duodenum ve jejunum yerleşimini değerlendiren kontrast çalışmadır.','Bilöz kusmalı stabil bebekte duodenojejunal bileşke pozisyonu ve corkscrew görünümü gibi bulgularla tanıya yardım eder. Şok veya peritonit varsa görüntüleme cerrahiyi geciktirmemelidir.','Bilöz kusmada stabil hastada üst GIS pasaj grafisi malrotasyonu araştırır.','Abdominal USG invajinasyonda ilk tercihtir; malrotasyonda üst GIS pasaj grafisi klasik tanı aracıdır.',['Malrotasyon-volvulus','Bilöz kusma','Corkscrew görünümü']),
 e('Pilor stenozu','Pediatrik gastroenteroloji / Kusma','Süt çocuğunda pilor kası hipertrofisine bağlı gastrik çıkış obstrüksiyonudur.','Tipik olarak 2–8 haftalık erkek bebekte safrasız projektil kusma, kusmaya rağmen açlık ve hipokloremik hipokalemik metabolik alkaloz görülür. Önce sıvı-elektrolit düzeltilir, sonra piloromiyotomi yapılır.','Safrasız projektil kusma + aç bebek + metabolik alkaloz pilor stenozudur.','Bilöz kusma malrotasyon-volvulus alarmıdır; pilor stenozunda kusma safrasızdır.',['Safrasız fışkırır kusma','Hipokloremik metabolik alkaloz','Piloromiyotomi'], aliases=['hipertrofik pilor stenozu'], priority='P0'),
 e('Safrasız fışkırır kusma','Pediatrik gastroenteroloji / Kusma paterni','Safra içermeyen, güçlü ve projektil kusma paternidir.','Pilor stenozunda tıkanıklık safra kanalının proksimalinde olduğu için kusma safrasızdır. Bebek kusmasına rağmen aç görünür; elektrolit bozukluğu ve dehidratasyon gelişebilir.','Safrasız projektil kusma pilor stenozunu; bilöz kusma volvulusu düşündürür.','Regürjitasyon pasif ve hafiftir; projektil kusma çıkış obstrüksiyonu lehinedir.',['Pilor stenozu','Hipokloremik metabolik alkaloz','Dehidratasyon'], aliases=['projektil kusma','fışkırır kusma']),
 e('Piloromiyotomi','Pediatrik cerrahi / Tedavi','Hipertrofik pilor stenozunda hipertrofik pilor kasının kesilmesi işlemidir.','Cerrahi tedavi kalıcı çözüm sağlar ancak öncesinde hipovolemi ve hipokloremik alkaloz düzeltilmelidir. Soru tuzağı doğrudan ameliyata gitmek değil önce stabilizasyonu seçmektir.','Pilor stenozunda önce sıvı-elektrolit düzelt, sonra piloromiyotomi.','Volvulus acil cerrahidir; pilor stenozunda elektrolit stabilizasyonu ameliyat öncesi şarttır.',['Pilor stenozu','Hipokloremik metabolik alkaloz','Sıvı resüsitasyonu']),
 e('Mekonyum ileusu','Pediatrik gastroenteroloji / Kistik fibrozis','Yenidoğanda koyu yapışkan mekonyumun ileumda tıkanıklık oluşturmasıdır.','Kistik fibrozisin erken bulgusu olabilir; mekonyum çıkaramama, batın distansiyonu ve kusma ile gelir. Bu bulgu CFTR ilişkili ekzokrin salgı koyulaşmasını klinik olarak gösterir.','Yenidoğanda mekonyum ileusu varsa kistik fibrozis düşün.','Hirschsprung’da ganglion hücresi yokluğu ve geç mekonyum; mekonyum ileusunda yapışkan sekresyon tıkanıklığı vardır.',['Kistik fibrozis','CFTR','Pankreatik yetmezlik']),
 e('Kistik fibrozis','Pediatrik pulmonoloji / Genetik hastalık','CFTR kanal kusuruna bağlı koyu sekresyonlar, kronik akciğer hastalığı ve pankreatik yetmezlikle seyreden otozomal resesif hastalıktır.','Klor kanal bozukluğu hava yollarında koyu mukus ve tekrarlayan enfeksiyon; pankreasta malabsorbsiyon; yenidoğanda mekonyum ileusu yapabilir. Tanıda ter klorür testi ve genetik analiz kullanılır.','Tekrarlayan sinopulmoner enfeksiyon + pankreatik yetmezlik + yüksek ter klorürü kistik fibrozistir.','Primer siliyer diskinezide situs inversus ve siliyer hareket bozukluğu; CF’de CFTR/klor kanalı kusuru ön plandadır.',['CFTR','Ter klorür testi','Mekonyum ileusu'], aliases=['CF'], priority='P0'),
 e('Pankreatik yetmezlik','Pediatrik gastroenteroloji / Malabsorpsiyon','Pankreas enzim salgısının yetersizliği nedeniyle yağ ve besin emiliminin bozulmasıdır.','Kistik fibroziste pankreatik kanal sekresyonları koyulaşır, ekzokrin bez hasarı gelişir ve steatore/kilo alamama görülebilir. Tedavide pankreatik enzim desteği ve beslenme düzenlemesi önemlidir.','Kistik fibroziste solunum bulgularına steatore ve büyüme geriliği eşlik edebilir.','Çölyak hastalığında mukozal villus hasarı; pankreatik yetmezlikte enzim eksikliği malabsorpsiyon yapar.',['Kistik fibrozis','Steatore','Pankreatik enzim replasmanı']),
]

# Pediatric respiratory / emergency
C += [
 e('Bronşiolit','Pediatrik pulmonoloji / Alt solunum yolu','Genellikle 2 yaş altı bebeklerde viral küçük hava yolu inflamasyonu ile hışıltı ve taşipne yapan tablodur.','RSV en sık etkenlerdendir. Tedavinin temeli destek bakım, hidrasyon, nazal aspirasyon ve oksijen gereksinimini izlemektir; rutin antibiyotik veya bronkodilatör her hastada gerekli değildir.','İnfant + viral prodrom + hışıltı/taşipne = bronşiolit; temel tedavi destek tedavisidir.','Astımda tekrarlayan atak/atopi ve bronkodilatör yanıtı daha belirgin olabilir; bronşiolit genellikle ilk viral hışıltı atağıdır.',['RSV','Nazal aspirasyon','Oksijen desteği'], aliases=['viral bronşiolit'], priority='P0'),
 e('RSV','Pediatrik enfeksiyon / Solunum virüsü','Respiratuvar sinsityal virüs, süt çocuklarında bronşiolitin en önemli viral etkenlerinden biridir.','Küçük hava yollarında inflamasyon, mukus ve ödem oluşturarak hışıltı, taşipne ve beslenme güçlüğüne neden olur. Prematüre ve kardiyopulmoner hastalığı olan bebeklerde ağır seyir riski artar.','Bronşiolit sorusunda RSV en klasik etkenlerden biridir; yönetim çoğu kez destekleyicidir.','Influenza daha sistemik ateş-myalgilerle; RSV bronşiolit bebekte hışıltı/taşipneyle öne çıkar.',['Bronşiolit','Prematürite','Oksijen desteği'], aliases=['respiratuvar sinsityal virüs']),
 e('Nazal aspirasyon','Pediatrik pulmonoloji / Destek tedavisi','Bebeklerde üst hava yolu sekresyonlarının temizlenmesi işlemidir.','Bronşiolitte burun tıkanıklığı beslenmeyi ve solunumu zorlaştırabilir. Nazal aspirasyon özellikle küçük bebekte oksijenlenme ve beslenmeyi destekleyen basit ama etkili destek basamağıdır.','Bronşiolitte spesifik antiviral değil, nazal aspirasyon-hidrasyon-oksijen gibi destek tedavisi ön plandadır.','Epiglottitte hava yolu manipülasyonundan kaçınılır; bronşiolitte nazal sekresyon temizliği destekleyicidir.',['Bronşiolit','Oksijen desteği','Beslenme güçlüğü']),
 e('Krup','Pediatrik pulmonoloji / Üst hava yolu','Genellikle viral laringotrakeit sonucu havlar tarzda öksürük ve inspiratuvar stridor yapan tablodur.','Subglottik ödem hava yolunu daraltır; hafif olguda deksametazon, istirahatte stridor veya belirgin solunum sıkıntısında nebülize adrenalin gerekir. Çocuğu ajite etmek stridoru artırabilir.','Havlar öksürük + stridor = krup; istirahat stridoru varsa nebülize adrenalin eklenir.','Epiglottitte toksik görünüm, salya akması ve tripod baskındır; krup daha viral prodrom ve havlar öksürükle gelir.',['İnspiratuvar stridor','Nebülize adrenalin','Deksametazon'], aliases=['croup','laringotrakeit'], priority='P0'),
 e('İnspiratuvar stridor','Pediatrik pulmonoloji / Üst hava yolu bulgusu','İnspirasyon sırasında üst hava yolu darlığına bağlı duyulan kaba, tiz solunum sesidir.','Ekstratorasik hava yolu daralması inspirasyonda daha belirginleşir. Krup, epiglottit, laringomalazi, yabancı cisim ve subglottik stenoz gibi nedenlerde tanısal yönlendiricidir.','Stridor üst hava yolu obstrüksiyonunu gösterir; wheezing alt hava yolu obstrüksiyonudur.','Hışıltı genellikle ekspiratuvar ve bronşiyal daralmaya bağlıdır; stridor larenks/trakea düzeyini düşündürür.',['Krup','Epiglottit','Laringomalazi'], priority='P0'),
 e('Nebülize adrenalin','Pediatrik acil / Üst hava yolu tedavisi','Krupta üst hava yolu ödemini geçici olarak azaltan inhalasyon tedavisidir.','Alfa adrenerjik vazokonstriksiyon subglottik mukozal ödemi azaltır. Etkisi hızlı ama geçici olduğu için ağır olguda gözlem ve steroid tedavisiyle birlikte düşünülür.','Krupta istirahat stridoru varsa deksametazona nebülize adrenalin eklenir.','Beta agonistler alt hava yolu bronkospazmında; nebülize adrenalin krup üst hava yolu ödeminde öne çıkar.',['Krup','İnspiratuvar stridor','Deksametazon']),
 e('Deksametazon','Pediatrik acil / Krup tedavisi','Krupta hava yolu inflamasyonunu azaltmak için kullanılan sistemik kortikosteroiddir.','Tek doz bile subglottik ödemi ve tekrar başvuru riskini azaltabilir. Krup şiddetinden bağımsız olarak sık kullanılan temel tedavidir.','Krupta steroid temel tedavidir; ağır/istirahat stridorunda nebülize adrenalin eklenir.','Antibiyotik viral krup tedavisinin rutini değildir; epiglottitte antibiyotik-hava yolu güvenliği gerekir.',['Krup','Nebülize adrenalin','Subglottik ödem']),
 e('Epiglottit','Pediatrik acil / Hava yolu acili','Epiglot ve supraglottik dokuların hızla hava yolu tıkanıklığına ilerleyebilen enfeksiyonudur.','Toksik görünüm, yüksek ateş, salya akması, yutamama, tripod pozisyonu ve istirahat stridoru alarmdır. Çocuğu yatırmak veya boğaz muayenesiyle ajite etmek hava yolunu kapatabilir; güvenli hava yolu ve IV antibiyotik önceliklidir.','Epiglottit şüphesinde boğazı kurcalama; kontrollü hava yolu yönetimi önceliklidir.','Krup havlar öksürükle; epiglottit toksik görünüm, drooling ve tripodla ayrılır.',['Tripod pozisyonu','Salya akması','Güvenli hava yolu'], priority='P0'),
 e('Tripod pozisyonu','Pediatrik acil / Hava yolu bulgusu','Çocuğun hava yolunu açık tutmak için öne eğilerek oturma pozisyonudur.','Epiglottit ve ağır üst hava yolu obstrüksiyonunda çocuk bu pozisyonda daha rahat nefes alabilir. Bu bulgu hastayı yatırmama ve ajite etmeme gerektiğini hatırlatır.','Toksik çocuk + salya + tripod epiglottit için kırmızı bayraktır.','Krupta havlar öksürük öne çıkar; tripod ve yutamama epiglottiti güçlendirir.',['Epiglottit','Salya akması','İnspiratuvar stridor']),
 e('Laringomalazi','Pediatrik pulmonoloji / Kronik stridor','Süt çocuklarında supraglottik yapıların inspirasyonda kollabe olmasıyla kronik inspiratuvar stridor yapan en sık nedendir.','Stridor genellikle beslenme, ağlama veya sırtüstü pozisyonda artar; çoğu olgu büyümeyle düzelir. Kilo alamama, apne veya ciddi solunum sıkıntısı varsa ileri değerlendirme gerekir.','İnfantta kronik inspiratuvar stridorun en sık nedeni laringomalazidir.','Krup akut viral tablo; laringomalazi kronik/pozisyonel stridordur.',['İnspiratuvar stridor','Supraglottik kollaps','Beslenme güçlüğü']),
 e('Koanal atrezi','Pediatrik KBB / Nazal obstrüksiyon','Posterior nazal açıklığın tek veya çift taraflı kapalı olmasıdır.','Yenidoğanlar zorunlu nazal solunum eğiliminde olduğundan bilateral koanal atrezi beslenirken siyanoz, ağlayınca düzelme yapabilir. Nazogastrik sonda ilerletilememesi tanısal ipucudur.','Beslenirken morarma, ağlayınca düzelme koanal atrezi için klasik ipucudur.','Laringomalazide stridor; koanal atrezi nazal hava yolu tıkanıklığıyla siyanoz yapar.',['Beslenirken siyanoz','Nazal obstrüksiyon','CHARGE sendromu']),
 e('Subglottik stenoz','Pediatrik KBB / Hava yolu darlığı','Krikoid altındaki hava yolunun daralmasıdır.','Konjenital olabilir veya uzun süreli entübasyon sonrası gelişebilir. Kronik/tekrarlayan stridor ve krup benzeri ataklarla karışabilir; entübasyon öyküsü ayırıcı tanıda değerlidir.','Uzun entübasyon öyküsü + kronik stridor subglottik stenozu düşündürür.','Krup akut viral ve geçicidir; subglottik stenoz yapısal darlıktır.',['İnspiratuvar stridor','Entübasyon öyküsü','Krup']),
 e('Yabancı cisim aspirasyonu','Pediatrik acil / Hava yolu','Ani öksürük/boğulma atağı sonrası tek taraflı hışıltı veya solunum sesi azalmasıyla giden aspirasyon tablosudur.','Çocuklarda kuruyemiş/oyuncak parçaları sık neden olabilir. Ekspiratuvar grafide hava hapsi görülebilir; tanı ve tedavide rijit bronkoskopi önemlidir.','Ani başlangıç + tek taraflı wheezing yabancı cisim aspirasyonudur; astım gibi tedavi edip geciktirme.','Astım genellikle yaygın ve tekrarlayıcıdır; yabancı cisimde ani, fokal ve tek taraflı bulgu beklenir.',['Rijit bronkoskopi','Hava hapsi','Tek taraflı hışıltı'], priority='P0'),
 e('Tek taraflı hışıltı','Pediatrik pulmonoloji / Fizik muayene','Wheezing bulgusunun bir hemitoraksta belirgin olmasıdır.','Diffüz astımdan farklı olarak lokalize obstrüksiyon düşündürür; çocukta özellikle yabancı cisim aspirasyonu akla gelir. Tanıklı boğulma öyküsü tanıyı güçlendirir.','Fokal wheezing + ani başlangıç = yabancı cisim aspirasyonu.','Astımda wheezing çoğunlukla bilateral/diffüzdür.',['Yabancı cisim aspirasyonu','Hava hapsi','Rijit bronkoskopi']),
 e('Hava hapsi','Pediatrik pulmonoloji / Görüntüleme','Obstrüksiyon nedeniyle havanın distal akciğer segmentinden çıkamamasıdır.','Yabancı cisim aspirasyonunda valf mekanizmasıyla özellikle ekspirasyon grafisinde etkilenen tarafta hiperinflasyon görülebilir. Bu bulgu fokal obstrüksiyonu destekler.','Yabancı cisimde ekspiratuvar filmde tek taraflı hava hapsi görülebilir.','Bronşiolitte hava hapsi daha diffüz olabilir; yabancı cisimde fokal/lokalize patern önemlidir.',['Yabancı cisim aspirasyonu','Tek taraflı hışıltı','Ekspirasyon grafisi']),
 e('Pediatrik astım atağı','Pediatrik pulmonoloji / Acil','Çocukta bronş hiperreaktivitesi ve hava yolu inflamasyonuna bağlı akut hışıltı, dispne ve solunum işi artışı tablosudur.','Ağır atakta konuşamama, yardımcı kas kullanımı, hipoksemi, sessiz akciğer ve PaCO2 normalleşmesi kötüleşme işaretidir. İlk tedavi oksijen, inhale kısa etkili beta agonist, ipratropium ve sistemik steroid kombinasyonudur.','Ağır astımda sessiz akciğer ve yükselen PaCO2 tükenme işaretidir.','Bronşiolit çoğu kez ilk viral hışıltı atağıdır; astımda tekrarlayan atak ve bronkodilatör yanıt daha belirgindir.',['Status asthmaticus','Sessiz akciğer','Kısa etkili beta agonist'], aliases=['çocukta astım atağı'], priority='P0'),
 e('Status asthmaticus','Pediatrik pulmonoloji / Ağır astım','Standart başlangıç bronkodilatör tedavisine yeterli yanıt vermeyen ağır astım atağıdır.','Solunum kas yorgunluğu, hiperkapni, sessiz akciğer ve bilinç değişikliği yaşamı tehdit eder. Tedavi yoğun bronkodilatör, sistemik steroid, magnezyum ve gerektiğinde yoğun bakım/ventilasyon basamaklarını içerir.','Tedaviye dirençli ağır astımda hiperkapni ve sessiz akciğer entübasyon riski taşır.','Basit hışıltı atağı tedaviye hızla yanıt verir; status asthmaticus dirençli ve progresiftir.',['Pediatrik astım atağı','Sessiz akciğer','Hiperkapni'], priority='P0'),
 e('Sessiz akciğer','Pediatrik pulmonoloji / Ağır obstrüksiyon','Ağır hava yolu obstrüksiyonunda wheezing sesinin azalması veya kaybolmasıdır.','Hava akımı çok azaldığında hışıltı duyulmayabilir; bu düzelme değil, solunum yetersizliği uyarısıdır. Ağır astım atağında hipoksemi/hiperkapniyle birlikte acil tedavi ve yakın izlem gerektirir.','Astımda wheezing kaybolması iyiye gidiş değil, hava akımının kritik azalması olabilir.','Hafif astımda belirgin wheezing duyulur; ağır tıkanmada ses azalabilir.',['Status asthmaticus','Pediatrik astım atağı','Hiperkapni'], priority='P0'),
 e('Solunum işi artışı','Pediatrik acil / Fizik muayene','Çocuğun nefes almak için normalden fazla kas gücü kullanmasıdır.','Taşipne, burun kanadı solunumu, retraksiyon, inleme ve yardımcı kas kullanımıyla anlaşılır. Pediatride vital bulgular kadar gözleme dayalı bu bulgular da solunum yetmezliği riskini belirler.','Retraksiyon ve burun kanadı solunumu çocukta solunum işinin arttığını gösterir.','Sadece hızlı solunum anksiyeteyle olabilir; retraksiyon/hipoksemi eklenirse organik solunum sıkıntısı güçlenir.',['Retraksiyon','Burun kanadı solunumu','Hipoksemi']),
 e('Yardımcı kas kullanımı','Pediatrik acil / Fizik muayene','Solunumda boyun, interkostal veya abdominal kasların belirgin kullanılmasıdır.','Çocuklarda solunum rezervi sınırlı olduğu için yardımcı kas kullanımı solunum işinin arttığını ve yorulma riskini gösterir. Astım, bronşiolit, pnömoni ve üst hava yolu obstrüksiyonunda değerlendirilir.','Yardımcı kas kullanımı pediatrik solunum sıkıntısının klinik şiddet göstergesidir.','Sadece öksürük hafif olabilir; yardımcı kas kullanımı gerçek solunum yükünü gösterir.',['Solunum işi artışı','Retraksiyon','Hipoksemi']),
]

# Gastrointestinal / nephrology / endocrine/metabolic / cardiology etc. Continue concise high-yield
C += [
 e('İnvajinasyon','Pediatrik gastroenteroloji / Cerrahi acil','Bağırsak segmentinin distal segment içine teleskopik şekilde girmesidir.','Aralıklı kolik ağrı, dizleri karna çekme, kusma ve geç dönemde currant jelly dışkı ile gelebilir. Ultrasonografide target/donut sign tanıyı destekler; perforasyon yoksa hava/kontrast enema redüksiyonu tedavi edici olabilir.','Kolik ağrı + currant jelly dışkı + target sign invajinasyondur.','Gastroenteritte ağrı daha yaygın ve sürekli olabilir; invajinasyonda aralıklı kolik ataklar tipiktir.',['Currant jelly dışkı','Target sign','Enema redüksiyonu'], priority='P0'),
 e('Currant jelly dışkı','Pediatrik gastroenteroloji / Dışkı bulgusu','Mukus ve kan içeren, kırmızı jöle görünümünde dışkı tarifidir.','İnvajinasyonda venöz konjesyon ve mukozal iskemi sonucu gelişir; genellikle geç bulgudur. Varlığı tanıyı destekler ancak yokluğu invajinasyonu dışlamaz.','Currant jelly dışkı invajinasyonun klasik ama geç bulgusudur.','Basit dizanteride enfeksiyöz ateş-ishal baskın olabilir; invajinasyonda kolik ağrı ve ataklar öne çıkar.',['İnvajinasyon','Target sign','Kolik karın ağrısı']),
 e('Target sign','Pediatrik gastroenteroloji / Ultrason bulgusu','İnvajinasyonda ultrasonda iç içe geçmiş bağırsak segmentlerinin hedef/donut görünümüdür.','Transvers kesitte konsantrik halkalar şeklinde izlenir. Çocukta aralıklı kolik ağrı ve kusmayla birlikte tanıyı hızlandırır.','İnvajinasyonda ilk görüntüleme abdominal USG; target sign yüksek verimli bulgudur.','Pilor stenozunda USG pilor kalınlığı/uzunluğunu; invajinasyonda target signı gösterir.',['İnvajinasyon','Abdominal ultrasonografi','Enema redüksiyonu'], aliases=['donut sign','hedef bulgusu']),
 e('Enema redüksiyonu','Pediatrik cerrahi / Tedavi','İnvajinasyonda hava veya kontrast lavmanla bağırsak segmentinin açılmasıdır.','Peritonit veya perforasyon bulgusu yoksa tanı ve tedavi amacıyla kullanılabilir. Başarısızlık, perforasyon veya klinik instabilite cerrahi gerektirir.','İnvajinasyonda perforasyon yoksa pnömatik/hidrostatik enema redüksiyonu tedavi edici olabilir.','Volvulusta iskemi riski nedeniyle acil cerrahi değerlendirme önceliklidir.',['İnvajinasyon','Target sign','Peritonit'], aliases=['pnömatik redüksiyon','hidrostatik redüksiyon']),
 e('Hemolitik üremik sendrom','Pediatrik nefroloji / Trombotik mikroanjiyopati','Mikroanjiyopatik hemolitik anemi, trombositopeni ve akut böbrek hasarı üçlüsüdür.','Çocuklarda tipik form sıklıkla Shiga toksinli kanlı ishal sonrası gelişir. Tedavi çoğunlukla destekleyicidir; antibiyotik ve antimotilite ilaçlar EHEC ilişkili tabloda kötüleştirme riski nedeniyle tuzak olabilir.','Kanlı ishal sonrası anemi + trombositopeni + böbrek yetmezliği HÜS’tür.','TTP’de nörolojik bulgular ve erişkin patern daha ön plandadır; tipik pediatrik HÜS ishal sonrası renal tabloyla gelir.',['Mikroanjiyopatik hemolitik anemi','Shiga toksin','Akut böbrek hasarı'], aliases=['HÜS','HUS'], priority='P0'),
 e('Shiga toksin ilişkili HÜS','Pediatrik nefroloji / Post-diyareik HÜS','EHEC veya Shigella sonrası Shiga toksininin endotel hasarıyla HÜS oluşturmasıdır.','Toksin glomerüler endoteli zedeler, trombosit tüketimi ve eritrosit parçalanması gelişir. Kanlı ishalden günler sonra oligüri ve solukluk klasik zaman çizgisidir.','Kanlı ishalden 5-10 gün sonra HÜS gelişmesi Shiga toksin ilişkisini düşündürür.','İmmün trombositopenide böbrek yetmezliği ve şistosit beklenmez.',['Hemolitik üremik sendrom','EHEC','Şistosit']),
 e('İdrar çıkışında azalma','Pediatrik nefroloji / Oligüri','Çocuğun yaş ve ağırlığına göre beklenen idrar miktarının belirgin azalmasıdır.','Dehidratasyon, şok, akut böbrek hasarı veya HÜS gibi durumlarda erken uyarı olabilir. Pediatride aile öyküsündeki bez sayısı bile perfüzyon ve renal fonksiyon için değerli ipucudur.','Bez sayısının azalması çocukta hipoperfüzyon veya akut böbrek hasarı ipucu olabilir.','Sık idrara çıkma polidipsi/DM ile; idrar azalması volüm kaybı veya renal hasarla ilişkilidir.',['Oligüri','Akut böbrek hasarı','Dehidratasyon'], aliases=['oligüri']),
 e('Minimal değişiklik hastalığı','Pediatrik nefroloji / Nefrotik sendrom','Çocukluk çağının en sık nefrotik sendrom nedeni olan podosit hastalığıdır.','Masif proteinüri, hipoalbüminemi, ödem ve hiperlipidemi yapar; ışık mikroskobisi genellikle normal, elektron mikroskopide podosit ayaksı çıkıntı silinmesi görülür. Steroide iyi yanıt tipiktir.','Çocukta nefrotik sendrom + normal kompleman + belirgin hematüri yokluğu minimal değişiklik lehinedir.','Poststreptokokal GN nefritik patern ve düşük C3 ile; minimal değişiklik nefrotik paternle gelir.',['Nefrotik sendrom','Podosit ayaksı çıkıntı silinmesi','Masif proteinüri'], priority='P0'),
 e('Masif proteinüri','Pediatrik nefroloji / Nefrotik patern','Nefrotik düzeyde yüksek protein kaybıdır.','Glomerüler filtrasyon bariyeri özellikle podosit düzeyinde bozulduğunda albumin idrara kaçar; hipoalbüminemi ve ödem gelişir. Çocukta nefrotik sendrom tanısının temel laboratuvar ayağıdır.','Ödem + masif proteinüri + hipoalbüminemi nefrotik sendrom paternidir.','Nefritik sendromda hematüri, hipertansiyon ve azotemi daha belirgindir.',['Nefrotik sendrom','Hipoalbüminemi','Ödem']),
 e('Poststreptokokal glomerülonefrit','Pediatrik nefroloji / Nefritik sendrom','Streptokok enfeksiyonu sonrası immün kompleks aracılı akut nefritik sendromdur.','Çay rengi idrar, periorbital ödem, hipertansiyon, düşük C3 ve ASO/anti-DNase B yüksekliği ile sorulabilir. Genellikle enfeksiyondan latent dönem sonra gelişir.','Çocukta çay rengi idrar + düşük C3 + streptokok öyküsü PSGN düşündürür.','IgA nefropatisinde hematüri enfeksiyonla eş zamanlı; PSGN’de latent dönem vardır.',['Düşük C3','ASO yüksekliği','Çay rengi idrar'], aliases=['PSGN','post-streptokokal GN'], priority='P0'),
 e('Çay rengi idrar','Pediatrik nefroloji / Hematüri bulgusu','Glomerüler kaynaklı hematüride idrarın koyu kahverengi/çay renginde görünmesidir.','Eritrositler glomerülden geçerken şekil değiştirir ve idrar rengi parlak kırmızıdan çok çay-kola rengine dönebilir. Poststreptokokal GN ve IgA nefropatisi gibi nefritik tabloları düşündürür.','Çay rengi idrar glomerüler hematüri ipucudur.','Alt üriner sistem kanamasında idrar daha parlak kırmızı ve pıhtılı olabilir.',['Poststreptokokal glomerülonefrit','Eritrosit silendiri','Nefritik sendrom']),
 e('IgA vasküliti','Pediatrik romatoloji / Küçük damar vasküliti','Palpabl purpura, karın ağrısı, artralji ve renal tutulumla giden IgA aracılı vaskülittir.','Döküntü genellikle alt ekstremite ve kalçada belirgindir; trombosit sayısı normaldir. Karın ağrısı invajinasyonla, renal tutulum hematüri/proteinüriyle komplike olabilir.','Palpabl purpura + karın ağrısı + normal trombosit IgA vaskülitidir.','İTP’de purpura trombositopeniye bağlıdır; IgA vaskülitinde purpura vaskülit kaynaklıdır ve trombosit normal olabilir.',['Palpabl purpura','İnvajinasyon','Hematüri'], aliases=['Henoch-Schönlein purpurası','HSP'], priority='P0'),
 e('Palpabl purpura','Pediatrik romatoloji / Döküntü bulgusu','Ciltte ele gelen mor-kırmızı purpurik döküntüdür.','Damar duvarı inflamasyonu nedeniyle eritrosit ekstravazasyonu ve ödem oluşur. Çocukta alt ekstremite-kalça yerleşimi, karın ağrısı ve artralji ile IgA vaskülitini düşündürür.','Palpabl purpura trombositopeniden çok vaskülit düşündüren bir döküntüdür.','Peteşi/purpura trombositopenide düz olabilir; palpabl olması vasküliti destekler.',['IgA vasküliti','Artralji','Karın ağrısı']),
]

# Endocrine/metabolic/immunology/neuro/cardiology/infectious
C += [
 e('Pediatrik DKA','Pediatrik endokrinoloji / Diyabet acili','Çocukta insülin eksikliğine bağlı hiperglisemi, ketozis ve yüksek anyon açıklıklı metabolik asidoz tablosudur.','Tedavide sıvı resüsitasyonu, insülin infüzyonu ve potasyum güvenliği birlikte yönetilir. Çocuklarda serebral ödem riski nedeniyle hızlı osmolar değişim ve nörolojik kötüleşme yakından izlenir.','Pediatrik DKA’da insülin başlamadan önce potasyum ve perfüzyon değerlendirilir.','HHS’de ketozis daha az belirgin, hiperosmolarite daha baskındır; pediatrik DKA’da ketozis-asidoz öne çıkar.',['Ketozis','DKA potasyum güvenliği','Serebral ödem'], aliases=['çocuk DKA','diyabetik ketoasidoz'], priority='P0'),
 e('DKA potasyum güvenliği','Pediatrik endokrinoloji / Tedavi güvenliği','DKA tedavisinde serum potasyumunun insülin öncesi ve sırasında güvenli aralıkta tutulmasıdır.','Toplam vücut potasyumu eksiktir; insülin potasyumu hücre içine sokarak hipokalemiyi ağırlaştırabilir. Bu nedenle hipokalemi varsa insülin geciktirilip potasyum replasmanı önceliklenir.','DKA’da potasyum düşükse önce potasyum ver; insülin hipokalemiyi derinleştirir.','Hiperkalemik görünen DKA’da bile toplam vücut potasyumu düşük olabilir.',['Pediatrik DKA','Hipokalemi','İnsülin infüzyonu'], priority='P0'),
 e('Serebral ödem','Pediatrik endokrinoloji / DKA komplikasyonu','Pediatrik DKA tedavisinin en korkulan nörolojik komplikasyonudur.','Baş ağrısı, bilinç değişikliği, bradikardi, hipertansiyon ve pupilla bulguları artmış intrakraniyal basıncı düşündürür. Hızlı tanı ve hipertonik tedavi nörolojik sekeli azaltmak için kritiktir.','DKA tedavisinde bilinç kötüleşmesi serebral ödem alarmıdır.','Hipoglisemi de bilinç değişikliği yapar; DKA’da nörolojik kötüleşme serebral ödem açısından değerlendirilir.',['Pediatrik DKA','Artmış intrakraniyal basınç','Hipertonik salin'], priority='P0'),
 e('Semptomatik hipoglisemi','Pediatrik endokrinoloji / Acil glukoz','Düşük glukozun nöbet, letarji, bilinç değişikliği veya adrenerjik bulgularla seyretmesidir.','Çocuklarda beyin glukoza bağımlı olduğu için semptomatik hipoglisemi hızlı düzeltilmelidir. Bilinci kapalı veya nöbet geçiren çocukta oral besleme yerine intravenöz dekstroz bolusu gerekir.','Nöbet/letarji + düşük glukoz = IV dekstroz, antiepileptik bekleme.','Febril nöbette glukoz normal olabilir; hipoglisemide nöbet metabolik acildir.',['IV dekstroz bolusu','Ketotik hipoglisemi','Hipoketotik hipoglisemi'], priority='P0'),
 e('IV dekstroz bolusu','Pediatrik acil / Hipoglisemi tedavisi','Semptomatik hipoglisemide intravenöz glukozun hızlı verilmesidir.','Amaç nöroglikopeniyi hızla düzeltmek ve nöbet/bilinç bozukluğunu sonlandırmaktır. Bilinci açık çocukta oral karbonhidrat düşünülebilir; bilinç bozukluğu varsa aspirasyon riski nedeniyle IV yol tercih edilir.','Semptomatik hipoglisemide ilk düzeltme hızlı glukoz replasmanıdır.','Antiepileptik nöbeti baskılayabilir ama altta yatan hipoglisemiyi düzeltmez.',['Semptomatik hipoglisemi','Nöroglikopeni','Hipoglisemi']),
 e('Ketotik hipoglisemi','Pediatrik endokrinoloji / Açlık hipoglisemisi','Açlık veya hastalık sonrası keton artışıyla birlikte gelişen çocukluk çağı hipoglisemisidir.','Glikojen depoları sınırlı ve oral alımı azalan küçük çocukta keton üretimi belirginleşir. Hipoketotik hipoglisemiden farkı yağ asidi oksidasyon kusurundan çok açlık adaptasyonunun ketonlu yanıtıdır.','Açlık sonrası hipoglisemi + keton varlığı ketotik hipoglisemi lehinedir.','Hipoketotik hipoglisemi yağ asidi oksidasyon kusurlarını düşündürür.',['Açlık hipoglisemisi','Ketonemi','MCAD']),
 e('Tuz kaybettiren adrenal kriz','Pediatrik endokrinoloji / Adrenal acil','Aldosteron ve kortizol eksikliğine bağlı hiponatremi, hiperkalemi, dehidratasyon ve şok tablosudur.','Yenidoğanda 21-hidroksilaz eksikliğinde kusma, kilo kaybı, hipoglisemi, hiponatremi, hiperkalemi ve kız bebekte virilizasyon görülebilir. Tedavide hidrokortizon, sıvı, glukoz ve elektrolit yönetimi acildir.','Yenidoğan + kusma/şok + hiponatremi/hiperkalemi = tuz kaybettiren KAH krizi düşün.','Pilor stenozu hipokloremik alkaloz yapar; adrenal kriz hiponatremi-hiperkalemiyle gider.',['21-hidroksilaz eksikliği','Ambigus genitalya','Hidrokortizon'], priority='P0'),
 e('Ambigus genitalya','Pediatrik endokrinoloji / Cinsel gelişim','Dış genital yapının tipik kız/erkek görünümüne net uymamasıdır.','Yenidoğanda özellikle tuz kaybettiren konjenital adrenal hiperplaziyle birlikte kusma ve şok varsa acil endokrin değerlendirme gerekir. Genital muayene tanı değil, metabolik kriz riskini fark ettiren ipucudur.','Ambigus genitalya + tuz kaybı 21-hidroksilaz eksikliğini düşündürür.','İzole hipospadias farklıdır; ambigus genitalyada cinsel gelişim bozukluğu ve adrenal kriz araştırılır.',['Tuz kaybettiren adrenal kriz','21-hidroksilaz eksikliği','Virilizasyon']),
 e('Santral puberte prekoks','Pediatrik endokrinoloji / Puberte','Hipotalamus-hipofiz-gonad aksının erken aktive olmasıyla gelişen erken pubertedir.','Kızda 8, erkekte 9 yaşından önce ilerleyici puberte bulguları, büyüme hızında artış, kemik yaşı ileriliği ve pubertal LH yanıtı beklenir. Tedavide seçilmiş olguda GnRH analoğu kullanılır.','Erken puberte + pubertal LH yanıtı santral puberte prekoks lehinedir.','Periferik pubertede LH baskılıdır ve gonadal/adrenal hormon üretimi bağımsızdır.',['Kemik yaşı ileriliği','GnRH stimülasyon testi','Prematür telarş'], priority='P0'),
 e('Prematür telarş','Pediatrik endokrinoloji / Puberte varyantı','Kız çocukta diğer puberte bulguları olmadan erken meme gelişimidir.','Genellikle izole ve ilerleyici olmayan benign bir varyanttır. Pubik kıllanma, hızlı büyüme, kemik yaşı ileriliği veya pubertal LH yanıtı varsa santral puberte prekoks düşünülür.','İzole meme gelişimi prematür telarş olabilir; ilerleme varsa puberte prekoksu dışlama.','Prematür adrenarş pubik/aksiller kıllanma ve vücut kokusuyla gider; telarş meme gelişimidir.',['Santral puberte prekoks','Kemik yaşı','GnRH stimülasyon testi']),
 e('Prematür adrenarş','Pediatrik endokrinoloji / Puberte varyantı','Adrenal androjen artışına bağlı erken pubik/aksiller kıllanma veya vücut kokusudur.','Meme gelişimi veya testis büyümesi beklenmez; büyüme hızı ve kemik yaşı sınırlı etkilenebilir. Hızlı virilizasyon varsa adrenal tümör veya KAH dışlanmalıdır.','Erken pubik kıllanma + meme/testis gelişimi yoksa prematür adrenarş düşün.','Santral puberte prekoks gonadotropin bağımlıdır ve meme/testis gelişimiyle ilerleyebilir.',['Adrenal androjen','Virilizasyon','Santral puberte prekoks']),
 e('Kemik yaşı ileriliği','Pediatrik endokrinoloji / Büyüme-puberte','Kemik maturasyonunun kronolojik yaştan ileri olmasıdır.','Erken seks steroid maruziyeti büyüme plaklarını hızlandırır; çocuk başlangıçta uzun görünebilir ama final boyu azalabilir. Puberte prekoks değerlendirmesinde kritik veridir.','Erken puberte + kemik yaşı ileriliği final boy kaybı riskini gösterir.','Konstitüsyonel gecikmede kemik yaşı geri olabilir; puberte prekoksunda genellikle ileridir.',['Santral puberte prekoks','Büyüme hızı','GnRH stimülasyon testi']),
 e('GnRH stimülasyon testi','Pediatrik endokrinoloji / Puberte testi','GnRH veya analog uyarısı sonrası LH yanıtını değerlendirerek pubertenin santral olup olmadığını gösteren testtir.','Pubertal düzeyde LH yanıtı hipotalamus-hipofiz-gonad aksının aktive olduğunu gösterir. Periferik puberte prekoksda LH genellikle baskılı kalır.','Pubertal LH yanıtı santral puberte prekoksu destekler.','Periferik pubertede seks steroidleri yüksek olabilir ama gonadotropin yanıtı baskılıdır.',['Santral puberte prekoks','LH yanıtı','Periferik puberte prekoks']),
 e('Konjenital hipotiroidi','Pediatrik endokrinoloji / Yenidoğan taraması','Doğumsal tiroid hormon eksikliğidir ve tedavi edilmezse kalıcı nörogelişimsel hasar yapabilir.','Uzamış sarılık, kabızlık, makroglossi, hipotoni ve büyük fontanel görülebilir; ancak çoğu bebek tarama ile semptom gelişmeden yakalanır. Erken levotiroksin tedavisi nörolojik prognoz için kritiktir.','Yenidoğan taramasında TSH/T4 anormalliği konjenital hipotiroidiyi erken yakalar.','Anne sütü sarılığı indirekt bilirubinle; konjenital hipotiroidi uzamış sarılık ve gelişim riskiyle ayırt edilir.',['Yenidoğan taraması','Topuk kanı','Makroglossi'], priority='P0'),
 e('Yenidoğan taraması','Pediatri / Koruyucu hekimlik','Doğum sonrası belirli hastalıkları semptom gelişmeden yakalamayı amaçlayan tarama programıdır.','Konjenital hipotiroidi ve fenilketonüri gibi tedavi edilebilir hastalıklar erken saptanırsa ağır nörogelişimsel sonuçlar önlenebilir. Tarama pozitifliği tanı değil, doğrulayıcı test gerektiren alarmdır.','Tarama testi pozitifse doğrulama yapılır; amaç geri dönüşsüz hasar olmadan tedavidir.','Tanısal test hastalığı kesinleştirir; tarama riskli bebekleri ayıklar.',['Topuk kanı','Konjenital hipotiroidi','Fenilketonüri'], aliases=['neonatal tarama']),
 e('Topuk kanı','Pediatri / Tarama örneği','Yenidoğan taramaları için topuktan alınan kuru kan damlası örneğidir.','Metabolik ve endokrin hastalıkların erken yakalanmasında kullanılır. Pozitif sonuç aileyi korkutmadan doğrulayıcı test ve hızlı yönlendirme gerektirir.','Topuk kanı tarama testidir; pozitiflik doğrulama gerektirir.','Rutin biyokimya kanı tanısal olabilir; topuk kanı popülasyon taramasıdır.',['Yenidoğan taraması','Fenilketonüri','Konjenital hipotiroidi']),
 e('Makroglossi','Pediatrik endokrinoloji / Fizik muayene','Dilin beklenenden büyük görünmesidir.','Konjenital hipotiroidi, Down sendromu ve depo hastalıklarında görülebilir. Yenidoğanda uzamış sarılık, kabızlık ve hipotoniyle birlikte hipotiroidi ipucu olabilir.','Makroglossi + uzamış sarılık + kabızlık konjenital hipotiroidiyi düşündürür.','İzole büyük dil normal varyant olabilir; sistemik bulgular eşlik ederse anlam kazanır.',['Konjenital hipotiroidi','Down sendromu','Hipotoni']),
 e('Fenilketonüri','Pediatrik metabolizma / Aminoasit metabolizması','Fenilalanin hidroksilaz eksikliği veya BH4 metabolizması bozukluğuyla fenilalanin birikmesidir.','Tedavi edilmezse ağır entelektüel yetersizlik, nöbet ve hipopigmentasyon gelişebilir. Yenidoğan taramasında erken saptanır ve fenilalanin kısıtlı diyetle nörolojik hasar önlenir.','Yenidoğan taramasında fenilalanin yüksekliği PKU için erken tedavi fırsatıdır.','Maple syrup urine disease dallı zincirli aminoasitlerle; PKU fenilalanin birikimiyle gider.',['Fenilalanin hidroksilaz','Yenidoğan taraması','Fenilalanin kısıtlı diyet'], aliases=['PKU'], priority='P0'),
 e('Fenilalanin hidroksilaz','Pediatrik metabolizma / Enzim','Fenilalanini tirozine dönüştüren enzimdir.','Enzim eksikliğinde fenilalanin ve fenilketonlar birikir; gelişmekte olan beyinde toksisite yapar. PKU patofizyolojisinin temel enzimidir.','PKU’da temel kusur fenilalanin hidroksilaz veya kofaktör BH4 yolundadır.','Tirozinemi tirozin katabolizmasıyla ilişkilidir; PKU fenilalanin dönüşüm kusurudur.',['Fenilketonüri','Tirozin','BH4']),
 e('Organik asidemi','Pediatrik metabolizma / Metabolik asidoz','Organik asitlerin birikimiyle ağır metabolik asidoz, ketozis ve hiperamonyemi yapabilen kalıtsal metabolik hastalık grubudur.','Yenidoğan veya süt çocukluğunda beslenme bozulması, kusma, letarji ve anyon açıklıklı asidozla gelebilir. Propiyonik ve metilmalonik asidemi klasik örneklerdir.','Yenidoğan + ketotik metabolik asidoz + hiperamonyemi organik asidemi düşündürür.','Üre döngüsü bozukluklarında hiperamonyemi belirgin ama asidoz/ketozis genellikle daha azdır.',['Propiyonik asidemi','Metilmalonik asidemi','Hiperamonyemi'], priority='P0'),
 e('Propiyonik asidemi','Pediatrik metabolizma / Organik asidemi','Propionil-CoA karboksilaz eksikliğine bağlı organik asidemi tablosudur.','Protein alımı veya katabolizma sonrası kusma, letarji, metabolik asidoz, ketozis ve hiperamonyemi gelişebilir. Tedavide protein kısıtlaması, karnitin ve akut dönemde katabolizmayı durdurma önemlidir.','Ketotik asidoz + hiperamonyemi organik asidemi, özellikle propiyonik/metilmalonik asidemi düşündürür.','Üre döngüsü defektinde respiratuvar alkaloz ve asidozsuz hiperamonyemi daha tipiktir.',['Organik asidemi','Propionil-CoA karboksilaz','Karnitin']),
 e('Metilmalonik asidemi','Pediatrik metabolizma / Organik asidemi','Metilmalonil-CoA metabolizması bozukluğu sonucu metilmalonik asit birikimiyle seyreden hastalıktır.','B12 ilişkili veya enzimatik kusurlar olabilir; kusma, letarji, ketotik metabolik asidoz ve hiperamonyemi görülebilir. B12 yanıtlı formlar ayırıcı tanıda önemlidir.','Metilmalonik asit artışı + ketotik asidoz metilmalonik asidemiyi düşündürür.','Propiyonik asidemi benzer kliniğe sahip olabilir; özgül organik asit profili ayrım sağlar.',['Organik asidemi','B12 metabolizması','Hiperamonyemi']),
 e('Reye sendromu','Pediatrik metabolizma / Toksik-metabolik ensefalopati','Viral enfeksiyon sonrası aspirin kullanımıyla ilişkilenen akut ensefalopati ve hepatik disfonksiyon tablosudur.','Mitokondriyal yağ asidi metabolizması bozulur; kusma, bilinç değişikliği, hipoglisemi, transaminaz yüksekliği ve hiperamonyemi görülebilir. Çocuklarda viral enfeksiyonda aspirin verilmemesinin klasik nedeni budur.','Çocukta viral hastalık + aspirin + kusma/ensefalopati Reye sendromudur.','Viral meningoensefalitte BOS bulguları öne çıkar; Reye’de karaciğer-metabolik ensefalopati paterni vardır.',['Aspirin','Hiperamonyemi','Hepatik disfonksiyon'], priority='P0'),
 e('Ağır kombine immün yetmezlik','Pediatrik immünoloji / Primer immün yetmezlik','T ve B hücre fonksiyonlarının ağır bozulduğu, erken bebeklikte hayatı tehdit eden immün yetmezliktir.','Ağır tekrarlayan enfeksiyonlar, kronik ishal, oral kandidiyazis, gelişme geriliği ve lenfopeni ile gelir. Canlı aşılar tehlikeli olabilir; kesin tedavi hematopoetik kök hücre nakli gibi yaklaşımlardır.','Erken bebeklik + kandidiyazis/kronik ishal + lenfopeni SCID düşündürür.','Bruton’da T hücre fonksiyonu korunur ve enfeksiyonlar maternal IgG kaybolduktan sonra belirginleşir.',['Lenfopeni','Canlı aşı kontrendikasyonu','Kök hücre nakli'], aliases=['SCID'], priority='P0'),
 e('Bruton agammaglobulinemisi','Pediatrik immünoloji / B hücre yetmezliği','BTK mutasyonuna bağlı B hücre olgunlaşma kusuru ve çok düşük immünoglobulin düzeyleriyle seyreden X’e bağlı hastalıktır.','Maternal IgG azaldıktan sonra tekrarlayan pyojenik sinopulmoner enfeksiyonlar başlar. Lenfoid dokular küçük olabilir; tedavide immünoglobulin replasmanı kullanılır.','6. aydan sonra tekrarlayan pyojenik enfeksiyon + düşük Ig + erkek bebek Bruton düşündürür.','SCID’de T hücre kusuru ve fırsatçı enfeksiyonlar daha erken/ağırdır.',['BTK mutasyonu','İmmünoglobulin replasmanı','Pyojenik enfeksiyon'], aliases=['X bağlı agammaglobulinemi'], priority='P0'),
 e('Wiskott-Aldrich sendromu','Pediatrik immünoloji / Kombine immün yetmezlik','Egzama, trombositopeni ve tekrarlayan enfeksiyon triadıyla giden X’e bağlı immün yetmezliktir.','WAS protein kusuru aktin iskelet düzenini ve immün sinapsı bozar. Küçük trombositler, kanama eğilimi ve enfeksiyon birlikteliği klasik TUS ipucudur.','Egzama + tekrarlayan enfeksiyon + küçük trombositli trombositopeni Wiskott-Aldrich’tir.','ITP’de trombositler genellikle büyük olabilir; Wiskott-Aldrich’te küçük trombosit ve immün yetmezlik vardır.',['Küçük trombosit','Egzama','X bağlı kalıtım'], priority='P0'),
 e('Lökosit adezyon defekti','Pediatrik immünoloji / Fagosit kusuru','Nötrofillerin damar dışına göç edememesiyle giden adezyon molekül kusurudur.','Gecikmiş göbek kordonu düşmesi, irin oluşmaması, tekrarlayan bakteriyel enfeksiyonlar ve belirgin nötrofili tipiktir. Problem nötrofil sayısı değil, dokulara geçememesidir.','Gecikmiş umblikal kord düşmesi + irin yokluğu + nötrofili LAD düşündürür.','Kronik granülomatöz hastalıkta fagositler gelir ama oksidatif öldürme bozulur.',['Nötrofili','Gecikmiş göbek kordonu düşmesi','İrin yokluğu'], aliases=['LAD'], priority='P0'),
 e('Gecikmiş göbek kordonu düşmesi','Pediatrik immünoloji / Klinik ipucu','Umblikal kordun beklenenden geç ayrılmasıdır ve lökosit adezyon defekti için klasik ipucudur.','Nötrofiller enfeksiyon alanına göç edemediği için lokal inflamasyon ve ayrılma süreci bozulabilir. İrin azlığı ve nötrofiliyle birlikte değerlendirilir.','Geç düşen göbek kordonu + irin yokluğu LAD için yüksek verimli ipucudur.','Basit geç iyileşme tek başına tanı koydurmaz; nötrofili ve enfeksiyon paterni eşlik etmelidir.',['Lökosit adezyon defekti','Nötrofili','İrin yokluğu']),
 e('Kronik granülomatöz hastalık','Pediatrik immünoloji / Fagosit öldürme kusuru','NADPH oksidaz kusuru nedeniyle fagositlerin oksidatif öldürme yapamadığı primer immün yetmezliktir.','Katalaz pozitif mikroorganizmalarla tekrarlayan apse ve enfeksiyonlar gelişir. Dihidrorodamin testi tanıda kullanılır.','Katalaz pozitif enfeksiyonlar + apse + DHR testi bozukluğu CGD düşündürür.','LAD’de nötrofil dokuya gidemez; CGD’de fagosit gelir ama öldüremez.',['NADPH oksidaz','Katalaz pozitif mikroorganizma','Dihidrorodamin testi'], aliases=['CGD'], priority='P0'),
 e('Dihidrorodamin testi','Pediatrik immünoloji / Fagosit fonksiyon testi','Nötrofillerin oksidatif patlama kapasitesini ölçen akım sitometri testidir.','Kronik granülomatöz hastalıkta NADPH oksidaz kusuru nedeniyle floresan sinyali bozulur. Nitroblue tetrazolium testinin modern karşılığı gibi düşünülebilir.','CGD tanısında DHR testi oksidatif patlamayı değerlendirir.','İmmünoglobulin düzeyi B hücre kusurunu; DHR fagosit oksidatif öldürmesini ölçer.',['Kronik granülomatöz hastalık','NADPH oksidaz','Oksidatif patlama'], aliases=['DHR testi']),
 e('Selektif IgA eksikliği','Pediatrik immünoloji / Antikor eksikliği','Serum IgA düşüklüğüyle giden en sık primer immün yetmezliklerden biridir.','Mukozal enfeksiyonlar, Giardia, alerji/otoimmünite ve anti-IgA antikorları varsa transfüzyon reaksiyonu riskiyle sorulabilir. Çoğu olgu asemptomatik de olabilir.','Tekrarlayan mukozal enfeksiyon + düşük IgA selektif IgA eksikliği düşündürür.','CVID’de birden çok immünoglobulin sınıfı düşer; selektif IgA’da temel kusur IgA’dır.',['Mukozal enfeksiyon','Giardia','Anafilaktik transfüzyon reaksiyonu']),
 e('DiGeorge sendromu','Pediatrik immünoloji / Faringeal poş anomalisi','22q11 delesyonuna bağlı timus ve paratiroid gelişim bozukluğu, konotrunkal kalp defekti ve hipokalsemiyle seyreden sendromdur.','Üçüncü-dördüncü faringeal poş gelişim kusuru T hücre immün yetmezliği ve hipokalsemiye yol açar. Yenidoğanda tetani/nöbet, konjenital kalp hastalığı ve enfeksiyon eğilimi birlikte sorulabilir.','Konotrunkal defekt + hipokalsemi + timus hipoplazisi DiGeorge’dur.','Bruton B hücre/antikor kusurudur; DiGeorge T hücre/timus gelişim kusurudur.',['22q11 delesyonu','Timus hipoplazisi','Hipokalsemi'], priority='P0'),
 e('Ataksi telenjiektazi','Pediatrik immünoloji / DNA tamir bozukluğu','ATM gen kusuruna bağlı serebellar ataksi, okülokutanöz telenjiektazi ve immün yetmezlikle giden hastalıktır.','DNA çift iplik kırığı yanıtı bozulur; sinopulmoner enfeksiyonlar, malignite riski ve AFP yüksekliği görülebilir. Radyasyon duyarlılığı önemli klinik noktadır.','Ataksi + telenjiektazi + yüksek AFP ATM kusurunu düşündürür.','Serebral palside statik motor bozukluk vardır; ataksi telenjiektazide ilerleyici nöro-immün tablo olur.',['ATM geni','AFP yüksekliği','Serebellar ataksi']),
 e('Febril nöbet','Pediatrik nöroloji / Ateşli nöbet','6 ay-5 yaş arasında ateşle ilişkili, MSS enfeksiyonu veya metabolik neden olmadan gelişen nöbettir.','Basit febril nöbet kısa, jeneralize ve 24 saatte tek nöbettir; kompleks febril nöbet uzamış, fokal veya tekrarlayıcıdır. Gereksiz lomber ponksiyon/antiepileptik tuzaklarına dikkat edilir.','Kısa, jeneralize, tek ateşli nöbet basit febril nöbettir.','Menenjitte ense sertliği, toksik görünüm ve BOS bulguları nöbetin ateşten bağımsız ciddi nedenini düşündürür.',['Basit febril nöbet','Kompleks febril nöbet','Menenjit'], priority='P0'),
 e('Basit febril nöbet','Pediatrik nöroloji / Ateşli nöbet','Kısa süreli, jeneralize, 24 saat içinde tekrarlamayan febril nöbettir.','Nöbet sonrası çocuk hızla toparlar ve nörolojik defisit beklenmez. Tedavi çoğunlukla aile eğitimi ve ateş nedeninin değerlendirilmesidir; rutin uzun süreli antiepileptik gerekmez.','Basit febril nöbet benign seyreder; uzun süreli antiepileptik rutin değildir.','Kompleks febril nöbet fokal, 15 dakikadan uzun veya 24 saatte tekrarlayan nöbettir.',['Febril nöbet','Kompleks febril nöbet','Ateş']),
 e('Kompleks febril nöbet','Pediatrik nöroloji / Ateşli nöbet','Fokal özellikli, 15 dakikadan uzun süren veya 24 saatte tekrarlayan febril nöbettir.','Basit febril nöbete göre altta yatan patoloji ve tekrar riski açısından daha dikkatli değerlendirilir. Menenjit, metabolik bozukluk veya yapısal neden bulguları özellikle aranır.','Fokal, uzun veya tekrarlayan ateşli nöbet kompleks febril nöbettir.','Basit febril nöbet kısa, jeneralize ve tek ataktır.',['Febril nöbet','Menenjit','Lomber ponksiyon']),
 e('Status epileptikus','Pediatrik nöroloji / Nöbet acili','Uzamış veya tekrarlayan nöbetlerle bilinç toparlanmasının olmadığı nörolojik acildir.','Pediatrik yaklaşım ABC, glukoz kontrolü, benzodiazepin ve devam eden nöbette ikinci basamak antiepileptiklerle ilerler. Hipoglisemi gibi düzeltilebilir nedenler aynı anda aranır.','Uzamış nöbette önce ABC + glukoz + benzodiazepin zinciri kurulur.','Basit febril nöbet kısa sürer ve kendiliğinden biter; status epileptikus acil tedavi gerektirir.',['Benzodiazepin','IV dekstroz bolusu','Hipoglisemi'], priority='P0'),
 e('Katılma nöbeti','Pediatrik nöroloji / Benign paroksismal olay','Ağlama veya korku sonrası soluk tutma, morarma/solukluk ve kısa bilinç kaybıyla giden benign çocukluk olayıdır.','Genellikle hızlı düzelir ve postiktal dönem belirgin değildir. Aile için korkutucu olsa da tipik öykü epileptik nöbetten ayırmada değerlidir.','Ağlama sonrası morarma ve hızlı düzelme katılma nöbetini düşündürür.','Epileptik nöbette tetikleyici ağlama şart değildir ve postiktal uyku/konfüzyon daha belirgin olabilir.',['Siyanotik katılma nöbeti','Postiktal dönem','Aile eğitimi']),
 e('Hipoksik iskemik ensefalopati','Neonatoloji / Perinatal nöroloji','Perinatal asfiksi sonrası beyin oksijenlenme ve perfüzyon bozukluğuna bağlı ensefalopati tablosudur.','Metabolik asidoz, düşük Apgar, nöbet, hipotoni ve bilinç etkilenimi görülebilir. Orta-ağır olgularda ilk saatlerde terapötik hipotermi nörolojik sekel riskini azaltmak için kullanılır.','Term yenidoğanda perinatal asfiksi + ensefalopati terapötik hipotermi endikasyonunu düşündürür.','Basit doğum depresyonu hızlı toparlayabilir; HİE’de nörolojik bulgular ve asidoz belirgindir.',['Terapötik hipotermi','Perinatal asfiksi','Metabolik asidoz'], aliases=['HİE','HIE'], priority='P0'),
 e('Terapötik hipotermi','Neonatoloji / Nöroproteksiyon','Orta-ağır hipoksik iskemik ensefalopatide beyin hasarını azaltmak için kontrollü soğutma tedavisidir.','Belirli zaman penceresinde uygulanır; metabolik hızı, eksitotoksisiteyi ve sekonder enerji yetmezliğini azaltmayı hedefler. Her asfiktik bebek değil, kriterleri karşılayan orta-ağır HİE olguları uygundur.','HİE’de hipotermi zaman duyarlı nöroprotektif tedavidir.','Ateş düşürme değildir; protokollü nöroprotektif soğutmadır.',['Hipoksik iskemik ensefalopati','Perinatal asfiksi','Nörolojik sekel']),
 e('Duchenne musküler distrofi','Pediatrik nöromüsküler / Kas hastalığı','Distrofin eksikliğine bağlı X’e bağlı progresif kas hastalığıdır.','Erkek çocukta proksimal güçsüzlük, Gowers bulgusu, baldır psödohipertrofisi ve CK yüksekliğiyle gelir. Kardiyomiyopati ve solunum kas etkilenimi uzun dönem izlemde önemlidir.','Erkek çocuk + Gowers + baldır psödohipertrofisi Duchenne düşündürür.','Becker daha geç ve hafif seyreder; Duchenne distrofin yokluğu/ağır eksikliğiyle daha ağırdır.',['Distrofin','Gowers bulgusu','Baldır psödohipertrofisi'], aliases=['DMD'], priority='P0'),
 e('Gowers bulgusu','Pediatrik nöromüsküler / Muayene bulgusu','Çocuğun yerden kalkarken elleriyle bacaklarına tırmanarak doğrulmasıdır.','Proksimal kas güçsüzlüğünü gösterir ve Duchenne musküler distrofi için klasik ipucudur. Kalça-kuadriseps güçsüzlüğü nedeniyle gövdeyi kaldırmak için üst ekstremiteler destek olarak kullanılır.','Gowers bulgusu proksimal kas güçsüzlüğünü gösterir.','Serebellar atakside dengesizlik baskın olabilir; Gowers kas güçsüzlüğü paternidir.',['Duchenne musküler distrofi','Proksimal kas güçsüzlüğü','Distrofin']),
 e('Baldır psödohipertrofisi','Pediatrik nöromüsküler / Muayene bulgusu','Kas lifleri yerine yağ ve bağ dokusu artışına bağlı baldırların büyük görünmesidir.','Duchenne musküler distrofide kas dejenerasyonu sonucu baldırlar güçlü değil, yalancı büyümüş görünür. Bu bulgu Gowers ile birlikte çok yüksek verimli ipucudur.','Baldır büyüklüğü güç değil, psödohipertrofi olabilir; DMD’yi düşündürür.','Atletik hipertrofi fonksiyonel güçle gider; psödohipertrofide güçsüzlük vardır.',['Duchenne musküler distrofi','Gowers bulgusu','Distrofin']),
 e('Spinal musküler atrofi tip 1','Pediatrik nöromüsküler / Motor nöron hastalığı','SMN1 gen kusuruna bağlı erken bebeklikte ağır hipotoni ve güçsüzlük yapan alt motor nöron hastalığıdır.','Dil fasikülasyonu, arefleksi, kurbağa bacağı pozisyonu ve solunum/emme güçlüğü görülebilir. Duyusal fonksiyon ve biliş genellikle korunur.','Hipotonik bebek + dil fasikülasyonu + arefleksi SMA tip 1 düşündürür.','Duchenne daha geç çocuklukta yürüyen çocukta proksimal güçsüzlükle; SMA tip 1 erken bebeklikte hipotonik tabloyla gelir.',['SMN1','Dil fasikülasyonu','Arefleksi'], aliases=['Werdnig-Hoffmann hastalığı','SMA tip 1'], priority='P0'),
 e('Dil fasikülasyonu','Pediatrik nöromüsküler / Muayene bulgusu','Dilde ince kas seğirmelerinin görülmesidir.','Alt motor nöron etkilenimini düşündürür; bebekte hipotoni ve arefleksiyle birlikte SMA tip 1 için güçlü ipucudur. Muayenede dikkatli gözlemle saptanır.','Hipotonik bebekte dil fasikülasyonu SMA lehinedir.','Santral hipotonide refleksler artabilir; SMA’da alt motor nöron bulguları vardır.',['Spinal musküler atrofi tip 1','Arefleksi','Hipotoni']),
 e('Arefleksi','Pediatrik nöromüsküler / Muayene bulgusu','Derin tendon reflekslerinin alınamamasıdır.','Alt motor nöron, periferik sinir veya kas-sinir birimi hastalıklarında görülebilir. SMA tip 1 ve Guillain-Barré gibi tablolarla birlikte yorumlanır.','Arefleksi periferik/alt motor nöron etkilenimini düşündürür.','Üst motor nöron lezyonlarında hiperrefleksi beklenir.',['Spinal musküler atrofi tip 1','Guillain-Barré sendromu','Alt motor nöron']),
 e('Retinoblastom','Pediatrik onkoloji / Göz tümörü','Retinal hücrelerden gelişen çocukluk çağı malign göz tümörüdür.','Lökokori, şaşılık ve asimetrik kırmızı refle ile saptanabilir. RB1 tümör baskılayıcı geninin iki vuruş kaybı klasik patogenezdir; bilateral/multifokal olgular germline riski düşündürür.','Fotoğrafta beyaz pupilla retinoblastom açısından acil değerlendirilmelidir.','Konjenital katarakt da lökokori yapabilir; retinoblastom malignite riski nedeniyle dışlanmalıdır.',['Lökokori','RB1','Kırmızı refle'], priority='P0'),
 e('Lökokori','Pediatrik oftalmoloji / Göz bulgusu','Pupillada normal kırmızı refle yerine beyaz refle görülmesidir.','Retinoblastom, konjenital katarakt, prematüre retinopatisi gibi nedenleri olabilir. Fotoğrafta beyaz pupilla aile tarafından fark edilebilir ve malignite dışlanana kadar önemlidir.','Lökokori retinoblastom dışlanana kadar ciddi kabul edilir.','Şaşılık tek başına benign olabilir; lökokori malign göz tümörü alarmıdır.',['Retinoblastom','Kırmızı refle','Konjenital katarakt']),
 e('Kırmızı refle','Pediatrik oftalmoloji / Tarama muayenesi','Oftalmoskopla pupilladan retinal yansımanın kırmızı-turuncu görülmesidir.','Asimetri veya beyaz refle lökokori nedenlerini düşündürür. Yenidoğan ve çocuk muayenesinde katarakt ve retinoblastom taramasında basit ama kritik bir bulgudur.','Kırmızı refle kaybı/lökokori retinoblastom ve katarakt açısından alarmdır.','Normal kırmızı refle göz içi opasite veya retinal kitle olasılığını azaltır.',['Lökokori','Retinoblastom','Konjenital katarakt']),
 e('Kawasaki hastalığı','Pediatrik kardiyoloji / Vaskülit','Uzamış ateş ve mukokutanöz bulgularla seyreden, koroner arter anevrizması riski taşıyan çocukluk çağı vaskülitidir.','En az 5 gün ateş, bilateral nonpürülan konjonktivit, oral değişiklikler, döküntü, ekstremite değişiklikleri ve servikal lenfadenopati kriterleriyle düşünülür. IVIG ve aspirin koroner komplikasyon riskini azaltmak için erken verilir.','5 günden uzun ateş + mukokutanöz bulgular Kawasaki; koroner risk için IVIG önemlidir.','Kızamıkta öksürük-koryza-Koplik ve yaygın döküntü; Kawasaki’de koroner arter riski ön plandadır.',['Koroner arter anevrizması','IVIG','Mukokutanöz bulgular'], priority='P0'),
 e('Koroner arter anevrizması','Pediatrik kardiyoloji / Kawasaki komplikasyonu','Koroner arter duvarında genişleme ve anevrizmatik değişiklik gelişmesidir.','Kawasaki hastalığında temel mortalite/morbidite nedeni olabilir. Tedavide IVIG’in hedefi inflamasyonu azaltarak bu komplikasyonu önlemektir.','Kawasaki tedavisindeki ana hedef koroner anevrizmayı önlemektir.','Basit viral döküntüler koroner anevrizma riski taşımaz.',['Kawasaki hastalığı','IVIG','Ekokardiyografi']),
 e('IVIG','Pediatrik immünoloji / Tedavi','İntravenöz immünoglobulin tedavisidir.','Kawasaki’de koroner anevrizma riskini azaltır; ITP’de kanama riski yüksek veya trombosit çok düşükse trombosit artışı sağlayabilir. Mekanizması hastalığa göre immün modülasyondur.','Kawasaki’de IVIG koroner komplikasyon önlemek için erken verilir.','Antibiyotik enfeksiyon etkenini hedefler; IVIG immün modülasyon sağlar.',['Kawasaki hastalığı','ITP','Koroner arter anevrizması'], aliases=['intravenöz immünoglobulin']),
 e('İnkomplet Kawasaki','Pediatrik kardiyoloji / Vaskülit','Kawasaki kriterlerinin tamamı olmadan koroner risk taşıyabilen Kawasaki tablosudur.','Özellikle 6 aydan küçük bebeklerde eksik mukokutanöz bulgularla gelebilir ve tanı gecikirse koroner komplikasyon riski artar. Uzamış ateş + inflamasyon belirteçleri + ekokardiyografi bulguları tanıda önemlidir.','Bebekte uzamış ateş ve yüksek inflamasyon varsa kriterler eksik olsa da Kawasaki düşün.','Viral enfeksiyonda ateş genellikle kısa sürer ve koroner risk yoktur.',['Kawasaki hastalığı','Koroner arter anevrizması','CRP yüksekliği']),
 e('Kızamık','Pediatrik enfeksiyon / Döküntülü hastalık','Ateş, öksürük, koryza, konjonktivit ve Koplik lekeleriyle seyreden viral döküntülü hastalıktır.','Döküntü yüz-saçlı deriden başlayıp gövdeye yayılabilir. Aşılanmamış çocukta yüksek bulaştırıcılık, pnömoni ve ensefalit komplikasyonları açısından önemlidir.','Öksürük-koryza-konjonktivit + Koplik lekesi kızamık için klasik paterndir.','Kızılda zımpara döküntüsü ve çilek dili streptokokla ilişkilidir; kızamık viral ve Koplik lekeli tablodur.',['Koplik lekeleri','MMR aşısı','Konjonktivit'], priority='P0'),
 e('Koplik lekeleri','Pediatrik enfeksiyon / Mukozal bulgu','Kızamıkta bukkal mukozada görülen küçük beyaz-mavimsi lezyonlardır.','Döküntüden önce ortaya çıkabilir ve kızamık için çok özgül klasik bulgudur. Aşısız çocukta ateş ve 3K bulgularıyla birlikte tanıyı güçlendirir.','Koplik lekeleri kızamık için yüksek özgüllükte ipucudur.','Kızılda ağız bulgusu çilek dilidir; Koplik kızamığa gider.',['Kızamık','MMR aşısı','Bukkal mukoza']),
 e('Kızıl','Pediatrik enfeksiyon / Streptokokal toksin hastalığı','Grup A streptokok farenjiti sonrası eritrojenik toksinle gelişen döküntülü tablodur.','Ateş, boğaz ağrısı, zımpara kağıdı döküntüsü ve çilek dili klasik ipuçlarıdır. Tedavi streptokok eradikasyonu ve akut romatizmal ateş riskini azaltma açısından önemlidir.','Boğaz ağrısı + zımpara döküntüsü + çilek dili kızılı düşündürür.','Kızamıkta öksürük-koryza-konjonktivit ve Koplik lekeleri; kızılda streptokokal farenjit bulguları vardır.',['Grup A streptokok','Çilek dili','Zımpara kağıdı döküntüsü']),
 e('Çilek dili','Pediatrik enfeksiyon / Ağız bulgusu','Dilde papillaların belirginleştiği kırmızı çilek görünümüdür.','Kızıl ve Kawasaki gibi pediatrik tablolarla ilişkili olabilir. Bağlam tanı koydurur: boğaz ağrısı-zımpara döküntüsü kızıl, uzamış ateş-mukokutanöz bulgular Kawasaki lehinedir.','Çilek dili tek başına değil, eşlik eden döküntü/ateş paterniyle yorumlanır.','Koplik lekesi kızamık için; çilek dili kızıl/Kawasaki bağlamında düşünülür.',['Kızıl','Kawasaki hastalığı','Mukokutanöz bulgular']),
 e('Zımpara kağıdı döküntüsü','Pediatrik enfeksiyon / Döküntü paterni','Ele pütürlü gelen yaygın eritemli döküntüdür.','Kızılda eritrojenik streptokok toksinine bağlı gelişir. Pastia çizgileri ve çilek dili eşlik edebilir.','Zımpara gibi döküntü + farenjit kızıl için klasik ipucudur.','Kawasaki döküntüsü polimorf olabilir ama streptokokal farenjit paterni şart değildir.',['Kızıl','Çilek dili','Grup A streptokok']),
 e('Akut romatizmal ateş','Pediatrik kardiyoloji / Poststreptokokal hastalık','Grup A streptokok farenjiti sonrası gelişen otoimmün inflamatuvar hastalıktır.','Gezici poliartrit, kardit, Sydenham kore, eritema marginatum ve subkutan nodüller Jones kriterlerinde yer alır. Asıl kalıcı risk romatizmal kalp hastalığıdır.','Strep farenjiti sonrası kardit/gezici artrit ARA düşündürür.','Poststreptokokal GN böbrek bulgularıyla; ARA kardit ve Jones kriterleriyle ayrılır.',['Jones kriterleri','Sydenham kore','Kardit'], aliases=['ARA'], priority='P0'),
 e('Jones kriterleri','Pediatrik kardiyoloji / Tanı kriteri','Akut romatizmal ateş tanısında kullanılan majör-minör klinik ve laboratuvar kriterleridir.','Streptokok enfeksiyonu kanıtıyla birlikte majör/minör kriter kombinasyonu tanı koydurur. Kardit, gezici poliartrit, Sydenham kore, eritema marginatum ve subkutan nodül majör başlıklardır.','ARA tanısında Jones kriterleri + streptokok kanıtı birlikte düşünülür.','Kawasaki’de tanı uzamış ateş ve mukokutanöz kriterlerle; ARA’da Jones kriterleriyle kurulur.',['Akut romatizmal ateş','Kardit','ASO yüksekliği']),
 e('Sydenham kore','Pediatrik nöroloji / ARA majör kriteri','Akut romatizmal ateşte görülebilen istemsiz, düzensiz koreiform hareket bozukluğudur.','Bazal ganglionlara karşı otoimmün yanıtla ilişkilidir ve streptokok enfeksiyonundan haftalar-aylar sonra ortaya çıkabilir. ARA majör kriterlerinden biridir.','Koreiform hareket + strep öyküsü Sydenham kore/ARA düşündürür.','Tik bozuklukları daha stereotipik olabilir; Sydenham kore düzensiz dans eder tarzda hareketlerle seyreder.',['Akut romatizmal ateş','Jones kriterleri','Bazal ganglion']),
 e('İmmün trombositopeni','Pediatrik hematoloji / Trombositopeni','Çocukta çoğu kez viral enfeksiyon sonrası gelişen izole trombositopeni ve mukokutanöz kanama tablosudur.','Genel durum iyi, Hb/lökosit normal ve hepatosplenomegali yoksa tipik İTP düşünülür. Atipik bulgular lösemi gibi kemik iliği hastalıklarını dışlamayı gerektirir.','Viral enfeksiyon sonrası izole trombositopeni + peteşi İTP lehinedir.','Lösemide anemi, lökosit bozukluğu, kemik ağrısı veya organomegali eşlik edebilir.',['İzole trombositopeni','Peteşi','IVIG'], aliases=['ITP','çocukluk çağı İTP'], priority='P0'),
 e('İzole trombositopeni','Pediatrik hematoloji / Laboratuvar paterni','Trombosit düşüklüğünün anemi veya lökosit bozukluğu olmadan görülmesidir.','Çocukta peteşi/ekimoz ve iyi genel durumla birlikte İTP’yi düşündürür. Diğer hücre serilerinde bozukluk veya organomegali varsa kemik iliği hastalığı düşünülmelidir.','İzole trombositopeni İTP lehine; pansitopeni lösemi/aplazi açısından alarmdır.','HÜS’te trombositopeniye hemolitik anemi ve böbrek yetmezliği eşlik eder.',['İmmün trombositopeni','Peteşi','Pansitopeni']),
 e('Hemofili A','Pediatrik hematoloji / Koagülasyon bozukluğu','Faktör VIII eksikliğine bağlı X’e bağlı kanama bozukluğudur.','Derin doku kanamaları, hemartroz ve uzamış aPTT beklenir; trombosit sayısı ve kanama zamanı genellikle normaldir. Tedavide faktör VIII replasmanı temel yaklaşımdır.','Erkek çocuk + hemartroz + uzamış aPTT Hemofili A düşündürür.','ITP mukokutanöz kanama ve düşük trombosit yapar; hemofilide trombosit normaldir.',['Faktör VIII eksikliği','Hemartroz','aPTT uzaması'], priority='P0'),
 e('Hemartroz','Pediatrik hematoloji / Kanama paterni','Eklem içine kanamadır.','Hemofili gibi koagülasyon faktör eksikliklerinde tipiktir ve tekrarlarsa eklem hasarı yapabilir. Mukokutanöz peteşiden farklı olarak derin kanama paternidir.','Hemartroz faktör eksikliği/hemofili için klasik kanama paternidir.','Trombosit bozuklukları daha çok peteşi-purpura; faktör eksiklikleri derin doku/eklem kanaması yapar.',['Hemofili A','Faktör VIII eksikliği','aPTT uzaması']),
 e('Febril nötropeni','Pediatrik onkoloji / Enfeksiyon acili','Nötropenik hastada ateş gelişmesiyle sepsis riski taşıyan acil tablodur.','Kemoterapi sonrası mukozal bariyer bozulur ve nötrofil savunması azalır. Kan kültürlerinden sonra ilk saat içinde antipseudomonal geniş spektrumlu IV antibiyotik geciktirilmez.','Kemoterapi sonrası ateş + düşük ANC = febril nötropeni; antibiyotik ilk saat içinde.','Basit viral ateşte genel durum iyi olabilir; febril nötropeni sepsis kabul edilip hızlı tedavi edilir.',['Mutlak nötrofil sayısı','Antipseudomonal antibiyotik','Kan kültürü'], priority='P0'),
 e('Mutlak nötrofil sayısı','Pediatrik hematoloji / Laboratuvar','Toplam lökosit içinde dolaşımdaki nötrofil sayısını gösteren hesaplanmış değerdir.','Febril nötropeni riskini belirlemede kullanılır; sayı düştükçe bakteriyel/fungal enfeksiyon riski artar. Kemoterapi alan çocukta ateş değerlendirmesinin temel parametresidir.','Ateşli kemoterapi hastasında ANC febril nötropeni kararını belirler.','Toplam lökosit normal olsa bile nötrofil alt grubu düşük olabilir.',['Febril nötropeni','Nötropeni','Antipseudomonal antibiyotik'], aliases=['ANC']),
 e('Antipseudomonal antibiyotik','Pediatrik enfeksiyon / Febril nötropeni tedavisi','Pseudomonas aeruginosa dahil gram negatifleri kapsayan antibiyotik yaklaşımıdır.','Febril nötropenide erken ölüm riski gram negatif sepsisle ilişkili olduğundan ilk saat içinde antipseudomonal beta-laktam başlanır. Klinik instabilite ve direnç riski tedavi genişliğini belirler.','Febril nötropenide ilk ampirik tedavi Pseudomonas kapsamalıdır.','Basit ÜSYE’de dar tedavi yeterli olabilir; nötropenide geniş gram negatif kapsama gerekir.',['Febril nötropeni','Pseudomonas aeruginosa','Kan kültürü']),
 e('Duktus bağımlı konjenital kalp hastalığı','Pediatrik kardiyoloji / Yenidoğan kardiyak acil','Sistemik veya pulmoner kan akımının açık duktus arteriozusa bağlı olduğu doğumsal kalp hastalıklarıdır.','Duktus kapanınca şok, siyanoz, metabolik asidoz veya nabız farkı gelişebilir. Prostaglandin E1 duktusu açık tutarak cerrahi/girişimsel düzeltmeye kadar zaman kazandırır.','Yenidoğanda dirençli siyanoz/şok + duktal bağımlı lezyon şüphesinde PGE1 ver.','Akciğer hastalığında oksijenle düzelme olabilir; duktal lezyonda hiperoksi yanıtı zayıf kalabilir.',['Prostaglandin E1','Preduktal-postduktal satürasyon farkı','Hiperoksi testi'], priority='P0'),
 e('Prostaglandin E1','Pediatrik kardiyoloji / Duktal açıklık tedavisi','Duktus arteriozusu açık tutmak için kullanılan prostaglandin tedavisidir.','Duktus bağımlı kalp hastalıklarında sistemik veya pulmoner kan akımını geçici olarak sürdürür. Apne önemli yan etkidir; yenidoğan yoğun bakım koşullarında verilir.','Duktus bağımlı lezyonda PGE1 hayat kurtarıcı köprü tedavidir.','PDA kapatmak için indometazin/ibuprofen; duktusu açık tutmak için PGE1 kullanılır.',['Duktus bağımlı konjenital kalp hastalığı','Apne','PDA'], aliases=['PGE1','alprostadil'], priority='P0'),
 e('Preduktal-postduktal satürasyon farkı','Pediatrik kardiyoloji / Yenidoğan değerlendirme','Sağ el ile alt ekstremite oksijen satürasyonları arasındaki farktır.','Duktus arteriozus düzeyinde sağ-sol şant veya pulmoner hipertansiyon/duktal bağımlı lezyonlarda fark gelişebilir. Yenidoğan siyanozunda kardiyak-pulmoner ayrım için kullanılır.','Sağ el satürasyonu preduktal, ayak satürasyonu postduktal bilgidir.','Diffüz akciğer hastalığında fark daha az olabilir; duktal düzeyde şantta belirginleşebilir.',['Duktus bağımlı konjenital kalp hastalığı','Hiperoksi testi','Santral siyanoz'], aliases=['pre/postduktal satürasyon farkı']),
 e('Hiperoksi testi','Pediatrik kardiyoloji / Siyanoz ayrımı','Yenidoğan siyanozunda yüksek oksijen verilince PaO2 yanıtını değerlendirerek pulmoner-kardiyak ayrım yapmaya yardım eden testtir.','Akciğer hastalığında oksijen yanıtı daha iyi olabilir; siyanotik konjenital kalp hastalığında sağ-sol şant nedeniyle yanıt sınırlı kalır. Modern pratikte ekokardiyografi önceliklidir ama sınav jargonu önemlidir.','Oksijene dirençli siyanoz siyanotik KKH veya pulmoner hipertansiyon düşündürür.','Methemoglobinemide pulse oksimetre ve kan rengi farklı ipuçları verebilir; hiperoksi testi şant mantığına odaklanır.',['Duktus bağımlı konjenital kalp hastalığı','Santral siyanoz','Ekokardiyografi']),
 e('Fallot tetralojisi','Pediatrik kardiyoloji / Siyanotik KKH','VSD, pulmoner stenoz, sağ ventrikül hipertrofisi ve overriding aorta bileşenlerinden oluşan siyanotik kalp hastalığıdır.','Pulmoner çıkış darlığı sağ-sol şantı artırarak siyanoz yapar. Hipoksik spell sırasında çömelme sistemik vasküler direnci artırıp sağ-sol şantı azaltabilir.','Siyanotik çocuk + çömelme davranışı Fallot tetralojisini düşündürür.','VSD tek başına asiyanotik soldan sağa şant yapabilir; Fallot’ta pulmoner stenoz ve sağ-sol şant siyanoz oluşturur.',['Hipoksik spell','Çömelme davranışı','VSD'], aliases=['TOF'], priority='P0'),
 e('Hipoksik spell','Pediatrik kardiyoloji / Siyanotik atak','Fallot tetralojisinde ani siyanoz ve hiperpne ataklarıdır.','Sağ ventrikül çıkış yolu darlığı artınca sağ-sol şant artar ve oksijenlenme bozulur. Diz-göğüs pozisyonu, oksijen, morfin ve beta bloker gibi basamaklar bağlama göre kullanılır.','Fallot’ta ani siyanoz atağı hipoksik spell olarak sorulur.','Basit nefes tutma atağı genellikle ağlama sonrası benign; hipoksik spell yapısal kalp hastalığı zeminindedir.',['Fallot tetralojisi','Çömelme davranışı','Sağ-sol şant']),
 e('Çömelme davranışı','Pediatrik kardiyoloji / Klinik kompansasyon','Siyanotik çocukta çömelerek sistemik vasküler direnci artırma davranışıdır.','Fallot tetralojisinde SVR artışı sağ-sol şantı azaltır ve pulmoner akımı görece artırarak siyanozu hafifletebilir. Bu davranış tanısal ipucu olarak değerlidir.','Çömelme siyanozu azaltıyorsa Fallot tetralojisi düşün.','Egzersiz sonrası dinlenmek nonspesifiktir; tekrarlayan çömelme davranışı şant fizyolojisini düşündürür.',['Fallot tetralojisi','Hipoksik spell','Sistemik vasküler direnç']),
 e('Sabit çift S2','Pediatrik kardiyoloji / Oskültasyon','Solunumla değişmeyen geniş çift ikinci kalp sesidir.','ASD’de sağ kalbe sürekli hacim yükü pulmoner kapak kapanmasını geciktirir ve S2 sabit çift duyulur. Çocukta üfürümden çok sabit çift S2 tanısal olabilir.','Sabit çift S2 ASD için klasik oskültasyon bulgusudur.','Fizyolojik çiftleşme inspiryumda artar; ASD’de sabit kalır.',['ASD','Sağ kalp hacim yükü','Pulmoner akım']),
 e('Makine üfürümü','Pediatrik kardiyoloji / Oskültasyon','Sistol-diyastol boyunca devam eden sürekli üfürüm tarifidir.','Patent duktus arteriozusta aorttan pulmoner artere sürekli akım bu üfürümü oluşturur. Prematüre bebekte PDA tedavi kararı hemodinamik etkiye göre verilir.','Sürekli makine üfürümü PDA için klasik ipucudur.','VSD holosistolik üfürüm yapar; PDA sürekli üfürümle ayrılır.',['PDA','İndometazin','Prematürite']),
 e('PDA kapatma tedavisi','Pediatrik kardiyoloji / Duktus yönetimi','Patent duktus arteriozusun farmakolojik veya girişimsel olarak kapatılmasıdır.','Prematürelerde prostaglandin sentezini azaltan indometazin veya ibuprofen duktus kapanmasını destekleyebilir. Duktus bağımlı lezyonlarda ise tam tersi PGE1 ile açık tutulur.','PDA kapatmak için indometazin/ibuprofen; duktus bağımlı lezyonda PGE1 verilir.','PDA tedavisi hemodinamik etkiye bağlıdır; her üfürüm acil kapatma gerektirmez.',['PDA','İndometazin','Prostaglandin E1']),
 e('SVT','Pediatrik kardiyoloji / Taşiaritmi','Çocukta çoğu kez ani başlayan düzenli dar QRS taşikardisidir.','Sinüs taşikardisinden farkı başlangıç-bitişin ani olması ve hızın klinik durumla orantısız olabilmesidir. Stabil çocukta vagal manevra, başarısızsa hızlı IV adenozin kullanılır.','Ani başlayan düzenli dar QRS taşikardi SVT’dir; stabilse vagal manevra/adenozin.','Sinüs taşikardisi ateş/dehidratasyonla uyumludur ve başlangıcı daha kademelidir.',['Dar QRS taşikardi','Adenozin hızlı IV puşe','Vagal manevra'], aliases=['supraventriküler taşikardi'], priority='P0'),
 e('Adenozin hızlı IV puşe','Pediatrik kardiyoloji / SVT tedavisi','SVT tedavisinde adenozinin hızlı damar içi bolus ve flush ile verilmesidir.','Adenozin çok kısa yarı ömürlüdür; AV nodu geçici bloke ederek re-entry taşikardiyi sonlandırabilir. Yavaş verilirse etkisiz kalabilir.','Adenozin SVT’de hızlı IV puşe + flush şeklinde verilmelidir.','Hemodinamik instabil taşikardide senkronize kardiyoversiyon önceliklidir.',['SVT','AV nod blokajı','Dar QRS taşikardi']),
 e('Senkronize kardiyoversiyon','Pediatrik acil / Aritmi tedavisi','Hemodinamik instabil taşikardide elektrik şokunun QRS ile senkronize verilmesidir.','Senkronizasyon repolarizasyon dönemine denk gelen şok riskini azaltır. Pediatrik taşikardi algoritmasında hipotansiyon, bilinç bozukluğu veya şok bulgusu varsa ilaç beklenmez.','İnstabil taşikardide senkronize kardiyoversiyon ilaçtan önce gelir.','Defibrilasyon nabızsız VT/VF için senkronize edilmeden verilir; kardiyoversiyon nabızlı instabil taşikardi içindir.',['SVT','Geniş QRS taşikardi','Hemodinamik instabilite'], priority='P0'),
 e('Pediatrik septik şok','Pediatrik acil / Şok','Enfeksiyona bağlı dolaşım yetmezliği ve doku hipoperfüzyonu tablosudur.','Çocuklarda hipotansiyon geç bulgu olabilir; taşikardi, kapiller dolum uzaması, soğuk/sıcak ekstremite, oligüri ve laktat yüksekliği erken uyarıdır. İlk saat sıvı, kültür, antibiyotik ve vazopressör kararlarını içerir.','Çocukta hipotansiyon beklemeden hipoperfüzyon bulgularıyla septik şok tedavisine başla.','Dehidratasyonda enfeksiyon odağı olmayabilir; septik şokta sistemik inflamasyon ve laktat/perfüzyon bozukluğu vardır.',['Kapiller dolum süresi','Laktat yüksekliği','İlk saat antibiyotik'], priority='P0'),
 e('Kapiller dolum süresi','Pediatrik acil / Perfüzyon bulgusu','Cilde bası sonrası rengin geri dönme süresidir ve periferik perfüzyonu değerlendirir.','Uzaması şok, dehidratasyon veya soğuk çevreyle ilişkili olabilir. Pediatride kan basıncı geç bozulduğu için kapiller dolum erken dolaşım ipucu sağlar.','Kapiller dolum uzaması çocukta hipoperfüzyon uyarısıdır.','Tek başına tanı koydurmaz; nabız, bilinç, idrar ve ekstremite ısısıyla birlikte yorumlanır.',['Pediatrik septik şok','Dehidratasyon','Şok indeksi']),
 e('Oral rehidratasyon tedavisi','Pediatrik gastroenteroloji / Sıvı tedavisi','Hafif-orta dehidratasyonda oral rehidratasyon solüsyonuyla sıvı-elektrolit yerine koyma tedavisidir.','Sodyum-glukoz kotransportu sayesinde barsaktan su emilimi sürer. Şok, bilinç bozukluğu, persistan kusma veya ileus varsa IV tedavi gerekir.','Hafif-orta dehidratasyonda ORS çoğu çocukta IV sıvıdan önce gelir.','Ağır dehidratasyon/şokta oral yol yeterli değildir; IV resüsitasyon gerekir.',['Dehidratasyon','ORS','Sodyum-glukoz kotransportu'], aliases=['ORS','oral rehidratasyon solüsyonu']),
 e('Ağır dehidratasyon','Pediatrik acil / Sıvı kaybı','Dolaşım bozukluğu, letarji, belirgin kapiller dolum uzaması veya zayıf nabızla seyreden ciddi sıvı kaybıdır.','Çocukta rezerv sınırlı olduğu için hızlı hipovolemik şoka ilerleyebilir. Oral tedavi yerine izotonik IV sıvı bolusu önceliklidir.','Ağır dehidratasyon ve şokta ORS değil IV izotonik sıvı gerekir.','Hafif dehidratasyonda çocuk uyanık ve perfüzyon iyidir; ağır tabloda dolaşım etkilenir.',['Kapiller dolum süresi','Oral rehidratasyon tedavisi','Hipovolemik şok'], priority='P0'),
 e('Demir toksisitesi','Pediatrik toksikoloji / Zehirlenme','Aşırı demir alımına bağlı gastrointestinal irritasyon, şok, metabolik asidoz ve çoklu organ hasarı yapabilen zehirlenmedir.','Çocukta tekrarlayan kusma, kanlı ishal, letarji, anyon açıklıklı metabolik asidoz ve yüksek serum demiri ciddi zehirlenmeyi düşündürür. Spesifik antidot deferoksamindir.','Demir toksisitesinde ciddi asidoz/şok varsa deferoksamin düşünülür.','Basit gastroenteritte toksik doz öyküsü ve yüksek serum demiri yoktur.',['Deferoksamin','Anyon açıklıklı metabolik asidoz','Serum demiri'], priority='P0'),
 e('Deferoksamin','Pediatrik toksikoloji / Antidot','Demir toksisitesinde kullanılan demir şelatör antidottur.','Serbest demiri bağlayarak idrarla atılmasını sağlar; ciddi zehirlenmede hipotansiyon, asidoz veya yüksek demir düzeyi varsa kullanılır. Kırmızımsı idrar klasik bilgi olabilir.','Ağır demir zehirlenmesinin antidotu deferoksamindir.','Aktif kömür demiri iyi bağlamaz; demir toksisitesinde antidot mantığı farklıdır.',['Demir toksisitesi','Şelasyon','Metabolik asidoz']),
 e('Isı çarpması','Pediatrik acil / Hipertermi','Çekirdek ısı yüksekliği ve santral sinir sistemi disfonksiyonuyla seyreden hayatı tehdit eden hipertermi tablosudur.','Egzersiz veya sıcak ortam sonrası bilinç değişikliği, konfüzyon, nöbet ve rabdomiyoliz gelişebilir. Tedavide hızlı soğutma zaman kritiktir; antipiretikler patofizyolojiyi düzeltmez.','Hipertermi + bilinç değişikliği = ısı çarpması; hızlı soğutma gerekir.','Ateşte hipotalamik set-point artar; ısı çarpmasında ısı yükü ve termoregülasyon yetmezliği vardır.',['Rabdomiyoliz','Hızlı soğutma','Çekirdek ısı'], priority='P0'),
 e('Ko-oksimetri','Pediatrik toksikoloji / CO tanısı','Karboksihemoglobin gibi dishemoglobinleri ölçebilen özel oksimetri yöntemidir.','Karbon monoksit zehirlenmesinde standart pulse oksimetre yanlış normal gösterebilir; çünkü oksihemoglobin ve karboksihemoglobini ayırt edemez. Ko-oksimetri tanısal doğrulama sağlar.','CO zehirlenmesinde normal SpO2 yanıltıcıdır; ko-oksimetri gerekir.','Arter kan gazı PaO2 normal olabilir; sorun hemoglobinin oksijen taşıyamamasıdır.',['Karbonmonoksit zehirlenmesi','Karboksihemoglobin','Pulse oksimetre yanılsaması']),
 e('Karboksihemoglobin','Pediatrik toksikoloji / Dishemoglobin','Karbon monoksitin hemoglobine bağlanmasıyla oluşan formdur.','CO oksijen bağlanmasını engeller ve oksijen ayrılmasını da zorlaştırır; doku hipoksisi gelişir. Baş ağrısı, bulantı, bilinç değişikliği ve aynı ortamda birden çok kişide yakınma önemli ipucudur.','CO zehirlenmesinde karboksihemoglobin artar, pulse oksimetre yanıltıcı olabilir.','Methemoglobinemide demir Fe3+ formuna oksitlenir; CO zehirlenmesinde CO-Hb oluşur.',['Karbonmonoksit zehirlenmesi','Ko-oksimetri','Doku hipoksisi']),
 e('Hiperbarik oksijen','Pediatrik toksikoloji / CO tedavisi','Seçilmiş ağır karbon monoksit zehirlenmelerinde yüksek basınç altında oksijen verilmesidir.','CO’nun hemoglobinden ayrılmasını hızlandırır ve doku oksijenlenmesini artırır. Bilinç kaybı, ciddi nörolojik bulgu, kardiyak iskemi veya gebelik gibi durumlarda gündeme gelir.','Ağır CO zehirlenmesinde hiperbarik oksijen düşünülür.','Tüm baş ağrılı olgularda gerekmez; ağırlık kriterleri ve klinik risk belirleyicidir.',['Karbonmonoksit zehirlenmesi','Karboksihemoglobin','Ko-oksimetri']),
]

# Filter, enrich, write
seen = set()
entries=[]
skipped=[]
for c in C:
    key = norm(c['term'])
    al_norms = {norm(a) for a in c.get('aliases', [])}
    if not key or key in seen: continue
    seen.add(key)
    if key in active_norms or any(a in active_norms for a in al_norms if a):
        skipped.append({**c, 'skipReason': 'alreadyActiveGlossary'})
        continue
    occ = count_occ(c['term'], c.get('aliases'))
    ex = examples(c['term'], c.get('aliases'), 2)
    # Include if directly observed or high-value pediatric concept from scanned topics/related context.
    if occ == 0:
        skipped.append({**c, 'skipReason': 'noDirectOccurrenceInPediatricsScan'})
        continue
    aliases = []
    for a in [c['term']] + c.get('aliases', []):
        if a and a not in aliases:
            aliases.append(a)
    entry = {
        'id': f"v404-pediatrics-{slug(c['term'])}",
        'term': c['term'],
        'aliases': aliases,
        'normalizedTerm': norm(c['term']),
        'TurkishName': c['term'],
        'EnglishName': '',
        'category': 'Çocuk Sağlığı ve Hastalıkları',
        'subcategory': c['subcategory'],
        'sourceLayer': 'V404 pediatrics-focused glossary expansion',
        'previewDefinition': c['short'],
        'preAnswerSafeDefinition': c['short'],
        'shortDefinition': c['short'],
        'definition': c['short'],
        'detailedExplanation': c['detail'],
        'postAnswerExplanation': c['detail'],
        'postAnswerExpandedExplanation': c['detail'],
        'tusPearl': c['pearl'],
        'examPearl': c['pearl'],
        'differentialPoint': c['diff'],
        'clinicalRelevance': c['detail'],
        'safeNestedTerms': c.get('nested', []),
        'relatedTerms': c.get('nested', []),
        'relatedBranches': ['pediatrics'],
        'sourceArea': 'Çocuk Sağlığı ve Hastalıkları',
        'sourceFilePath': 'src/data/cases.js; src/data/tusPearlCards.js; src/data/tusPearlPediatricsFirst63Overrides.js; src/data/tusPearlPediatricsSecond63Overrides.js',
        'sourceFiles': ['src/data/cases.js','src/data/tusPearlCards.js','src/data/tusPearlPediatricsFirst63Overrides.js','src/data/tusPearlPediatricsSecond63Overrides.js'],
        'occurrenceCount': occ,
        'sourceTextExamples': ex,
        'matchingPriority': 96 if c['priority']=='P0' else 88 if c['priority']=='P1' else 72,
        'standaloneSafe': True,
        'phraseOnly': c.get('phraseOnly', True),
        'caseSensitiveDisplay': False,
        'answerLeakRisk': c.get('answerLeakRisk','low'),
        'ambiguityRisk': c.get('ambiguityRisk','low'),
        'priority': c['priority'],
        'recommendation': 'addNewEntry',
        'existingGlossaryStatus': 'missingActiveGlossary',
        'reasonForRecommendation': 'Çocuk sağlığı ve hastalıkları olguları/hap kartlarında yaşa özgü tanı, acil tedavi sırası, neonatal risk, immün yetmezlik, metabolik hastalık veya pediatrik sınav jargonu açısından öğretici ve soru çözdürücü olduğu için eklendi.',
        'notes': 'Açıklamalar pediatri, neonatoloji, çocuk acil, çocuk endokrinoloji-metabolizma, immünoloji, kardiyoloji, nefroloji ve enfeksiyon kaynaklarıyla doğrulanmıştır; kullanıcı isteğine uygun olarak glossary metinlerine referans eklenmemiştir.'
    }
    entries.append(entry)

entries.sort(key=lambda x: ({'P0':0,'P1':1,'P2':2}.get(x['priority'],9), x['subcategory'], x['term']))

js_path = ROOT/'src/data/tusGlossaryV404PediatricsExpansionIndex.js'
js = "// V404 — Pediatrics-focused glossary expansion.\n// Generated after scanning Çocuk Sağlığı ve Hastalıkları cases, TUS Pearl cards and pediatric Hap card overrides.\n// Definitions are educational and reference-free in UI text.\n\n"
js += "export const TUS_GLOSSARY_V404_PEDIATRICS_EXPANSION_TERMS = " + json.dumps(entries, ensure_ascii=False, indent=2) + ";\n"
js_path.write_text(js, encoding='utf-8')

# update utils imports/spread
utils = ROOT/'src/utils/glossary.js'
text = utils.read_text(encoding='utf-8')
import_line = "import { TUS_GLOSSARY_V404_PEDIATRICS_EXPANSION_TERMS } from '../data/tusGlossaryV404PediatricsExpansionIndex.js';\n"
if import_line not in text:
    anchor = "import { TUS_GLOSSARY_V403_INTERNAL_MEDICINE_EXPANSION_TERMS } from '../data/tusGlossaryV403InternalMedicineExpansionIndex.js';\n"
    text = text.replace(anchor, anchor + import_line)
spread_line = "  ...TUS_GLOSSARY_V404_PEDIATRICS_EXPANSION_TERMS,\n"
if spread_line not in text:
    anchor = "  ...TUS_GLOSSARY_V403_INTERNAL_MEDICINE_EXPANSION_TERMS,\n"
    text = text.replace(anchor, anchor + spread_line)
utils.write_text(text, encoding='utf-8')

# reports
summary = {
    'version': 'V404',
    'branch': 'Çocuk Sağlığı ve Hastalıkları',
    'sourceCounts': payload['counts'],
    'activeGlossaryExactTermAliasCount': len(active_norms),
    'curatedCandidateBankCount': len(C),
    'addedEntryCount': len(entries),
    'skippedCount': len(skipped),
    'skippedAlreadyActive': sum(1 for s in skipped if s['skipReason']=='alreadyActiveGlossary'),
    'skippedNoDirectOccurrence': sum(1 for s in skipped if s['skipReason']=='noDirectOccurrenceInPediatricsScan'),
    'priorityDistribution': {p: sum(1 for e in entries if e['priority']==p) for p in ['P0','P1','P2']},
    'sourceInventory': source_inventory,
    'addedTerms': [e['term'] for e in entries]
}
(REPORT/'pediatrics-glossary-additions-v404.json').write_text(json.dumps(entries, ensure_ascii=False, indent=2), encoding='utf-8')
(REPORT/'pediatrics-glossary-skipped-v404.json').write_text(json.dumps(skipped, ensure_ascii=False, indent=2), encoding='utf-8')
(REPORT/'pediatrics-glossary-scan-sources-v404.json').write_text(json.dumps(source_inventory, ensure_ascii=False, indent=2), encoding='utf-8')
(REPORT/'pediatrics-glossary-additions-v404-summary.json').write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding='utf-8')

csv_path = REPORT/'pediatrics-glossary-additions-v404.csv'
with open(csv_path, 'w', encoding='utf-8-sig', newline='') as f:
    fields = ['id','term','aliases','category','subcategory','priority','shortDefinition','postAnswerExplanation','tusPearl','differentialPoint','safeNestedTerms','occurrenceCount','sourceTextExamples','answerLeakRisk','ambiguityRisk']
    w = csv.DictWriter(f, fieldnames=fields)
    w.writeheader()
    for e0 in entries:
        row = {k: e0.get(k,'') for k in fields}
        row['aliases'] = '; '.join(e0.get('aliases',[]))
        row['safeNestedTerms'] = '; '.join(e0.get('safeNestedTerms',[]))
        row['sourceTextExamples'] = ' || '.join(x.get('text','') for x in e0.get('sourceTextExamples',[]))
        w.writerow(row)

md = []
md.append('# KlinikIQ V404 Pediatrics Glossary Expansion Summary')
md.append('')
md.append('Bu paket yalnızca Çocuk Sağlığı ve Hastalıkları ile ilişkili klinik olgular, TUS Pearl kartları ve pediatri hap kart override metinleri üzerinden hazırlanmıştır. Açıklamalar kaynak kontrollüdür; glossary UI metinlerine referans eklenmemiştir.')
md.append('')
md.append('## Özet')
for k,v in summary.items():
    if k not in ('sourceInventory','addedTerms','priorityDistribution'):
        md.append(f'- **{k}:** {v}')
md.append(f"- **priorityDistribution:** {summary['priorityDistribution']}")
md.append('')
md.append('## Kaynak envanteri')
for src in source_inventory:
    md.append(f"- `{src['sourceFilePath']}` — {src['recordCount']} kayıt, {src['textFieldCount']} metin alanı")
md.append('')
md.append('## Eklenen terimler')
for e0 in entries:
    md.append(f"- **{e0['term']}** ({e0['priority']}, {e0['subcategory']}): {e0['shortDefinition']}")
(REPORT/'pediatrics-glossary-additions-v404-summary.md').write_text('\n'.join(md), encoding='utf-8')

print(json.dumps(summary, ensure_ascii=False, indent=2))
