import { cases } from './src/data/cases.js';
import { tusPearlCards } from './src/data/tusPearlCards.js';
import { TUS_PEARL_INTERNAL_MEDICINE_FIRST_50_OVERRIDES } from './src/data/tusPearlInternalMedicineFirst50Overrides.js';
import { TUS_PEARL_INTERNAL_MEDICINE_SECOND_50_OVERRIDES } from './src/data/tusPearlInternalMedicineSecond50Overrides.js';
import { TUS_PEARL_INTERNAL_MEDICINE_THIRD_59_OVERRIDES } from './src/data/tusPearlInternalMedicineThird59Overrides.js';
console.log('cases export', Array.isArray(cases), cases.length);
const ic = cases.filter(c => c.branch === 'internal-medicine' || c.relatedBranch === 'internal-medicine' || c.branchId === 'internal-medicine' || c.relatedBranches?.includes?.('internal-medicine') || c.category === 'İç Hastalıkları');
console.log('internal cases', ic.length);
for (const c of ic.slice(0,10)) console.log(c.id,c.title,c.branch,c.relatedBranch,c.relatedBranches,c.category);
console.log('tusPearlCards', Array.isArray(tusPearlCards), tusPearlCards.length);
const imCards = tusPearlCards.filter(c => c.branch === 'internal-medicine' || c.relatedBranch === 'internal-medicine' || c.branchId === 'internal-medicine' || c.relatedBranches?.includes?.('internal-medicine') || c.category === 'İç Hastalıkları' || c.section === 'İç Hastalıkları');
console.log('im pearls', imCards.length);
for (const c of imCards.slice(0,10)) console.log(c.id,c.front||c.question||c.title,c.section,c.branch,c.category);
console.log('overrides', TUS_PEARL_INTERNAL_MEDICINE_FIRST_50_OVERRIDES.length,TUS_PEARL_INTERNAL_MEDICINE_SECOND_50_OVERRIDES.length,TUS_PEARL_INTERNAL_MEDICINE_THIRD_59_OVERRIDES.length);
console.log('override sample', JSON.stringify(TUS_PEARL_INTERNAL_MEDICINE_FIRST_50_OVERRIDES[0],null,2).slice(0,1000));
