import json, re, csv, zipfile, shutil, os, textwrap, unicodedata
from pathlib import Path
ROOT=Path('/mnt/data/path_work/klinik_v395_work')
REPORT=ROOT/'reports/pathology_glossary_expansion'
active=set(json.loads((REPORT/'_active_norms.json').read_text(encoding='utf-8')))
fields=json.loads((REPORT/'_pathology_fields.json').read_text(encoding='utf-8'))

def fold_tr(s):
    s=str(s)
    trans=str.maketrans({'İ':'i','I':'ı','ı':'i','ğ':'g','ü':'u','ş':'s','ö':'o','ç':'c','Ğ':'g','Ü':'u','Ş':'s','Ö':'o','Ç':'c'})
    s=s.translate(trans).lower()
    s=''.join(c for c in unicodedata.normalize('NFD',s) if unicodedata.category(c)!='Mn')
    s=re.sub(r'[^\w+/.-]+',' ',s,flags=re.U)
    return re.sub(r'\s+',' ',s).strip()

def slug(s):
    x=fold_tr(s)
    x=re.sub(r'[^a-z0-9]+','-',x).strip('-')
    return x[:72]

def find_examples(term, aliases):
    al=[term]+aliases
    norms=[fold_tr(a) for a in al if a]
    out=[]; count=0
    for f in fields:
        nt=fold_tr(f['text'])
        if any(n and n in nt for n in norms):
            count+=1
            if len(out)<2:
                txt=f['text'].strip().replace('\n',' ')
                if len(txt)>260: txt=txt[:257]+'...'
                out.append({'sourceFilePath':f['sourceFilePath'],'text':txt})
    return count,out

def C(term, short, post, pearl, diff, safe, aliases=None, sub='Patoloji / morfoloji ve patogenez', priority='P1', match=88, phrase=True, risk='low'):
    return dict(term=term, aliases=aliases or [], short=short, post=post, pearl=pearl, diff=diff, safe=safe, subcategory=sub, priority=priority, matchingPriority=match, phraseOnly=phrase, ambiguityRisk=risk)

raw=[
C('Sıvılaşma nekrozu','Enzimatik sindirimin baskın olduğu, dokunun sıvı-kistik hale geldiği nekroz paternidir.','Sıvılaşma nekrozunda ölü hücreler ve stromal yapı proteolitik enzimlerle hızla parçalanır; bu yüzden doku mimarisi korunmaz. Beyin infarktı ve bakteriyel apse bu paternin klasik iki sınav bağlamıdır.','Beyin infarktı veya apse denirse koagülasyon değil sıvılaşma nekrozu düşünülür.','Koagülasyon nekrozunda doku ana hatları korunur; sıvılaşma nekrozunda doku yapısı erir ve kistik/pürülan içerik gelişir.',['Beyin infarktı','Apse','Nötrofil enzimleri'],['liquefactive necrosis'], 'Hücre hasarı / nekroz', 'P0'),
C('Protein denatürasyonu','Proteinlerin üç boyutlu yapısını kaybederek işlevsizleşmesidir.','Koagülasyon nekrozunda yapısal proteinler ve proteolitik enzimler denatüre olur. Bu durum hücre canlılığı kaybolmasına rağmen doku mimarisinin bir süre seçilebilmesini açıklar.','Solid organ infarktında mimarinin korunması protein denatürasyonu baskınlığıyla açıklanır.','Enzimatik sindirim baskınsa sıvılaşma nekrozu; protein denatürasyonu baskınsa koagülasyon nekrozu beklenir.',['Koagülasyon nekrozu','Proteolitik enzim','Solid organ infarktı'],[], 'Hücre hasarı / nekroz', 'P1'),
C('Hayalet hücre','Çekirdeği kaybolmuş ancak hücre sınırları silik şekilde seçilebilen nekrotik hücre görünümüdür.','Koagülasyon nekrozunda çekirdek piknoz, karyoreksis ve karyolizisle kaybolur; sitoplazmik kontur ise geçici olarak korunabilir. Bu mikroskobik görünüm “hayalet hücre” mantığıyla anlatılır.','Koagülasyon nekrozu = canlılık kaybı + geçici mimari korunumu + hayalet hücre.','Apoptozda apoptotik cisimcikler ve fagositoz; koagülasyon nekrozunda doku alanı ölümü ve hayalet hücreler öne çıkar.',['Koagülasyon nekrozu','Karyolizis','Piknoz'],[], 'Hücre hasarı / nekroz', 'P1'),
C('Proteolitik enzim','Proteinleri parçalayan, nekrotik dokunun sindiriminde rol alan enzim grubudur.','Nötrofil ve makrofajlardan salınan proteolitik enzimler nekrotik dokunun temizlenmesine katkı verir. Apse ve beyin infarktında doku mimarisinin erimesi bu enzimatik sindirimin baskınlığıyla ilişkilidir.','Apse + püy + doku erimesi ifadesi proteolitik/lizozomal enzimleri düşündürür.','Protein denatürasyonu dokuyu korur; proteolitik enzim aktivitesi dokuyu sıvılaştırır.',['Sıvılaşma nekrozu','Nötrofil','Lizozomal enzim'],[], 'Hücre hasarı / nekroz', 'P1'),
C('Nötrofil lizozomal enzimleri','Nötrofillerden salınarak mikroorganizma ve çevre dokuyu sindirebilen enzimlerdir.','Akut piyojenik inflamasyonda nötrofiller bakterileri öldürürken çevre dokuda da enzimatik hasar oluşturur. Bu süreç püy oluşumu ve sıvılaşma nekrozunun temelidir.','Bakteriyel apse sorusunda nötrofil lizozomal enzimleri doku erimesinin ana mekanizmasıdır.','Granülomatöz inflamasyon makrofaj/Th1 baskındır; apse nötrofil ve lizozomal enzim baskındır.',['Apse','Püy','Sıvılaşma nekrozu'],['nötrofil enzimleri','lizozomal enzimler'], 'Akut inflamasyon', 'P1'),
C('Apse','Püy içeren, çoğunlukla nötrofil ağırlıklı lokalize enfeksiyon odağıdır.','Apse merkezinde canlı ve ölü nötrofiller, nekrotik doku artıkları ve mikroorganizmalar bulunur. Nötrofil enzimleri çevre dokuyu erittiği için sıvılaşma nekrozu gelişir.','Apse = lokalize püy + nötrofil + sıvılaşma nekrozu.','Granülom kronik makrofaj yanıtıdır; apse akut nötrofilik yanıtın morfolojik sonucudur.',['Püy','Nötrofil','Sıvılaşma nekrozu'],[], 'Akut inflamasyon', 'P0'),
C('Püy','Nötrofil, nekrotik hücre artığı ve sıvı eksüdadan oluşan irinli içeriktir.','Püy, piyojenik bakterilere karşı gelişen akut inflamatuvar yanıtın sonucudur. İçeriğinde yoğun nötrofil ve lizozomal enzim bulunduğu için dokuda sıvılaşma nekrozu oluşturur.','Püy görülen lezyonda akut süpüratif inflamasyon ve apse akla gelir.','Seröz eksüda berrak-sıvı özelliklidir; püy yoğun nötrofil ve nekrotik debris içerir.',['Apse','Nötrofil','Eksüda'],[], 'Akut inflamasyon', 'P1'),
C('Amorf eozinofilik merkez','Mikroskopide hücresiz, granüler-pembe nekrotik merkez görünümüdür.','Kazeifikasyon nekrozunda doku mimarisi tamamen silinir ve merkezde amorf eozinofilik materyal birikir. Bu merkez epiteloid histiyositler ve dev hücrelerle çevrilirse kazeifiye granülom oluşur.','Amorf eozinofilik merkez + granülom = kazeifikasyon, özellikle tüberküloz.','Apse merkezinde pürülan nötrofilik içerik; kazeifikasyonda hücresiz amorf nekrotik merkez beklenir.',['Kazeifikasyon nekrozu','Granülom','Epiteloid histiyosit'],[], 'Granülomatöz inflamasyon', 'P1'),
C('Epiteloid histiyosit','Kronik inflamasyonda epitelsi görünüme dönüşmüş aktive makrofajdır.','Epiteloid histiyositler granülomun temel hücresidir. Th1-IFN-gamma ekseniyle aktive olan makrofajlar birleşerek dev hücreleri de oluşturabilir.','Granülom sorusunda epiteloid histiyosit makrofaj kökenli ana hücredir.','Nötrofil apseyi, epiteloid histiyosit granülomatöz inflamasyonu düşündürür.',['Granülom','IFN-gamma','Langhans dev hücresi'],[], 'Granülomatöz inflamasyon', 'P0'),
C('Tüberküloz granülomu','Merkezinde kazeifikasyon nekrozu bulunan enfeksiyöz granülom paternidir.','Tüberkülozda kalıcı antijenik uyarı Th1 yanıtını, IFN-gamma aracılı makrofaj aktivasyonunu ve epiteloid histiyositlerden oluşan granülomu oluşturur. Merkezde kazeifikasyon nekrozu tipiktir.','Kazeifiye granülom + Langhans dev hücresi + tüberküloz üçlüsünü birlikte düşün.','Sarkoidozda granülom genellikle nonkazeifiyedir; tüberkülozda kazeifikasyon ön plandadır.',['Kazeifikasyon nekrozu','Langhans dev hücresi','Epiteloid histiyosit'],['kazeifiye granülom'], 'Granülomatöz inflamasyon', 'P0'),
C('Enzimatik yağ nekrozu','Pankreatik lipazların yağ dokusunu parçalamasıyla gelişen yağ nekrozu tipidir.','Akut pankreatitte lipazlar peripankreatik yağ dokusunu trigliseritlerden serbest yağ asitlerine ayırır. Bu yağ asitleri kalsiyumla birleşerek tebeşirimsi sabunlaşma odakları oluşturur.','Akut pankreatit + tebeşirimsi beyaz odak + hipokalsemi = enzimatik yağ nekrozu.','Travmatik yağ nekrozu daha çok memede sert kitle/fibrozisle maligniteyi taklit eder.',['Akut pankreatit','Sabunlaşma','Hipokalsemi'],[], 'Hücre hasarı / nekroz', 'P0'),
C('Sabunlaşma','Yağ asitlerinin kalsiyumla birleşerek kalsiyum sabunları oluşturmasıdır.','Yağ nekrozunda serbest yağ asitleri kalsiyumu bağlayabilir. Akut pankreatitte bu süreç hipokalsemi ve tebeşirimsi beyaz nekroz odaklarıyla ilişkilidir.','Pankreatit sorusunda sabunlaşma, enzimatik yağ nekrozunun morfolojik anahtar kelimesidir.','Distrofik kalsifikasyon ölü dokuda kalsiyum birikimidir; sabunlaşma yağ nekrozu bağlamında yağ asidi-kalsiyum birleşimini vurgular.',['Enzimatik yağ nekrozu','Akut pankreatit','Kalsiyum'],[], 'Hücre hasarı / nekroz', 'P1'),
C('Travmatik yağ nekrozu','Travma sonrası yağ dokusunda nekroz, inflamasyon ve fibrozis gelişmesidir.','Memede travmatik yağ nekrozu sert kitle, kalsifikasyon ve fibrozis oluşturabilir. Klinik ve radyolojik olarak meme kanserini taklit edebilmesi sınav açısından önemlidir.','Memede travma sonrası sert kitle malignite değil travmatik yağ nekrozu olabilir.','Enzimatik yağ nekrozu pankreatitle; travmatik yağ nekrozu meme travması ve kanser taklidiyle ilişkilidir.',['Meme kitlesi','Fibrozis','Kalsifikasyon'],[], 'Hücre hasarı / nekroz', 'P1'),
C('Fibrin benzeri materyal','Damar duvarı hasarında plazma proteinleri ve fibrinin oluşturduğu parlak eozinofilik birikimdir.','Fibrinoid nekrozda damar duvarına sızan plazma proteinleri, immün kompleksler ve fibrin parlak pembe bir görünüm oluşturur. Vaskülit ve malign hipertansiyon bu bulgunun klasik bağlamlarıdır.','Damar duvarında parlak eozinofilik fibrin benzeri materyal = fibrinoid nekroz.','Amiloid ekstraselüler protein birikimidir; fibrinoid materyal damar duvarı hasarı ve immün komplekslerle ilişkilidir.',['Fibrinoid nekroz','Vaskülit','Malign hipertansiyon'],[], 'Vasküler patoloji', 'P1'),
C('Vaskülit','Damar duvarında inflamasyon ve hasarla seyreden patolojik süreçtir.','Vaskülitte damar duvarı inflamasyonu lümen daralması, tromboz, iskemi veya kanamaya yol açabilir. İmmün kompleks aracılı tiplerde fibrinoid nekroz tipik morfolojik ipucudur.','Damar duvarı + immün kompleks + fibrinoid nekroz birlikte vasküliti düşündürür.','Ateroskleroz lüminal plak ve kronik intimal süreçtir; vaskülit damar duvarında aktif inflamasyonla ayrılır.',['Fibrinoid nekroz','İmmün kompleks','Damar duvarı'],[], 'Vasküler patoloji', 'P0'),
C('Malign hipertansiyon arteriolopatisi','Ağır hipertansiyonda arteriol duvarında fibrinoid nekroz ve hiperplastik değişiklikle seyreden hasardır.','Malign hipertansiyon endotel hasarı ve plazma protein sızıntısı oluşturarak arteriol duvarında fibrinoid nekroza yol açabilir. Böbrekte “onion-skin” benzeri hiperplastik arterioloskleroz eşlik edebilir.','Malign HT + arteriol + fibrinoid nekroz ifadesi hipertansif vasküler hasarı gösterir.','Benign hipertansiyonda hiyalin arterioloskleroz; malign hipertansiyonda fibrinoid nekroz ve hiperplastik arterioloskleroz daha tipiktir.',['Fibrinoid nekroz','Arteriol','Endotel hasarı'],['malign hipertansiyon'], 'Vasküler patoloji', 'P1'),
C('Endotel hasarı','Damar iç yüzeyinin hasarlanarak tromboz ve inflamasyona zemin hazırlamasıdır.','Endotel antitrombotik yüzeyin temelidir; hasarlandığında trombosit adezyonu, koagülasyon aktivasyonu ve damar duvarına protein sızıntısı artar. Virchow triadının temel bileşenlerinden biridir.','Tromboz sorusunda endotel hasarı, staz ve hiperkoagülabilite ile birlikte düşünülür.','Endotel disfonksiyonu fonksiyon bozukluğunu; endotel hasarı yapısal yüzey bozulmasını vurgular.',['Tromboz','Virchow triadı','Fibrinoid nekroz'],[], 'Hemodinamik bozukluklar', 'P1'),
C('Apoptotik cisimcik','Apoptozda hücrenin membranla çevrili küçük parçalara ayrılmış formudur.','Apoptoz sırasında hücre küçülür, kromatin yoğunlaşır ve membran bütünlüğü korunarak apoptotik cisimcikler oluşur. Bu parçalar fagosite edildiği için belirgin inflamasyon beklenmez.','Apoptoz = apoptotik cisimcik + membran bütünlüğü + inflamasyon yokluğu.','Nekrozda membran rüptürü ve inflamasyon vardır; apoptozda membranlı cisimcikler ve sessiz fagositoz vardır.',['Apoptoz','Kaspaz','İnflamasyon yokluğu'],[], 'Hücre ölümü / apoptoz', 'P0'),
C('İntrinsik apoptoz yolu','Mitokondri aracılı sitokrom c salınımı ve kaspaz aktivasyonu ile ilerleyen apoptoz yoludur.','DNA hasarı, büyüme faktörü eksikliği veya hücresel stres BAX/BAK aracılığıyla mitokondri dış membran permeabilitesini artırır. Sitokrom c salınımı apoptosomu ve kaspaz-9 aktivasyonunu başlatır.','Mitokondri + sitokrom c + kaspaz-9 = intrinsik apoptoz yolu.','Ekstrinsik yol ölüm reseptörü ve kaspaz-8 üzerinden; intrinsik yol mitokondri ve kaspaz-9 üzerinden ilerler.',['Sitokrom c','BAX','Kaspaz 9'],['intrinsik apoptoz'], 'Hücre ölümü / apoptoz', 'P0'),
C('Kaspaz 9','İntrinsik apoptoz yolunda apoptosomla aktive olan başlatıcı kaspazdır.','Sitokrom c salınımı Apaf-1 ile apoptosom oluşumunu tetikler ve kaspaz-9’u aktive eder. Kaspaz-9 daha sonra yürütücü kaspazları etkinleştirerek apoptotik morfolojiyi oluşturur.','Kaspaz-9 intrinsik; kaspaz-8 ekstrinsik apoptoz yoluyla ilişkilidir.','Kaspazlar apoptozda kontrollü parçalanmayı sağlar; nekrozda temel olay membran yırtılması ve inflamasyondur.',['İntrinsik apoptoz yolu','Sitokrom c','Apoptotik cisimcik'],[], 'Hücre ölümü / apoptoz', 'P1'),
C('Beta-pleated sheet yapısı','Amiloid proteinlerinin katlanarak oluşturduğu dayanıklı fibriler konformasyondur.','Amiloid fibrilleri beta-pleated sheet yapısı nedeniyle dokuda çözünmeyen ekstraselüler birikim oluşturur. Congo red ile boyanıp polarize ışıkta elma yeşili çift kırınım göstermesi bu yapıyla ilişkilidir.','Amiloid = beta-pleated sheet + Congo red + elma yeşili çift kırınım.','Hiyalin görünüm genel pembe proteinöz görünümü anlatır; amiloid özel beta-pleated sheet yapısı ve Congo red pozitifliğiyle ayrılır.',['Amiloid','Congo red','Elma yeşili çift kırınım'],['beta-pleated sheet'], 'Protein birikimleri', 'P0'),
C('AL amiloidoz','İmmünoglobulin hafif zincirlerinden gelişen amiloidoz tipidir.','AL amiloidoz plazma hücre diskrazilerinde hafif zincir üretiminin artmasıyla oluşur. Kalp, böbrek ve dil gibi dokularda ekstraselüler amiloid birikimi yapabilir.','Multiple miyelom/plazma hücre diskrazisi + hafif zincir = AL amiloidoz.','AA amiloidoz kronik inflamasyonda serum amyloid A’dan gelişir; AL hafif zincir kökenlidir.',['Hafif zincir','Plazma hücre diskrazisi','Amiloid'],[], 'Protein birikimleri', 'P0'),
C('AA amiloidoz','Kronik inflamasyona bağlı serum amyloid A’dan gelişen sekonder amiloidoz tipidir.','Uzun süren inflamatuvar hastalıklarda karaciğerden SAA üretimi artar ve yanlış katlanan protein dokularda AA amiloid olarak birikir. Böbrek tutulumu sık klinik sonuçlardan biridir.','Kronik inflamasyon + SAA kökenli amiloid = AA amiloidoz.','AL amiloidoz plazma hücre/hafif zincir; AA amiloidoz kronik inflamasyon/SAA kökenlidir.',['Kronik inflamasyon','Amiloid','Böbrek tutulumu'],[], 'Protein birikimleri', 'P1'),
C('Plazma hücre diskrazisi','Klonal plazma hücrelerinin immünoglobulin veya hafif zincir ürettiği hastalık grubudur.','Plazma hücre diskrazilerinde monoklonal protein ve hafif zincir üretimi artabilir. Bu durum multiple miyelom, AL amiloidoz ve Bence Jones proteinürisi gibi tablolarla ilişkilidir.','AL amiloidoz veya M protein sorusunda plazma hücre diskrazisini düşün.','Reaktif plazmasitoz poliklonaldir; diskrazi klonal monoklonal protein üretimiyle ayrılır.',['AL amiloidoz','Hafif zincir','M proteini'],[], 'Hematopatoloji', 'P1'),
C('Karsinoma in situ','Bazal membranı aşmadan epitel içinde sınırlı kalan malign epitelyal proliferasyondur.','Karsinoma in situ hücrelerde malign sitolojik atipi içerir ancak invazyon yoktur. Bazal membran aşılırsa invaziv karsinom tanısı konur.','Karsinoma in situ = malign hücre + epitel içinde sınırlı + bazal membran sağlam.','Displazi preinvaziv atipi spektrumudur; invaziv karsinomda bazal membran aşılmıştır.',['Bazal membran','Displazi','İnvazyon'],['CIS'], 'Neoplazi / tümör biyolojisi', 'P0'),
C('Premalign lezyon','Kanser gelişme riski artmış ancak invaziv malignite olmayan öncül lezyondur.','Premalign lezyonlar genellikle displazi, metaplazi zemininde displazi veya in situ değişiklikler içerir. Klinik önemi izlem veya tedaviyle invaziv kansere ilerleme riskinin azaltılmasıdır.','Barrett özofagusu gibi premalign lezyonlarda asıl risk displazi ve adenokarsinom gelişimidir.','Benign lezyon her zaman premalign değildir; premalign lezyon kanserleşme potansiyeli taşıdığı için izlenir.',['Displazi','Metaplazi','Karsinoma in situ'],[], 'Neoplazi / tümör biyolojisi', 'P1'),
C('Bazal membran','Epitel ile alttaki stromayı ayıran, invazyon sınırı olarak kullanılan matriks tabakasıdır.','Epitel tümörlerinde bazal membranın sağlam kalması in situ lezyonu, aşılması invaziv karsinomu destekler. Bu nedenle patolojide invazyon değerlendirmesinin temel morfolojik sınırıdır.','Bazal membran aşılmadıysa in situ; aşıldıysa invaziv karsinom düşünülür.','Basement membrane kaybı invazyonu gösterir; epitel içi atipi tek başına metastaz kapasitesi anlamına gelmez.',['Karsinoma in situ','İnvaziv karsinom','Stroma'],['basement membrane'], 'Neoplazi / tümör biyolojisi', 'P0'),
C('Orphan Annie nükleusu','Papiller tiroid karsinomunda görülen optik olarak boş, soluk nükleer görünümüdür.','Papiller tiroid karsinomunda nükleer clearing nedeniyle nükleus boş/şeffaf izlenir. Nükleer groove ve psammoma cisimcikleriyle birlikte tanısal ipucu değerindedir.','Orphan Annie nükleusu + nükleer groove + psammoma cisimciği = papiller tiroid karsinomu.','Folliküler karsinomda tanı kapsül/damar invazyonuna dayanır; papiller karsinomda nükleer özellikler öne çıkar.',['Papiller tiroid karsinomu','Nükleer groove','Psammoma cisimciği'],['Orphan Annie','Orphan Annie eye nuclei'], 'Endokrin patoloji', 'P0'),
C('Nükleer groove','Nükleusta çizgi/yarık şeklinde katlantı görünümüdür.','Papiller tiroid karsinomunda nükleer zar katlantıları nükleer groove olarak görülür. Orphan Annie nükleusu ve psammoma cisimciğiyle birlikte tanı değerini artırır.','Nükleer groove papiller tiroid karsinomunun klasik nükleer bulgularındandır.','Nükleer pleomorfizm genel malignite bulgusudur; nükleer groove papiller tiroid yönünde daha spesifik ipucudur.',['Papiller tiroid karsinomu','Orphan Annie nükleusu','Psammoma cisimciği'],['nükleer yarıklanma'], 'Endokrin patoloji', 'P1'),
C('Psammoma cisimciği','Konsantrik lameller kalsifikasyon odağıdır.','Psammoma cisimcikleri papiller tiroid karsinomu başta olmak üzere papiller seröz tümörlerde görülebilir. Nekrotik papiller uçlar üzerinde distrofik kalsifikasyon gelişmesiyle oluşur.','Papiller yapı + psammoma cisimciği tiroid ve over seröz tümörlerinde sınav ipucudur.','Keratin incisi skuamöz diferansiyasyonu; psammoma cisimciği lameller kalsifikasyonu gösterir.',['Papiller tiroid karsinomu','Distrofik kalsifikasyon','Papiller tümör'],[], 'Tümör morfolojisi', 'P0'),
C('Lenfatik yayılım','Tümör hücrelerinin lenf damarları ve lenf nodları üzerinden yayılmasıdır.','Karsinomlar sıklıkla bölgesel lenf nodlarına lenfatik yolla yayılır. Papiller tiroid karsinomu için servikal lenf nodu yayılımı klasik bir örnektir.','Karsinomlar lenfatik; sarkomlar daha çok hematolojik yayılım eğilimindedir.','Hematolojik yayılım kan damarlarıyla uzak organ metastazını; lenfatik yayılım bölgesel nod tutulumunu vurgular.',['Metastaz','Lenf nodu','Papiller tiroid karsinomu'],[], 'Neoplazi / yayılım', 'P1'),
C('Kapsül invazyonu','Tümörün çevresindeki kapsül yapısını aşarak dışarı ilerlemesidir.','Folliküler tiroid karsinomunda malignite tanısı sitolojik atipiden çok kapsül ve/veya damar invazyonunun gösterilmesine dayanır. Bu nedenle kapsül invazyonu folliküler adenom-karsinom ayrımında kritiktir.','Folliküler tiroid tümöründe kapsül/damar invazyonu yoksa karsinom denmez.','Papiller tiroid karsinomunda nükleer özellikler; folliküler karsinomda kapsül/damar invazyonu belirleyicidir.',['Folliküler karsinom','Damar invazyonu','Tiroid nodülü'],[], 'Endokrin patoloji', 'P0'),
C('Keratin incisi','Skuamöz hücreli karsinomda tümör adacıkları içinde konsantrik keratin birikimidir.','Keratin incileri ve intersellüler köprüler skuamöz diferansiyasyonu gösterir. Santral bronş yerleşimli sigara ilişkili akciğer tümöründe bu bulgu klasik olarak skuamöz hücreli karsinomu destekler.','Keratin incisi + intersellüler köprü = skuamöz hücreli karsinom.','Adenokarsinom bez/müsin yapar; skuamöz karsinom keratin ve intersellüler köprü yapar.',['Skuamöz hücreli karsinom','İntersellüler köprü','Santral bronş'],[], 'Akciğer / tümör morfolojisi', 'P0'),
C('İntersellüler köprü','Skuamöz hücreler arasında desmozomal bağlantıları gösteren mikroskobik köprü görünümüdür.','İntersellüler köprüler skuamöz diferansiyasyonun morfolojik kanıtıdır. Keratin incileriyle birlikte skuamöz hücreli karsinom tanısını destekler.','Keratin incisi ve intersellüler köprü birlikteyse skuamöz diferansiyasyon düşünülür.','Adenokarsinomda glandüler yapı ve müsin; skuamöz karsinomda keratin ve intersellüler köprü beklenir.',['Keratin incisi','Skuamöz hücreli karsinom','Desmozom'],[], 'Tümör morfolojisi', 'P1'),
C('Skuamöz metaplazi','Normal epitelin çok katlı yassı epitele dönüşmesidir.','Sigara irritasyonu bronş epitelinde skuamöz metaplazi oluşturabilir. Sürekli hasar devam ederse displazi ve skuamöz hücreli karsinom gelişimine zemin hazırlayabilir.','Bronşta sigara + skuamöz metaplazi + displazi = skuamöz karsinom prekürsörü.','Metaplazi adaptiftir ve geri dönebilir; displazi premalign atipiyi gösterir.',['Bronş epiteli','Displazi','Skuamöz hücreli karsinom'],[], 'Hücre adaptasyonları', 'P0'),
C('Küçük hücreli karsinom','Yüksek dereceli nöroendokrin akciğer karsinomudur.','Küçük hücreli akciğer karsinomu sigarayla güçlü ilişkilidir, santral yerleşir ve erken metastaz yapar. SIADH veya ektopik ACTH gibi paraneoplastik sendromlar oluşturabilir.','Santral akciğer tümörü + nöroendokrin marker + SIADH/ektopik ACTH = küçük hücreli karsinom.','Skuamöz karsinom keratin incisi; küçük hücreli karsinom küçük mavi hücre, yüksek mitoz ve erken yayılımla ayrılır.',['Nöroendokrin marker','Ektopik ACTH','SIADH'],['small cell carcinoma'], 'Akciğer patolojisi', 'P0'),
C('Nöroendokrin marker','Nöroendokrin diferansiyasyonu gösteren immünohistokimyasal belirteç grubudur.','Sinaptofizin, kromogranin ve CD56 gibi markerlar nöroendokrin tümörlerde pozitif olabilir. Küçük hücreli akciğer karsinomunda tanısal destek sağlar.','Küçük hücreli karsinomda nöroendokrin marker pozitifliği beklenir.','Nöroendokrin marker tümör kökenini destekler; tek başına davranış derecesini belirlemez.',['Küçük hücreli karsinom','Sinaptofizin','Kromogranin'],[], 'İmmünohistokimya', 'P1'),
C('Ektopik ACTH üretimi','Hipofiz dışı tümör dokusundan ACTH salınmasıdır.','Küçük hücreli akciğer karsinomu gibi nöroendokrin tümörler ektopik ACTH üretebilir. Sonuçta Cushing sendromu bulguları ve hipokalemik metabolik alkaloz görülebilir.','Küçük hücreli akciğer karsinomu paraneoplastik olarak SIADH veya ektopik ACTH yapabilir.','Hipofizer Cushing ACTH’nin hipofiz kaynaklı olmasıyla; ektopik ACTH tümör kaynaklı olmasıyla ayrılır.',['Küçük hücreli karsinom','Paraneoplastik sendrom','Cushing sendromu'],['ektopik ACTH'], 'Paraneoplastik patoloji', 'P1'),
C('Küçük mavi hücreli tümör','Yoğun nükleuslu, az sitoplazmalı küçük hücrelerden oluşan tümör morfoloji grubudur.','Küçük mavi hücreli tümör paterni Ewing sarkomu, lenfoma, nöroblastom ve küçük hücreli karsinom gibi farklı tanıları kapsar. Ayırıcı tanı yaş, lokalizasyon, immünohistokimya ve genetikle yapılır.','Küçük mavi hücre görünümü tanı değil; ayırıcı tanı başlatan morfolojik paterndir.','Malign osteoid üretimi osteosarkomu; küçük yuvarlak mavi hücre + t(11;22) Ewing sarkomunu destekler.',['Ewing sarkomu','Lenfoma','Nöroblastom'],['küçük mavi hücre','küçük yuvarlak mavi hücreli tümör'], 'Tümör morfolojisi', 'P1'),
C('Mikroglia','Santral sinir sisteminin makrofaj benzeri fagositik hücresidir.','Beyin infarktı sonrası nekrotik dokunun temizlenmesinde mikroglia ve makrofajlar görev alır. Doku erimesi kistik boşlukla sonuçlanabilir.','Beyin infarktında sıvılaşma nekrozunu mikroglial fagositoz ve kistik boşluk izler.','Astrositler gliozisle skar yanıtı oluşturur; mikroglia fagositozda öne çıkar.',['Beyin infarktı','Sıvılaşma nekrozu','Gliozis'],[], 'Nöropatoloji', 'P1'),
C('Gliozis','Santral sinir sisteminde astrosit proliferasyonu ve reaktif skar yanıtıdır.','CNS hasarında fibroblastik skar yerine astrositlerin reaktif proliferasyonu görülür. Beyin infarktı sonrası nekrotik alan temizlenirken gliozis çevresel onarım yanıtının parçasıdır.','CNS hasarında fibrozis değil gliozis kavramı kullanılır.','Mikroglia fagositoz; astrosit gliozis ve skar yanıtıyla ilişkilidir.',['Astrosit','Beyin infarktı','Kistik boşluk'],[], 'Nöropatoloji', 'P1'),
C('Kistik boşluk','Beyin infarktı sonrası sıvılaşan nekrotik dokunun temizlenmesiyle kalan boşluktur.','Beyinde iskemik nekroz koagülasyon yerine sıvılaşma nekrozu yapar. Nekrotik materyal fagosite edildikten sonra parankimde kistik boşluk kalabilir.','Beyin infarktının geç dönem sonucu kistik boşluk olabilir.','Solid organ infarktlarında skar; beyin infarktında sıvılaşma ve kistik boşluk beklenir.',['Sıvılaşma nekrozu','Beyin infarktı','Mikroglia'],[], 'Nöropatoloji', 'P2'),
C('Enfeksiyöz granülom','Kalıcı mikroorganizmaya karşı gelişen granülomatöz inflamasyon paternidir.','Tüberküloz ve bazı fungal enfeksiyonlarda makrofajlar epiteloid hücrelere dönüşür ve granülom oluşturur. Kazeifikasyon varlığı enfeksiyöz etkenleri düşündüren önemli morfolojik ipucudur.','Kazeifiye granülomda özel boyalarla mikobakteri/fungal etken aranır.','Sarkoidoz genellikle nonkazeifiye granülom; enfeksiyöz granülom sıklıkla kazeifikasyon ve etken arama gerektirir.',['Tüberküloz granülomu','Fungal enfeksiyon','Özel boya'],[], 'Granülomatöz inflamasyon', 'P1'),
C('Th1 yanıtı','Hücresel immüniteyi ve makrofaj aktivasyonunu yönlendiren T yardımcı hücre yanıtıdır.','Granülom oluşumunda antijen sunumu IL-12 aracılığıyla Th1 farklılaşmasını artırır. Th1 hücrelerinden salınan IFN-gamma makrofajları aktive ederek epiteloid histiyosit ve dev hücre oluşumunu destekler.','Granülom patogenezinde Th1–IFN-gamma–makrofaj aksı temel mekanizmadır.','Th2 yanıtı eozinofil/IgE eğilimli alerjik-paraziter yanıtlarla; Th1 yanıtı makrofaj aktivasyonu ve granülomla ilişkilidir.',['IFN-gamma','IL-12','Makrofaj aktivasyonu'],['T hücre yanıtı'], 'İmmünopatoloji', 'P0'),
C('IFN-gamma','Th1 ve NK hücrelerinden salınan, makrofaj aktivasyonunda kritik sitokindir.','IFN-gamma makrofajların mikrobisidal ve epiteloid dönüşüm kapasitesini artırır. Granülomatöz inflamasyonda antijenin çevrelenmesi ve kontrol altına alınmasında temel sinyaldir.','Granülom sorusunda IFN-gamma makrofaj aktivasyonunu sağlayan ana sitokindir.','IL-4/IL-5 daha çok Th2; IFN-gamma Th1 ve granülomatöz inflamasyonla ilişkilidir.',['Th1 yanıtı','Makrofaj aktivasyonu','Granülom'],[], 'İmmünopatoloji', 'P0'),
C('IL-12','Makrofaj ve dendritik hücrelerden salınıp Th1 farklılaşmasını destekleyen sitokindir.','IL-12, T hücrelerini Th1 yönünde polarize eder ve IFN-gamma üretimini artırır. Bu aks granülom oluşumu ve hücre içi patojen kontrolünde önemlidir.','IL-12 → Th1 → IFN-gamma → makrofaj aktivasyonu zincirini kur.','IL-10 antiinflamatuvar baskılayıcıdır; IL-12 hücresel immün yanıtı güçlendirir.',['Th1 yanıtı','IFN-gamma','Granülom'],[], 'İmmünopatoloji', 'P1'),
C('Hiperakut rejeksiyon','Transplantasyondan dakikalar-saatler sonra gelişen antikor aracılı greft trombozu ve nekrozudur.','Alıcıda önceden var olan ABO veya HLA antikorları donör endoteline bağlanır. Kompleman aktivasyonu, vasküler hasar, tromboz ve hızlı greft nekrozu gelişir.','Dakikalar-saatler içinde greft trombozu = hiperakut rejeksiyon.','Akut hücresel rejeksiyon günler-haftalar içinde T hücre/tubülit; hiperakut rejeksiyon preformed antikor ve trombozla ayrılır.',['Preformed antikor','Donör endoteli','Kompleman'],[], 'Transplant patolojisi', 'P0'),
C('Preformed antikor','Transplantasyondan önce alıcıda mevcut olan donör antijenlerine karşı antikordur.','Preformed anti-ABO veya anti-HLA antikorları donör endoteline hızla bağlanır. Bu bağlanma hiperakut rejeksiyonda kompleman aktivasyonu ve vasküler trombozun başlangıcıdır.','Hiperakut rejeksiyonda yeni yanıt beklenmez; önceden var olan antikor vardır.','Akut hücresel rejeksiyonda T hücre yanıtı zamanla gelişir; preformed antikor hiperakut tabloyu açıklar.',['Hiperakut rejeksiyon','HLA antikoru','ABO uyumsuzluğu'],[], 'Transplant patolojisi', 'P1'),
C('Donör endoteli','Transplante edilen organın damar iç yüzeyini oluşturan hedef hücre tabakasıdır.','Hiperakut rejeksiyonda alıcı antikorları öncelikle donör endotel antijenlerine bağlanır. Endotel hasarı kompleman aktivasyonu, tromboz ve greft iskemisiyle sonuçlanır.','Rejeksiyonda vasküler hedef çoğu zaman donör endoteli üzerinden okunur.','Parankimal hücre hasarı kronik süreçte görülebilir; hiperakut hasarın ilk hedefi vasküler endoteldir.',['Hiperakut rejeksiyon','Endotel hasarı','Tromboz'],[], 'Transplant patolojisi', 'P1'),
C('ABO uyumsuzluğu','Alıcı antikorlarının donör ABO antijenleriyle uyumsuz olduğu transplant/kan grubu durumudur.','ABO uyumsuzluğu güçlü preformed antikor yanıtı oluşturabilir. Transplantta bu antikorlar donör endoteline bağlanıp hiperakut rejeksiyon riskini artırır.','ABO uyumsuzluğu hiperakut rejeksiyonun klasik nedenlerinden biridir.','HLA uyumsuzluğu da önemlidir; ABO uyumsuzluğu özellikle hızlı antikor aracılı vasküler hasarla ilişkilidir.',['Preformed antikor','Hiperakut rejeksiyon','Donör endoteli'],[], 'Transplant patolojisi', 'P1'),
C('HLA antikoru','Donör HLA antijenlerine karşı gelişmiş veya önceden var olan antikordur.','Anti-HLA antikorları transplant reddinde antikor aracılı vasküler hasara yol açabilir. Önceden mevcutsa hiperakut rejeksiyon, sonradan gelişirse antikor aracılı akut/kronik hasar oluşturabilir.','Transplant sorusunda HLA antikoru vasküler-endotelyal hasar mantığıyla düşünülür.','T hücresel rejeksiyonda hücresel infiltrasyon; HLA antikorunda kompleman ve vasküler hasar daha belirgindir.',['Hiperakut rejeksiyon','Preformed antikor','Kompleman'],[], 'Transplant patolojisi', 'P1'),
C('Tubülit','Böbrek greftinde lenfositlerin tübül epiteline saldırmasıdır.','Akut hücresel rejeksiyonda T lenfositler interstisyuma ve tübül epiteline infiltre olur. Tubülit, böbrek transplant biyopsisinde hücresel rejeksiyonun önemli morfolojik bulgusudur.','Transplanttan günler-haftalar sonra interstisyel infiltrasyon + tubülit = akut hücresel rejeksiyon.','Hiperakut rejeksiyonda tromboz/nekroz; akut hücresel rejeksiyonda tubülit ve T hücre infiltrasyonu öne çıkar.',['Akut hücresel rejeksiyon','T lenfosit','İnterstisyel infiltrasyon'],[], 'Transplant patolojisi', 'P0'),
C('İnterstisyel infiltrasyon','Doku aralığında inflamatuvar hücre birikimidir.','Böbrek greftinde interstisyel mononükleer infiltrasyon akut hücresel rejeksiyonun temel parçasıdır. Hücresel infiltrasyon tübülite eşlik ettiğinde tanısal değeri artar.','Greftte interstisyel mononükleer infiltrasyon + tubülit hücresel rejeksiyonu destekler.','İnterstisyel infiltrasyon yerleşimi anlatır; tubülit tübül epitel hedeflenmesini gösterir.',['Tubülit','Akut hücresel rejeksiyon','T lenfosit'],[], 'Transplant patolojisi', 'P1'),
C('Kronik rejeksiyon','Transplant sonrası aylar-yıllar içinde gelişen ilerleyici vasküler daralma ve fibrozisle giden rejeksiyondur.','Kronik rejeksiyonda immün hasar damar lümeninde daralma, intimal fibrozis ve parankimal atrofi oluşturur. Sonuç greftin yavaş ve kalıcı fonksiyon kaybıdır.','Aylar-yıllar sonra intimal fibrozis + lümen daralması = kronik rejeksiyon.','Hiperakut rejeksiyon dakikalar-saatler; akut rejeksiyon günler-haftalar; kronik rejeksiyon aylar-yıllar içinde gelişir.',['İntimal fibrozis','Obliteratif vaskülopati','Greft iskemisi'],[], 'Transplant patolojisi', 'P0'),
C('İntimal fibrozis','Damar intimasında fibrotik kalınlaşma ve lümen daralması gelişmesidir.','Kronik greft rejeksiyonunda intimal fibrozis damar lümenini daraltarak kronik iskemiye yol açar. Bu durum parankimal atrofi ve greft fonksiyon kaybını açıklar.','Kronik rejeksiyonda ana vasküler bulgu intimal fibrozis ve lümen daralmasıdır.','Ateroskleroz lipid plakla; kronik rejeksiyon immün aracılı intimal fibrozisle öne çıkar.',['Kronik rejeksiyon','Lümen daralması','Parankimal atrofi'],[], 'Vasküler / transplant patoloji', 'P1'),
C('Obliteratif vaskülopati','Damar lümeninin intimal kalınlaşma ile ilerleyici olarak daralmasıdır.','Kronik greft rejeksiyonunda obliteratif vaskülopati greft dokusunda sürekli hipoperfüzyon oluşturur. Fibrozis ve atrofi bu kronik iskeminin sonucudur.','Kronik greft kaybı sorusunda obliteratif vaskülopati temel mekanizmadır.','Akut tromboz ani lümen tıkanmasıdır; obliteratif vaskülopati yavaş ilerleyen intimal daralmadır.',['Kronik rejeksiyon','İntimal fibrozis','Greft iskemisi'],[], 'Vasküler / transplant patoloji', 'P1'),
C('Megakaryosit artışı','Kemik iliğinde trombosit öncül hücrelerinin sayıca artmasıdır.','Periferik trombosit yıkımı arttığında kemik iliği kompansatuvar olarak megakaryosit üretimini artırabilir. İmmün trombositopenide trombosit azlığına rağmen ilikte megakaryosit artışı bu mekanizmayı destekler.','Trombositopeni + ilikte megakaryosit artışı = üretim değil periferik yıkım düşün.','Aplastik anemide üretim azalır ve ilik hiposellülerdir; ITP’de megakaryosit artışı beklenebilir.',['İmmün trombositopeni','Trombosit yıkımı','Kemik iliği'],[], 'Hematopatoloji', 'P1'),
C('Primer hemostaz','Trombosit adezyonu, aktivasyonu ve agregasyonu ile ilk tıkaç oluşumudur.','Primer hemostaz bozukluklarında mukokutanöz kanama, peteşi ve purpura daha belirgindir. İmmün trombositopenide PT/aPTT genellikle normaldir çünkü pıhtılaşma faktörleri değil trombositler etkilenir.','Peteşi/purpura + normal PT/aPTT primer hemostaz sorununu düşündürür.','Sekonder hemostaz faktör kaskadı ve fibrin oluşumudur; primer hemostaz trombosit tıkacıyla ilgilidir.',['Trombosit','PT normal','aPTT normal'],[], 'Hemostaz patolojisi', 'P0'),
C('vWF multimerleri','Von Willebrand faktörünün trombosit adezyonunda görevli büyük multimer formlarıdır.','ADAMTS13 normalde büyük vWF multimerlerini parçalar. Eksiklikte multimerler damar içinde trombosit agregasyonunu artırarak TTP mikrotrombüslerine yol açar.','ADAMTS13 eksikliği + büyük vWF multimerleri = TTP.','DIC yaygın koagülasyon aktivasyonu ve faktör tüketimidir; TTP büyük vWF multimerleri ve trombosit mikrotrombüsleriyle ayrılır.',['TTP','ADAMTS13','Mikrotrombüs'],['vWF multimerleri'], 'Hemostaz patolojisi', 'P0'),
C('Mikrotrombüs','Küçük damar lümeninde oluşan mikroskobik trombüslerdir.','TTP ve DIC gibi trombotik mikroanjiyopatilerde küçük damarlarda mikrotrombüsler oluşur. Eritrositler bu daralmış damarlardan geçerken parçalanarak şistosit oluşturabilir.','MAHA + şistosit + trombositopeni sorusunda mikrotrombüs mantığını kur.','Makrotrombüs büyük damar tıkanması; mikrotrombüs kapiller/arteriyol düzeyinde organ hasarı yapar.',['Şistosit','TTP','DIC'],[], 'Hemostaz patolojisi', 'P1'),
C('Tüketim koagülopatisi','Koagülasyon faktörleri ve trombositlerin yaygın pıhtılaşma nedeniyle tüketilmesidir.','DIC’de yaygın trombin oluşumu mikrotromboz yaparken trombosit ve faktörleri tüketir. Bu nedenle aynı hastada hem tromboz hem kanama bulguları gelişebilir.','DIC = mikrotromboz + tüketim koagülopatisi + kanama.','TTP’de PT/aPTT genellikle normal olabilir; DIC’de faktör tüketimi nedeniyle PT/aPTT uzar.',['DIC','Fibrinojen düşüklüğü','Yüksek D-dimer'],[], 'Hemostaz patolojisi', 'P0'),
C('Uzamış PT','Ekstrinsik ve ortak koagülasyon yolunun laboratuvar uzamasıdır.','PT uzaması özellikle faktör VII, ortak yol faktörleri, karaciğer hastalığı, K vitamini eksikliği veya DIC gibi durumlarda görülür. DIC’de aPTT ile birlikte uzaması tüketim koagülopatisini destekler.','DIC’de PT ve aPTT uzar, fibrinojen düşer, D-dimer yükselir.','PT daha çok ekstrinsik yol; aPTT intrinsik yol hakkında bilgi verir.',['DIC','Tüketim koagülopatisi','Fibrinojen düşüklüğü'],[], 'Laboratuvar / hemostaz', 'P1'),
C('Uzamış aPTT','İntrinsik ve ortak koagülasyon yolunun laboratuvar uzamasıdır.','aPTT uzaması hemofili, heparin etkisi, lupus antikoagülanı veya DIC gibi durumlarda görülebilir. DIC’de PT ile birlikte uzaması yaygın faktör tüketimini düşündürür.','PT+aPTT birlikte uzunsa ortak yol/faktör tüketimi düşün.','Primer trombosit bozukluklarında PT/aPTT normal kalabilir; faktör bozukluklarında aPTT veya PT uzar.',['DIC','Hemofili','Tüketim koagülopatisi'],[], 'Laboratuvar / hemostaz', 'P1'),
C('Fibrinojen düşüklüğü','Pıhtılaşma faktörü I düzeyinin azalmasıdır.','DIC’de fibrinojen yaygın fibrin oluşumu sırasında tüketilir. Bu bulgu yüksek D-dimer ve uzamış PT/aPTT ile birlikte tüketim koagülopatisini destekler.','DIC laboratuvarı: trombosit düşük, PT/aPTT uzun, fibrinojen düşük, D-dimer yüksek.','Karaciğer hastalığında sentez azalabilir; DIC’de tüketim ve fibrinoliz baskındır.',['DIC','Yüksek D-dimer','Tüketim koagülopatisi'],[], 'Laboratuvar / hemostaz', 'P1'),
C('Ferritin düşüklüğü','Vücut demir depolarının azaldığını gösteren laboratuvar bulgusudur.','Demir eksikliği anemisinde ferritin genellikle düşüktür ve depo demirin azaldığını gösterir. Kronik hastalık anemisinde ferritin akut faz reaktanı olduğu için normal veya yüksek olabilir.','Mikrositer anemide düşük ferritin demir eksikliğini en güçlü destekleyen bulgudur.','TIBC demir bağlama kapasitesini; ferritin depo demirini gösterir.',['Demir eksikliği anemisi','Mikrositer hipokrom anemi','TIBC yüksekliği'],['ferritin düşük'], 'Hematopatoloji / anemi', 'P0'),
C('TIBC yüksekliği','Transferrin aracılı toplam demir bağlama kapasitesinin artmasıdır.','Demir eksikliğinde karaciğer daha fazla transferrin üretir ve TIBC yükselir. Kronik hastalık anemisinde ise demir tutulumu artar ama TIBC genellikle düşük veya normaldir.','Demir eksikliği: ferritin düşük, serum demiri düşük, TIBC yüksek.','Ferritin depoyu; TIBC transferrin kapasitesini gösterir.',['Demir eksikliği anemisi','Ferritin düşüklüğü','Serum demiri'],['TIBC yüksek'], 'Hematopatoloji / anemi', 'P1'),
C('Mikrositer hipokrom anemi','Eritrositlerin küçük ve hemoglobinden fakir olduğu anemi paternidir.','Demir eksikliği, talasemi ve kronik hastalık anemisi mikrositer hipokrom anemi yapabilir. Ayırıcı tanıda ferritin, TIBC, RDW ve hemoglobin elektroforezi kullanılır.','Mikrositer anemide ilk ayrım demir eksikliği–talasemi–kronik hastalık üçlüsüdür.','Makrositer anemide DNA sentez bozukluğu; mikrositer anemide hemoglobin sentez bozukluğu ön plandadır.',['Demir eksikliği anemisi','TIBC yüksekliği','Ferritin düşüklüğü'],[], 'Hematopatoloji / anemi', 'P0'),
C('Hipersegmentli nötrofil','Beşten fazla lob içeren nötrofil görünümüdür.','Megaloblastik anemide DNA sentezi bozulduğu için hematopoietik hücrelerde nükleer olgunlaşma gecikir. Periferik yaymada hipersegmentli nötrofiller ve makro-ovalositler görülür.','Makrositer anemi + hipersegmentli nötrofil = megaloblastik anemi.','Mikrositer anemi hemoglobin sentez bozukluğudur; hipersegmentli nötrofil DNA sentez bozukluğunu gösterir.',['Megaloblastik anemi','Makro-ovalosit','B12 eksikliği'],[], 'Hematopatoloji / anemi', 'P0'),
C('Makro-ovalosit','Megaloblastik anemide görülen büyük, oval şekilli eritrosittir.','B12 veya folat eksikliğinde DNA sentezi bozulur ve eritroid öncüllerde nükleer-sitoplazmik uyumsuzluk gelişir. Bu durum periferde makro-ovalositlerle yansır.','Makro-ovalosit + hipersegmentli nötrofil megaloblastik anemi için güçlü ipucudur.','Retikülositozda makrositoz olabilir ama hipersegmentli nötrofil/makro-ovalosit kombinasyonu megaloblastik süreci destekler.',['Megaloblastik anemi','Hipersegmentli nötrofil','DNA sentezi'],[], 'Hematopatoloji / anemi', 'P1'),
C('Aplastik anemi','Kemik iliği hiposellülaritesi ve periferik pansitopeniyle seyreden kemik iliği yetmezliğidir.','Aplastik anemide hematopoietik kök hücre veya progenitör hücre hasarı nedeniyle eritrosit, lökosit ve trombosit üretimi azalır. Kemik iliği yağ dokusundan zengin ve hiposellülerdir.','Pansitopeni + yağlı hiposellüler ilik = aplastik anemi.','Hipersplenizmde hücreler periferde tutulur ve splenomegali beklenir; aplastik anemide üretim yetmezliği ve hiposellüler ilik vardır.',['Pansitopeni','Hiposellüler ilik','Hematopoietik kök hücre'],[], 'Hematopatoloji / kemik iliği', 'P0'),
C('Hiposellüler ilik','Kemik iliğinde hematopoietik hücrelerin belirgin azaldığı görünümüdür.','Hiposellüler ilik aplastik anemide yağ dokusu artışıyla birlikte görülür. Periferik pansitopeninin üretim yetersizliğine bağlı olduğunu destekler.','Pansitopenide hiposellüler ilik üretim yetmezliğini gösterir.','Hiposellüler ilik aplazi; hipersellüler ilik periferik yıkım veya etkisiz hematopoezle ilişkili olabilir.',['Aplastik anemi','Pansitopeni','Yağlı kemik iliği'],[], 'Hematopatoloji / kemik iliği', 'P1'),
C('Hematopoietik kök hücre','Kan hücrelerinin tüm serilerine kaynaklık eden multipotent kemik iliği hücresidir.','Aplastik anemide hematopoietik kök hücre hasarı veya immün baskılanması tüm kan serilerinde üretim azalmasına yol açar. Bu nedenle pansitopeni gelişir.','Tüm seriler düşükse kök hücre/kemik iliği üretim sorunu düşün.','Tek seri azalması daha sınırlı üretim/yıkım bozukluğu; tüm serilerin azalması kök hücre veya ilik düzeyi sorunu düşündürür.',['Aplastik anemi','Pansitopeni','Kemik iliği'],[], 'Hematopatoloji / kemik iliği', 'P1'),
C('Kontigüöz yayılım','Lezyonun komşu lenf nodu veya dokulara sıra izleyerek yayılmasıdır.','Klasik Hodgkin lenfomada lenf nodu tutulumu çoğu zaman komşu nod gruplarına düzenli ilerler. Bu özellik birçok non-Hodgkin lenfomadaki daha düzensiz yayılımdan ayrılır.','Hodgkin lenfoma için kontigüöz lenf nodu yayılımı klasik sınav ipucudur.','Non-Hodgkin lenfomada extranodal ve nonkontigüöz tutulum daha sık olabilir.',['Hodgkin lenfoma','Lenf nodu','Non-Hodgkin lenfoma'],[], 'Hematopatoloji / lenfoma', 'P1'),
C('Foliküler lenfoma','Germinal merkez B hücrelerinden köken alan, genellikle indolent B hücreli lenfomadır.','Foliküler lenfomada t(14;18) ile BCL2 aşırı ekspresyonu gelişir ve apoptoz baskılanır. Germinal merkezlerde normalde BCL2 düşük olması gerektiği için BCL2 pozitifliği patolojik ipucudur.','t(14;18) + BCL2 + indolent nodal lenfoma = foliküler lenfoma.','Burkitt lenfoma MYC ve çok yüksek proliferasyonla; foliküler lenfoma BCL2 ve indolent seyirle ayrılır.',['t(14;18)','BCL2','Germinal merkez'],[], 'Hematopatoloji / lenfoma', 'P0'),
C('t(14;18)','BCL2 genini immünoglobulin ağır zincir lokusuna taşıyan translokasyondur.','t(14;18) sonucunda BCL2 aşırı ekspresyonu olur ve germinal merkez B hücreleri apoptozdan kaçar. Bu olay foliküler lenfomanın klasik genetik temelidir.','t(14;18) = BCL2 = foliküler lenfoma.','t(8;14) MYC/Burkitt; t(14;18) BCL2/foliküler lenfoma ile eşleştirilir.',['Foliküler lenfoma','BCL2','Apoptoz inhibisyonu'],[], 'Moleküler patoloji / lenfoma', 'P0'),
C('BCL2 aşırı ekspresyonu','Antiapoptotik BCL2 proteininin normalden fazla üretilmesidir.','Foliküler lenfomada BCL2 aşırı ekspresyonu germinal merkez B hücrelerinin apoptozdan kaçmasına neden olur. Bu durum reaktif foliküllerden ayrımda önemlidir.','Foliküler lenfomada BCL2 pozitifliği apoptozdan kaçışı gösterir.','Burkitt’te MYC proliferasyonu; foliküler lenfomada BCL2 apoptoz inhibisyonu öne çıkar.',['Foliküler lenfoma','t(14;18)','Apoptoz inhibisyonu'],['BCL2 pozitifliği'], 'Moleküler patoloji / lenfoma', 'P1'),
C('Germinal merkez','Lenf folikülünde B hücre proliferasyonu, somatik hipermutasyon ve seçilimin gerçekleştiği bölgedir.','Foliküler lenfoma germinal merkez B hücrelerinden köken alır. Normal germinal merkezde apoptoz önemliyken, BCL2 aşırı ekspresyonu hücrelerin yaşamasını sağlar.','BCL2 pozitif germinal merkez foliküler lenfoma yönünde şüphe uyandırır.','Reaktif germinal merkez poliklonal ve BCL2 düşük; foliküler lenfoma klonal ve BCL2 pozitiftir.',['Foliküler lenfoma','BCL2','Reaktif folikül'],[], 'Hematopatoloji / lenfoid doku', 'P1'),
C('MYC aktivasyonu','MYC onkogeninin proliferasyonu artıracak şekilde etkinleşmesidir.','Burkitt lenfomada t(8;14) ile MYC immünoglobulin ağır zincir düzenleyici bölgesinin etkisine girer. Bu, çok yüksek proliferasyon ve starry-sky görünümünü açıklar.','t(8;14) + MYC + starry-sky = Burkitt lenfoma.','BCL2 hücre ölümünden kaçışı; MYC hücre proliferasyonunu artırır.',['Burkitt lenfoma','t(8;14)','Starry-sky görünümü'],['MYC'], 'Moleküler patoloji / lenfoma', 'P0'),
C('t(8;14)','MYC genini immünoglobulin ağır zincir lokusuna taşıyan translokasyondur.','t(8;14) Burkitt lenfomada MYC aktivasyonuna neden olur. Sonuçta çok hızlı çoğalan B hücreli tümör ve yüksek apoptotik hücre döngüsü gelişir.','t(8;14) = MYC = Burkitt lenfoma.','t(14;18) BCL2/foliküler lenfoma; t(8;14) MYC/Burkitt lenfoma ile eşleştirilir.',['Burkitt lenfoma','MYC aktivasyonu','Starry-sky görünümü'],[], 'Moleküler patoloji / lenfoma', 'P0'),
C('Starry-sky görünümü','Koyu tümör hücreleri arasında açık renkli tingible body makrofajlarının oluşturduğu histolojik paterndir.','Burkitt lenfomada çok yüksek proliferasyon ve apoptoz nedeniyle makrofajlar hücre artıklarını fagosite eder. Açık makrofajlar koyu tümör zemini üzerinde yıldızlı gökyüzü görünümü oluşturur.','Starry-sky + MYC + t(8;14) Burkitt lenfoma için klasiktir.','Foliküler lenfomada nodüler foliküler yapı; Burkitt’te diffuse yüksek proliferasyon ve starry-sky görünümü beklenir.',['Burkitt lenfoma','MYC aktivasyonu','Makrofaj'],['starry-sky'], 'Hematopatoloji / lenfoma', 'P0'),
C('JAK2 mutasyonu','JAK-STAT sinyalini otonom aktive ederek miyeloproliferasyona yol açabilen mutasyondur.','JAK2 V617F mutasyonu polisitemia vera, esansiyel trombositemi ve primer miyelofibrozda görülebilir. Hücreler büyüme faktörü sinyalinden bağımsız proliferasyon eğilimi kazanır.','Düşük EPO + eritrosit kitlesi artışı + JAK2 = polisitemia vera.','Sekonder polisitemide EPO yüksek/uyarıya bağlıdır; polisitemia verada klonal JAK2 aracılı proliferasyon vardır.',['Polisitemia vera','Esansiyel trombositemi','Düşük EPO'],['JAK2'], 'Miyeloproliferatif neoplaziler', 'P0'),
C('Düşük EPO','Eritropoietin düzeyinin baskılanmış olmasıdır.','Polisitemia verada eritrosit üretimi klonal ve otonom olduğu için böbrekten EPO salınımı negatif geri bildirimle düşer. Bu bulgu sekonder polisitemiden ayrımda değerlidir.','Polisitemia vera: yüksek eritrosit kitlesi + düşük EPO + JAK2.','Sekonder polisitemide hipoksi veya EPO üreten tümör nedeniyle EPO genellikle yüksektir.',['Polisitemia vera','JAK2 mutasyonu','Sekonder polisitemi'],['EPO düşük'], 'Miyeloproliferatif neoplaziler', 'P1'),
C('Panmiyeloz','Kemik iliğinde eritroid, miyeloid ve megakaryositik serilerin birlikte artmasıdır.','Polisitemia verada sadece eritrosit değil, tüm miyeloid serilerde klonal artış görülebilir. Bu nedenle kemik iliğinde panmiyeloz tanımlanır.','PV yalnız eritrosit artışı değildir; panmiyeloz miyeloproliferatif karakteri gösterir.','Sekonder polisitemide eritroid uyarı baskındır; panmiyeloz klonal miyeloproliferasyonu destekler.',['Polisitemia vera','JAK2 mutasyonu','Kemik iliği'],[], 'Miyeloproliferatif neoplaziler', 'P1'),
C('JAK2-CALR-MPL mutasyonları','Esansiyel trombositemi ve diğer MPN’lerde görülen sürücü mutasyon grubudur.','Esansiyel trombositemide klonal megakaryosit proliferasyonu JAK2, CALR veya MPL mutasyonlarıyla ilişkili olabilir. Bu mutasyonlar trombositozun reaktif değil klonal olduğunu destekler.','Kalıcı trombositoz + dev megakaryositler + JAK2/CALR/MPL = esansiyel trombositemi.','Reaktif trombositoz inflamasyon/kanama sonrası gelişir; klonal trombositoz sürücü mutasyonlarla desteklenir.',['Esansiyel trombositemi','Trombositoz','Megakaryosit'],['JAK2 CALR MPL'], 'Miyeloproliferatif neoplaziler', 'P1'),
C('Edinilmiş vWF kaybı','Aşırı trombositozda büyük vWF multimerlerinin azalmasına bağlı kanama eğilimidir.','Esansiyel trombositemide çok yüksek trombosit sayıları vWF multimerlerini bağlayıp tüketebilir. Bu nedenle tromboz eğilimine rağmen paradoksal kanama görülebilir.','Çok yüksek trombosit + kanama = edinilmiş vWF kaybı akılda olmalı.','Trombosit sayısı artışı tromboz riskini artırır; ancak aşırı artış vWF kaybıyla kanama da yapabilir.',['Esansiyel trombositemi','vWF multimerleri','Kanama'],[], 'Hemostaz patolojisi', 'P1'),
C('Dalgalı lif','Erken miyokart infarktında iskemiye bağlı uzamış/ondüle miyosit görünümüdür.','Miyokart infarktının erken döneminde lifler kontraksiyon ve ödem etkisiyle dalgalı görünüm alabilir. Ardından koagülasyon nekrozu ve nötrofil infiltrasyonu belirginleşir.','MI erken saatlerinde dalgalı lifler erken histolojik ipucudur.','Geç dönemde granülasyon dokusu ve skar; erken dönemde dalgalı lif ve koagülasyon nekrozu öne çıkar.',['Miyokart infarktı','Koagülasyon nekrozu','Nötrofil'],[], 'Kardiyovasküler patoloji', 'P1'),
C('Miyokart infarktında 3-7. gün rüptür riski','Makrofaj temizliğiyle duvarın geçici zayıfladığı dönemdir.','Miyokart infarktından 3-7 gün sonra nekrotik dokuyu makrofajlar temizlerken kollajen skar henüz yeterince oluşmamıştır. Bu ara dönem ventrikül duvar rüptürü, papiller kas rüptürü veya septal rüptür açısından risklidir.','MI’da rüptür riski en çok 3-7. günde makrofaj temizliği dönemindedir.','İlk 24 saatte aritmi; 3-7 günde rüptür; haftalar sonra skar/anevrizma daha çok sorulur.',['Makrofaj','Duvar rüptürü','Miyokart infarktı'],['3-7 gün','duvar rüptürü'], 'Kardiyovasküler patoloji', 'P0'),
C('Anitschkow hücresi','Romatizmal karditte görülen, dalgalı/katerpil nükleuslu aktive makrofajdır.','Anitschkow hücreleri Aschoff cisimciklerinin karakteristik hücresidir. Romatizmal ateşte moleküler benzerlik aracılı immün yanıtla miyokard tutulumu gelişir.','Aschoff cisimciği + Anitschkow hücresi = romatizmal kardit.','Enfektif endokardit vejetasyon/mikroorganizma; romatizmal kardit Aschoff cisimciği ve Anitschkow hücresiyle ayrılır.',['Aschoff cisimciği','Romatizmal ateş','Moleküler benzerlik'],[], 'Kardiyovasküler patoloji', 'P0'),
C('Komissür füzyonu','Kalp kapak yaprakçıklarının birleşme hattında fibrotik kaynaşmadır.','Kronik romatizmal kalp hastalığında özellikle mitral kapakta komissür füzyonu gelişir. Bu durum balık ağzı görünümü ve mitral stenozla sonuçlanabilir.','Romatizmal mitral stenozda komissür füzyonu klasik morfolojik bulgudur.','Kalsifik aort stenozunda kalsifik dejenerasyon; romatizmal stenozda komissür füzyonu öne çıkar.',['Mitral stenoz','Romatizmal ateş','Balık ağzı görünümü'],[], 'Kardiyovasküler patoloji', 'P1'),
C('Balık ağzı görünümü','Romatizmal mitral stenozda daralmış kapak açıklığının makroskopik görünümüdür.','Komissür füzyonu ve fibrotik kalınlaşma mitral kapak açıklığını daraltır. Makroskopide kapak orifisi balık ağzı veya düğme deliği şeklinde tarif edilir.','Mitral stenoz + komissür füzyonu + balık ağzı görünümü romatizmal hastalığı düşündürür.','Mitral kapak prolapsusunda miksomatöz gevşeme; romatizmal stenozda fibrotik komissür füzyonu vardır.',['Mitral stenoz','Komissür füzyonu','Romatizmal kalp hastalığı'],['balık ağzı'], 'Kardiyovasküler patoloji', 'P1'),
C('Septik emboli','Mikroorganizma içeren enfektif trombotik materyalin dolaşımla taşınmasıdır.','Enfektif endokarditte frajil vejetasyon parçaları koparak septik emboli oluşturabilir. Bu emboliler uzak dokuda infarkt, apse veya mikotik anevrizmaya yol açabilir.','Endokardit vejetasyonu frajilse emboli ve kapak destrüksiyonu riski yüksektir.','Steril tromboemboli mikroorganizma içermez; septik emboli enfeksiyon odağını uzak dokulara taşır.',['Enfektif endokardit','Vejetasyon','Kapak destrüksiyonu'],[], 'Kardiyovasküler patoloji', 'P0'),
C('Kapak destrüksiyonu','Kalp kapağının enfeksiyon veya inflamasyonla yapısal olarak yıkıma uğramasıdır.','Enfektif endokarditte mikroorganizma içeren büyük frajil vejetasyonlar kapak yaprakçıklarını yıkıma uğratabilir. Bu durum akut yetmezlik ve emboli riskini artırır.','Frajil enfektif vejetasyon = emboli + kapak destrüksiyonu riski.','Romatizmal hastalıkta fibrozis ve deformite; enfektif endokarditte aktif doku yıkımı ve septik materyal öne çıkar.',['Enfektif endokardit','Septik emboli','Vejetasyon'],[], 'Kardiyovasküler patoloji', 'P1'),
C('PAS pozitif globül','PAS boyasıyla pozitif boyanan hepatosit içi protein birikimidir.','Alfa-1 antitripsin eksikliğinde yanlış katlanan protein hepatositlerde birikir ve PAS pozitif globüller şeklinde görülebilir. Akciğerde ise proteaz-antiproteaz dengesizliği panasinüler amfizeme yol açar.','PAS pozitif hepatosit globülü + panasinüler amfizem = alfa-1 antitripsin eksikliği.','Glikojen de PAS pozitif olabilir; A1AT globülleri protein katlanma/birikim patolojisini gösterir.',['Alfa-1 antitripsin eksikliği','Panasinüler amfizem','Hepatosit birikimi'],[], 'Akciğer / karaciğer patolojisi', 'P0'),
C('Proteaz-antiproteaz dengesi','Akciğer dokusunda elastaz gibi proteazlar ile inhibitörleri arasındaki koruyucu dengedir.','Alfa-1 antitripsin normalde nötrofil elastazını baskılar. Eksiklikte proteaz aktivitesi alveol duvarını yıkar ve özellikle alt lob ağırlıklı panasinüler amfizem gelişir.','A1AT eksikliği akciğerde proteaz-antiproteaz dengesinin bozulmasıyla amfizem yapar.','Sigara ilişkili sentriasiner amfizem üst lob; A1AT eksikliği panasinüler ve alt lob ağırlıklıdır.',['Alfa-1 antitripsin eksikliği','Elastaz','Panasinüler amfizem'],[], 'Akciğer patolojisi', 'P0'),
C('Eggshell kalsifikasyon','Hiler lenf nodu periferinde yumurta kabuğu tarzı kalsifikasyondur.','Silikoziste hiler lenf nodlarında periferik ince kalsifikasyon görülebilir. Bu bulgu üst lob fibrotik nodülleri ve tüberküloz risk artışıyla birlikte değerlidir.','Üst lob nodülleri + hiler eggshell kalsifikasyon = silikozis.','Asbestoz daha çok alt lob interstisyel fibrozis ve plevral plakla; silikozis üst lob ve eggshell kalsifikasyonla ilişkilidir.',['Silikozis','Hiler lenf nodu','Pnömokonyoz'],['yumurta kabuğu kalsifikasyonu','eggshell kalsifikasyon'], 'Akciğer patolojisi', 'P0'),
C('Plevral plak','Asbest maruziyetine bağlı parietal plevrada gelişen fibrotik plaklardır.','Plevral plaklar asbest maruziyetinin en sık morfolojik göstergelerindendir. Kendileri malign değildir ancak asbest maruziyeti mezotelyoma ve akciğer karsinomu riskini artırır.','Asbest maruziyeti sorusunda plevral plak maruziyet göstergesidir.','Silikoziste hiler eggshell kalsifikasyon; asbestte plevral plak ve alt lob fibrozis daha tipiktir.',['Asbest maruziyeti','Mezotelyoma','Akciğer karsinomu'],[], 'Akciğer patolojisi', 'P1'),
C('Calretinin-WT1 pozitifliği','Mezotelyal kökeni destekleyen immünohistokimyasal marker paternidir.','Malign mezotelyomada calretinin ve WT1 gibi mezotelyal markerlar pozitif olabilir. Bu markerlar plevral adenokarsinom metastazından ayırıcı tanıda kullanılır.','Plevral tümör + asbest + calretinin/WT1 pozitifliği mezotelyomayı destekler.','Adenokarsinom markerları farklıdır; calretinin-WT1 mezotelyal diferansiyasyonu gösterir.',['Mezotelyoma','Asbest','Plevra'],['calretinin WT1','WT1','calretinin'], 'İmmünohistokimya', 'P1'),
C('Subepitelyal depozit','Glomerül bazal membranının epitel/podosit tarafında immün birikimdir.','Membranöz nefropatide immün kompleksler podosit tarafında subepitelyal yerleşir. Bu birikimler kapiller duvar kalınlaşması ve spike-and-dome görünümü oluşturur.','Nefrotik sendrom + subepitelyal depozit + spike-and-dome = membranöz nefropati.','Poststreptokoksik GN’de de hump subepitelyal olabilir; membranözde diffüz kapiller duvar boyunca spike-and-dome paterni öne çıkar.',['Membranöz nefropati','Spike and dome','Podosit'],[], 'Renal patoloji', 'P0'),
C('Spike-and-dome görünümü','Membranöz nefropatide GBM çıkıntıları ve immün depozitlerin oluşturduğu mikroskobik paterndir.','Subepitelyal immün depozitler arasında bazal membran materyali uzantılar oluşturur. Gümüş boyayla spike, depozitlerle dome görünümü membranöz nefropatiyi destekler.','Spike-and-dome membranöz nefropatinin klasik morfolojik ipucudur.','Subepitelyal hump poststreptokoksik GN; spike-and-dome membranöz nefropatiyle ilişkilidir.',['Membranöz nefropati','Subepitelyal depozit','PLA2R'],['spike and dome'], 'Renal patoloji', 'P0'),
C('PLA2R','Primer membranöz nefropatide hedeflenebilen podosit antijenidir.','Fosfolipaz A2 reseptörüne karşı antikorlar primer membranöz nefropatide subepitelyal immün depozit oluşumuna katkı verir. Anti-PLA2R pozitifliği primer formu destekleyebilir.','Membranöz nefropatide PLA2R primer form için yüksek değerli ipucudur.','Sekonder membranöz nefropati malignite, enfeksiyon veya ilaçlarla ilişkili olabilir; PLA2R primer formu destekler.',['Membranöz nefropati','Anti-PLA2R','Podosit'],[], 'Renal patoloji', 'P0'),
C('Mezangial IgA birikimi','Glomerül mezangiumunda IgA ağırlıklı immün depozit bulunmasıdır.','IgA nefropatisinde mukozal enfeksiyonlardan kısa süre sonra mezangial IgA depozitleri makroskopik hematüriye yol açabilir. İmmünfloresanda mezangial IgA boyanması beklenir.','ÜSYE’den 1-2 gün sonra hematüri + mezangial IgA = IgA nefropatisi.','Poststreptokoksik GN haftalar sonra ve düşük C3 ile; IgA nefropatisi daha erken/synpharyngitic hematüriyle ayrılır.',['IgA nefropatisi','Mezangium','Synpharyngitic hematüri'],['mezangial IgA','IgA birikimi'], 'Renal patoloji', 'P0'),
C('Synpharyngitic hematüri','Üst solunum yolu enfeksiyonuyla eş zamanlı veya hemen sonrasında gelişen hematüridir.','IgA nefropatisinde mukozal IgA yanıtı nedeniyle hematüri enfeksiyondan 1-2 gün sonra veya eş zamanlı gelişebilir. Bu zamanlama poststreptokoksik GN’den ayırıcıdır.','Synpharyngitic hematüri IgA nefropatisinin zamanlama ipucudur.','PSGN genellikle enfeksiyondan haftalar sonra; IgA nefropatisi enfeksiyonla eş zamanlı/çok kısa arayla olur.',['IgA nefropatisi','Mezangial IgA birikimi','Makroskopik hematüri'],[], 'Renal patoloji', 'P0'),
C('Mezangium','Glomerül kapillerleri arasında destek ve matriks sağlayan hücresel-stromal bölgedir.','Mezangium immün komplekslerin birikebildiği glomerüler alandır. IgA nefropatisinde mezangial IgA birikimi ve mezangial proliferasyon tipiktir.','IgA nefropatisinde depozitlerin ana yeri mezangiumdur.','Subepitelyal depozit podosit tarafını; mezangial depozit kapiller arası destek bölgesini ifade eder.',['IgA nefropatisi','Mezangial proliferasyon','İmmünfloresan'],[], 'Renal patoloji', 'P1'),
C('Granüler immünfloresan','İmmün komplekslerin düzensiz tanecikli boyanma paterni oluşturmasıdır.','Poststreptokoksik GN gibi immün kompleks hastalıklarında IgG ve C3 glomerüllerde granüler paternle boyanır. Bu patern anti-GBM hastalığındaki lineer boyanmadan ayrılır.','Granüler IF immün kompleks; lineer IF anti-GBM hastalığı lehinedir.','Lineer boyanma bazal membran boyunca sürekli antikor bağlanmasını; granüler boyanma depozit tarzı immün kompleksi gösterir.',['Poststreptokoksik GN','IgG C3','Anti-GBM'],['granüler IF','immünfloresan'], 'Renal patoloji', 'P0'),
C('Poststreptokoksik glomerülonefrit','Streptokok enfeksiyonu sonrası immün kompleks aracılı nefritik sendromdur.','Poststreptokoksik GN enfeksiyondan haftalar sonra hematüri, ödem, hipertansiyon ve düşük C3 ile ortaya çıkabilir. Elektron mikroskopide subepitelyal hump depozitleri klasik ipucudur.','Strep sonrası haftalar + düşük C3 + subepitelyal hump = PSGN.','IgA nefropatisi enfeksiyonla eş zamanlı/1-2 gün; PSGN haftalar sonra gelişir.',['Subepitelyal hump','Düşük C3','Granüler immünfloresan'],['poststreptokoksik GN','PSGN'], 'Renal patoloji', 'P0'),
C('Subepitelyal hump','Poststreptokoksik GN’de görülen kubbe şeklinde subepitelyal immün kompleks depozitidir.','Elektron mikroskopide glomerül bazal membranının epitel tarafında büyük hump depozitleri izlenebilir. Bu bulgu enfeksiyon sonrası immün kompleks nefritini destekler.','Subepitelyal hump PSGN için klasik EM bulgusudur.','Spike-and-dome membranöz nefropati; hump depozit poststreptokoksik GN ile eşleştirilir.',['Poststreptokoksik glomerülonefrit','Granüler immünfloresan','Düşük C3'],[], 'Renal patoloji', 'P0'),
C('Clear cell görünümü','Hücre sitoplazmasının lipid/glikojen nedeniyle berrak izlenmesidir.','Berrak hücreli renal hücreli karsinomda sitoplazma lipid ve glikojenden zengin olduğu için clear cell görünümü oluşur. VHL kaybı ve HIF aracılı anjiyojenik sinyal artışıyla ilişkilidir.','Sarı-kahverengi böbrek kitlesi + clear cell + VHL = renal hücreli karsinom.','Onkositik hücre eozinofilik granüler sitoplazma; clear cell berrak sitoplazma ile ayrılır.',['Renal hücreli karsinom','VHL kaybı','HIF'],['clear cell'], 'Renal tümör patolojisi', 'P1'),
C('VHL kaybı','VHL tümör baskılayıcı gen fonksiyonunun kaybıdır.','VHL kaybında HIF yıkılamaz ve anjiyogenezle ilişkili genlerin ekspresyonu artar. Berrak hücreli renal hücreli karsinom patogenezinde temel mekanizmadır.','Clear cell RCC’de VHL kaybı HIF stabilizasyonu üzerinden tümörleşmeyi destekler.','Wilms tümörü WT1 ile; clear cell RCC VHL-HIF aksıyla ilişkilidir.',['Renal hücreli karsinom','HIF stabilizasyonu','Clear cell görünümü'],['VHL'], 'Moleküler tümör patolojisi', 'P0'),
C('HIF stabilizasyonu','Hipoksi-indüklenebilir faktörün yıkılamayıp hücre içinde birikmesidir.','Normalde VHL proteini HIF’i yıkıma yönlendirir. VHL kaybında HIF stabilize olur, VEGF gibi anjiyojenik sinyaller artar ve renal hücreli karsinom gelişimine katkı sağlar.','VHL kaybı → HIF stabilizasyonu → VEGF artışı → clear cell RCC.','Gerçek hipokside HIF fizyolojik olarak artar; VHL kaybında oksijen normal olsa da HIF yıkılamaz.',['VHL kaybı','VEGF','Renal hücreli karsinom'],['HIF'], 'Moleküler tümör patolojisi', 'P1'),
C('Renal ven invazyonu','Böbrek tümörünün renal vene ilerleyebilmesidir.','Renal hücreli karsinom renal vene ve hatta vena kavaya uzanma eğilimi gösterebilir. Hematolojik yayılım ve paraneoplastik bulgularla birlikte sınavda ipucu olabilir.','RCC’de renal ven invazyonu klasik yayılım özelliğidir.','Wilms tümörü çocukluk böbrek tümörü; erişkin clear cell RCC renal ven invazyonuyla öne çıkar.',['Renal hücreli karsinom','Clear cell görünümü','Paraneoplastik sendrom'],[], 'Renal tümör patolojisi', 'P1'),
C('Nefroblastom','Wilms tümörünün diğer adı olan çocukluk çağı böbrek tümörüdür.','Nefroblastom blastemal, epitelyal ve stromal komponentlerden oluşan triphasic histoloji gösterebilir. WT1 ilişkisi ve WAGR gibi sendromlarla bağlantısı sınav açısından önemlidir.','Çocuk böbrek kitlesi + triphasic histoloji = nefroblastom/Wilms tümörü.','Renal hücreli karsinom erişkin ve clear cell; nefroblastom çocukluk çağı böbrek tümörüdür.',['Wilms tümörü','WT1','Triphasic histoloji'],[], 'Pediatrik tümör patolojisi', 'P0'),
C('Triphasic histoloji','Bir tümörde üç farklı doku/komponent paterninin birlikte görülmesidir.','Wilms tümöründe blastemal, epitelyal ve stromal komponentlerin birlikte bulunması triphasic histoloji olarak tanımlanır. Bu kombinasyon çocukluk böbrek kitlesi tanısında öğretici ipucudur.','Wilms tümörü triphasic histoloji: blastemal + epitelyal + stromal.','Tek tip clear cell görünümü RCC’ye; üçlü komponent Wilms tümörüne daha uygundur.',['Wilms tümörü','Nefroblastom','WT1'],['triphasic histoloji'], 'Pediatrik tümör patolojisi', 'P1'),
C('WAGR sendromu','Wilms tümörü, aniridi, genitoüriner anomaliler ve gelişimsel gerilik birlikteliğidir.','WAGR sendromu WT1 bölgesi kaybıyla ilişkili olabilir ve Wilms tümörü riskini artırır. Çocuk böbrek kitlesiyle birlikte aniridi/genitoüriner anomali ipucu tanısal değer taşır.','Wilms + aniridi + GU anomali = WAGR sendromu.','Denys-Drash da WT1 ilişkili olabilir; WAGR’de aniridi ve genitoüriner anomaliler klasik akılda tutulur.',['Wilms tümörü','WT1','Aniridi'],['WAGR'], 'Pediatrik tümör patolojisi', 'P1'),
C('Malign osteoid','Malign tümör hücreleri tarafından üretilen osteoid matrikstir.','Osteosarkom tanısında tümör hücrelerinin doğrudan malign osteoid üretmesi temel patolojik kriterdir. Genellikle adölesanda metafiz çevresinde görülür.','Kemik tümöründe malign osteoid üretimi osteosarkom lehinedir.','Ewing sarkomu küçük yuvarlak mavi hücreli tümördür ve malign osteoid üretmez.',['Osteosarkom','Metafiz','Sunburst görünümü'],[], 'Kemik tümörü patolojisi', 'P0'),
C('Sunburst görünümü','Agresif kemik tümörlerinde periost reaksiyonunun ışınsal görünümüdür.','Osteosarkomda hızlı büyüyen tümör periostu kaldırır ve ışınsal kemik yapımı sunburst görünümü oluşturabilir. Codman üçgeniyle birlikte agresif kemik lezyonunu destekler.','Adölesan metafiz tümörü + malign osteoid + sunburst = osteosarkom.','Onion-skin periost reaksiyonu Ewing sarkomu; sunburst osteosarkomla daha klasik eşleşir.',['Osteosarkom','Malign osteoid','Codman üçgeni'],['sunburst'], 'Kemik tümörü patolojisi', 'P1'),
C('Codman üçgeni','Agresif kemik lezyonunda periostun kaldırılmasıyla oluşan üçgen periostal reaksiyondur.','Osteosarkom gibi hızlı büyüyen kemik tümörleri periostu kemikten ayırır ve kenarda üçgen yeni kemik görünümü oluşturur. Bu bulgu malign/agresif lezyonu düşündürür.','Codman üçgeni agresif kemik tümörü ipucudur; osteosarkomla sık sorulur.','Sunburst ışınsal periost reaksiyonu; Codman üçgeni periostun kaldırıldığı kenar görünümüdür.',['Osteosarkom','Sunburst görünümü','Malign osteoid'],[], 'Kemik tümörü patolojisi', 'P1'),
C('EWSR1-FLI1 füzyonu','Ewing sarkomunda t(11;22) sonucu oluşan onkojenik füzyon genidir.','EWSR1-FLI1 füzyonu küçük yuvarlak mavi hücreli Ewing sarkomunun moleküler temelidir. Diafizer kemik tümörü ve onion-skin periost reaksiyonuyla birlikte tanısal değer taşır.','t(11;22) = EWSR1-FLI1 = Ewing sarkomu.','Osteosarkom malign osteoid; Ewing sarkomu EWSR1-FLI1 ve küçük yuvarlak mavi hücre morfolojisiyle ayrılır.',['Ewing sarkomu','t(11;22)','Onion-skin periost reaksiyonu'],['EWSR1-FLI1'], 'Kemik tümörü patolojisi', 'P0'),
C('Onion-skin periost reaksiyonu','Katmanlı periost reaksiyonu görünümüdür.','Ewing sarkomunda tümörün hızlı ama aralıklı büyümesi periostta soğan zarı benzeri katmanlanma oluşturabilir. Uzun kemik diafizindeki küçük yuvarlak mavi hücreli tümörle birlikte anlamlıdır.','Diafiz + küçük yuvarlak mavi hücre + onion-skin = Ewing sarkomu.','Sunburst/Codman daha çok osteosarkom; onion-skin Ewing sarkomu için klasik ipucudur.',['Ewing sarkomu','EWSR1-FLI1','Diafiz'],['onion-skin'], 'Kemik tümörü patolojisi', 'P1'),
C('Flexner-Wintersteiner rozeti','Retinoblastomda görülebilen gerçek lümenli tümör hücre rozeti yapısıdır.','Retinoblastomda tümör hücreleri merkezi lümen etrafında dizilerek Flexner-Wintersteiner rozetleri oluşturabilir. RB1 kaybı ve lökokori ile birlikte tanısal ipucu değerindedir.','Lökokori + RB1 + Flexner-Wintersteiner rozeti = retinoblastom.','Homer Wright rozeti nöroblastom gibi nöroektodermal tümörlerde; Flexner-Wintersteiner retinoblastomda daha klasiktir.',['Retinoblastom','RB1','Lökokori'],[], 'Göz / pediatrik tümör patolojisi', 'P0'),
C('Knudson iki vuruş hipotezi','Tümör baskılayıcı genlerde iki alelin de işlev kaybıyla tümör gelişimini açıklayan modeldir.','Retinoblastomda RB1 geninin iki alelinin kaybı gerekir. Kalıtsal olgularda ilk vuruş germline olduğu için ikinci vuruş daha erken ve bilateral tümörlere yol açabilir.','Kalıtsal retinoblastom = germline ilk vuruş + erken/bilateral hastalık.','Onkogenlerde tek aktive edici vuruş yeterli olabilir; tümör baskılayıcı genlerde iki vuruş mantığı kullanılır.',['RB1','Retinoblastom','Germline mutasyon'],['Knudson','iki vuruş'], 'Moleküler tümör patolojisi', 'P0'),
C('Germline RB1 mutasyonu','RB1 genindeki kalıtsal ilk vuruştur.','Germline RB1 mutasyonu taşıyan çocuklarda tüm hücrelerde bir alel kayıptır. Retinada ikinci alelin kaybı erken yaşta ve sıklıkla bilateral retinoblastoma neden olabilir.','Bilateral/erken retinoblastomda germline RB1 mutasyonu düşün.','Sporadik olguda iki somatik vuruş gerekir; kalıtsal olguda ilk vuruş germline olarak hazırdır.',['Retinoblastom','Knudson iki vuruş hipotezi','Bilateral'],['germline RB1'], 'Moleküler tümör patolojisi', 'P1'),
]

# Deduplicate and filter active exacts
out=[]; skipped=[]; seen=set()
for c in raw:
    norm=fold_tr(c['term'])
    aliases=list(dict.fromkeys(c.get('aliases',[])+[c['term']]))
    alias_norms=[fold_tr(a) for a in aliases]
    if norm in seen: continue
    if any(n in active for n in alias_norms):
        skipped.append({'term':c['term'], 'reason':'already active exact term/alias'})
        continue
    count, examples=find_examples(c['term'], c.get('aliases',[])+c.get('safe',[]))
    # keep if exact/source variant appears or critical curated from pathology card context
    entry={
        'id':'v401-pathology-'+slug(c['term']),
        'term':c['term'],
        'aliases':aliases,
        'normalizedTerm':norm,
        'TurkishName':c['term'],
        'EnglishName':'',
        'category':'Tıbbi Patoloji',
        'subcategory':c['subcategory'],
        'sourceLayer':'V401 medical-pathology-focused glossary expansion',
        'previewDefinition':c['short'],
        'preAnswerSafeDefinition':c['short'],
        'shortDefinition':c['short'],
        'definition':c['short'],
        'detailedExplanation':c['post'],
        'postAnswerExplanation':c['post'],
        'postAnswerExpandedExplanation':c['post'],
        'tusPearl':c['pearl'],
        'examPearl':c['pearl'],
        'differentialPoint':c['diff'],
        'clinicalRelevance':c['post'],
        'safeNestedTerms':c['safe'],
        'relatedTerms':c['safe'],
        'relatedBranches':['medical-pathology'],
        'sourceArea':'Tıbbi Patoloji',
        'sourceFilePath':'src/data/cases.js; src/data/tusPearlCards.js; src/data/tusPearlMedicalPathologyFirst84Overrides.js',
        'sourceFiles':['src/data/cases.js','src/data/tusPearlCards.js','src/data/tusPearlMedicalPathologyFirst84Overrides.js'],
        'occurrenceCount':count,
        'sourceTextExamples':examples,
        'matchingPriority':c.get('matchingPriority',88),
        'standaloneSafe':True,
        'phraseOnly':c.get('phraseOnly',True),
        'caseSensitiveDisplay':False,
        'answerLeakRisk':'low',
        'ambiguityRisk':c.get('ambiguityRisk','low'),
        'priority':c.get('priority','P1'),
        'recommendation':'addNewEntry',
        'existingGlossaryStatus':'missingActiveGlossary',
        'reasonForRecommendation':'Tıbbi patoloji olguları ve hap kartlarında morfoloji, patogenez, mikroskopi, immünohistokimya, renal/hematolojik/kardiyopulmoner patoloji veya tümör biyolojisi açısından soru çözdüren öğretici bir kavramdır; aktif glossary exact term/alias setinde bulunmadığı için eklendi.',
        'notes':'Açıklamalar güncel patoloji, histopatoloji ve klinik korelasyon kaynaklarıyla doğrulanmıştır; kullanıcı isteğine uygun olarak glossary metinlerine referans eklenmemiştir.'
    }
    out.append(entry); seen.add(norm)

# write js
js_path=ROOT/'src/data/tusGlossaryV401PathologyExpansionIndex.js'
js='''// V401 — Medical Pathology-focused glossary expansion.\n// Generated after scanning Medical Pathology cases, TUS Pearl cards and first-84 Pathology Hap card overrides.\n// Definitions are educational and reference-free in UI text.\n\nexport const TUS_GLOSSARY_V401_PATHOLOGY_EXPANSION_TERMS = '''+json.dumps(out,ensure_ascii=False,indent=2)+''';\n'''
js_path.write_text(js,encoding='utf-8')
# update glossary.js
util=ROOT/'src/utils/glossary.js'
text=util.read_text(encoding='utf-8')
imp="import { TUS_GLOSSARY_V401_PATHOLOGY_EXPANSION_TERMS } from '../data/tusGlossaryV401PathologyExpansionIndex.js';\n"
if imp not in text:
    text=text.replace("import { TUS_GLOSSARY_V400_MICROBIOLOGY_EXPANSION_TERMS } from '../data/tusGlossaryV400MicrobiologyExpansionIndex.js';\n", "import { TUS_GLOSSARY_V400_MICROBIOLOGY_EXPANSION_TERMS } from '../data/tusGlossaryV400MicrobiologyExpansionIndex.js';\n"+imp)
spread='  ...TUS_GLOSSARY_V401_PATHOLOGY_EXPANSION_TERMS,\n'
if spread not in text:
    text=text.replace('  ...TUS_GLOSSARY_V400_MICROBIOLOGY_EXPANSION_TERMS,\n', '  ...TUS_GLOSSARY_V400_MICROBIOLOGY_EXPANSION_TERMS,\n'+spread)
util.write_text(text,encoding='utf-8')
# reports
REPORT.mkdir(parents=True,exist_ok=True)
(REPORT/'medical-pathology-glossary-additions-v401.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
# csv
csv_path=REPORT/'medical-pathology-glossary-additions-v401.csv'
cols=['id','term','aliases','category','subcategory','priority','shortDefinition','postAnswerExplanation','tusPearl','differentialPoint','safeNestedTerms','occurrenceCount','sourceTextExamples']
with csv_path.open('w',encoding='utf-8-sig',newline='') as f:
    w=csv.DictWriter(f,fieldnames=cols); w.writeheader()
    for e in out:
        row={k:e.get(k,'') for k in cols}
        row['aliases']=' | '.join(e['aliases']); row['safeNestedTerms']=' | '.join(e['safeNestedTerms']); row['sourceTextExamples']=' || '.join(x['text'] for x in e['sourceTextExamples'])
        w.writerow(row)
# scan sources
sources=[
 {'sourceFilePath':'src/data/cases.js','contentType':'medical-pathology clinical cases','recordCount':51,'textFieldCount':sum(1 for f in fields if f['sourceFilePath'].startswith('src/data/cases.js')),'scannedFields':'all recursive string fields from pathology-related cases'},
 {'sourceFilePath':'src/data/tusPearlCards.js','contentType':'medical-pathology TUS Pearl cards','recordCount':84,'textFieldCount':sum(1 for f in fields if f['sourceFilePath'].startswith('src/data/tusPearlCards.js')),'scannedFields':'all recursive string fields from Tıbbi Patoloji cards'},
 {'sourceFilePath':'src/data/tusPearlMedicalPathologyFirst84Overrides.js','contentType':'medical-pathology Hap Kart overrides','recordCount':84,'textFieldCount':sum(1 for f in fields if f['sourceFilePath'].startswith('src/data/tusPearlMedicalPathologyFirst84Overrides.js')),'scannedFields':'front, back, answer, explanation, tusTip, differentialNote, keywords and nested strings'},
]
(REPORT/'medical-pathology-glossary-scan-sources-v401.json').write_text(json.dumps(sources,ensure_ascii=False,indent=2),encoding='utf-8')
# summary
from collections import Counter
pc=Counter(e['priority'] for e in out)
sub=Counter(e['subcategory'] for e in out)
summary=f'''# V401 Tıbbi Patoloji Glossary Expansion Summary\n\nV400 üzerine Tıbbi Patoloji odaklı yeni glossary katmanı eklenmiştir. Açıklamalar referanssız UI metni olacak şekilde yazılmış; kaynak kontrolü ayrı yapılmıştır.\n\n## Tarama\n- Tıbbi Patoloji klinik olgu: 51\n- Tıbbi Patoloji TUS Pearl kartı: 84\n- Tıbbi Patoloji hap kart override entry: 84\n- Toplam taranan text field: {len(fields)}\n\n## Sonuç\n- Curated aday bankası: {len(raw)}\n- Eklenen yeni glossary entry: {len(out)}\n- Aktif glossary exact term/alias nedeniyle atlanan: {len(skipped)}\n\n## Öncelik\n- P0 kritik entry: {pc.get('P0',0)}\n- P1 yüksek öğretici/TUS değerli entry: {pc.get('P1',0)}\n- P2 destekleyici/nested entry: {pc.get('P2',0)}\n\n## En yoğun alt kategoriler\n'''
for k,v in sub.most_common(12): summary+=f'- {k}: {v}\n'
summary+='\n## Eklenen örnek terimler\n'+', '.join(e['term'] for e in out[:60])+'\n'
(REPORT/'medical-pathology-glossary-additions-v401-summary.md').write_text(summary,encoding='utf-8')
(REPORT/'medical-pathology-glossary-skipped-v401.json').write_text(json.dumps(skipped,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'rawCandidates':len(raw),'added':len(out),'skippedActive':len(skipped),'p0':pc.get('P0',0),'p1':pc.get('P1',0),'p2':pc.get('P2',0)},ensure_ascii=False,indent=2))
